CREATE TABLE VA_RAW_InauguralCommittee
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  committee_code VARCHAR(150),
  committee_name VARCHAR(150),
  run_id int,
  is_amendment VARCHAR(150),
  date_changes_took_effect VARCHAR(150),
  committee_street_address VARCHAR(150),
  committee_suite VARCHAR(150),
  committee_city VARCHAR(150),
  committee_state VARCHAR(150),
  committee_zip_code VARCHAR(150),
  committee_email_address VARCHAR(150),
  committee_phone VARCHAR(150),
  committee_website VARCHAR(150),
  elected_official_salutation VARCHAR(150),
  elected_official_first_name VARCHAR(150),
  elected_official_middle_name VARCHAR(150),
  elected_official_last_name VARCHAR(150),
  elected_official_suffix VARCHAR(150),
  elected_official_street_address VARCHAR(150),
  elected_official_suite VARCHAR(150),
  elected_official_city VARCHAR(150),
  elected_official_state VARCHAR(150),
  elected_official_zip_code VARCHAR(150),
  treasurer_salutation VARCHAR(150),
  treasurer_first_name VARCHAR(150),
  treasurer_middle_name VARCHAR(150),
  treasurer_last_name VARCHAR(150),
  treasurer_suffix VARCHAR(150),
  treasurer_business_street_address VARCHAR(150),
  treasurer_business_suite VARCHAR(150),
  treasurer_business_city VARCHAR(150),
  treasurer_business_state VARCHAR(150),
  treasurer_business_zip_code VARCHAR(150),
  treasurer_street_address VARCHAR(150),
  treasurer_suite VARCHAR(150),
  treasurer_city VARCHAR(150),
  treasurer_state VARCHAR(150),
  treasurer_zip_code VARCHAR(150),
  treasurer_email VARCHAR(150),
  treasurer_day_time_phone_number VARCHAR(150),
  custodian_position_or_title VARCHAR(150),
  custodian_salutation VARCHAR(150),
  custodian_first_name VARCHAR(150),
  custodian_middle_name VARCHAR(150),
  custodian_last_name VARCHAR(150),
  custodian_suffix VARCHAR(150),
  custodian_business_address VARCHAR(150),
  custodian_business_suite_number VARCHAR(150),
  custodian_business_city VARCHAR(150),
  custodian_business_state VARCHAR(150),
  custodian_business_zip_code VARCHAR(150),
  custodian_street_address VARCHAR(150),
  custodian_suite VARCHAR(150),
  custodian_city VARCHAR(150),
  custodian_state VARCHAR(150),
  custodian_zip_code VARCHAR(150),
  custodian_email_address VARCHAR(150),
  custodian_day_time_phone_number VARCHAR(150),
  address_maintain_street_address VARCHAR(150),
  address_maintain_suite VARCHAR(150),
  address_maintain_city VARCHAR(150),
  address_maintain_state VARCHAR(150),
  address_maintain_zip_code VARCHAR(150),
  filing_method VARCHAR(150),
  approved_vendor VARCHAR(150),
  elected_office_name VARCHAR(150),
  other_office_name VARCHAR(150),
  date_first_contribution_accepted DATE,
  date_committee_organized DATE,
  date_campaign_depository_designated DATE,
  date_treasurer_appointed DATE,
  date_first_expenditure_made DATE,
  date_statement_of_qualification_filed DATE,
  data_source_url VARCHAR(150) DEFAULT NULL,
  created_by VARCHAR(150) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(150),
  UNIQUE KEY md5 (md5_hash),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
