CREATE TABLE VA_RAW_ReferendumCommittee
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  run_id int,
  committee_code VARCHAR(200),
  committee_name VARCHAR(200),
  is_amendment BOOLEAN,
  date_changes_took_effect DATE,
  committee_acronym VARCHAR(200),
  committee_street_address VARCHAR(200),
  committee_suite VARCHAR(200),
  committee_city VARCHAR(200),
  committee_state VARCHAR(200),
  committee_zip_code VARCHAR(200),
  committee_email_address VARCHAR(200),
  committee_phone VARCHAR(200),
  committee_website VARCHAR(200),
  affiliated_organization_name VARCHAR(200),
  affiliated_street_address VARCHAR(200),
  affiliated_suite VARCHAR(200),
  affiliated_city VARCHAR(200),
  affiliated_state VARCHAR(200),
  affiliated_zip_code VARCHAR(200),
  relationship_to_organization VARCHAR(200),
  treasurer_salutation VARCHAR(200),
  treasurer_first_name VARCHAR(200),
  treasurer_middle_name VARCHAR(200),
  treasurer_last_name VARCHAR(200),
  treasurer_suffix VARCHAR(200),
  treasurer_business_street_address VARCHAR(200),
  treasurer_business_suite VARCHAR(200),
  treasurer_business_city VARCHAR(200),
  treasurer_business_state VARCHAR(200),
  treasurer_business_zip_code VARCHAR(200),
  treasurer_street_address VARCHAR(200),
  treasurer_suite VARCHAR(200),
  treasurer_city VARCHAR(200),
  treasurer_state VARCHAR(200),
  treasurer_zip_code VARCHAR(200),
  treasurer_email VARCHAR(200),
  treasurer_daytime_phone_number VARCHAR(200),
  custodian_position_or_title VARCHAR(200),
  custodian_salutation VARCHAR(200),
  custodian_first_name VARCHAR(200),
  custodian_middle_name VARCHAR(200),
  custodian_last_name VARCHAR(200),
  custodian_suffix VARCHAR(200),
  custodian_business_address VARCHAR(200),
  custodian_business_suite_number VARCHAR(200),
  custodian_business_city VARCHAR(200),
  custodian_business_state VARCHAR(200),
  custodian_business_zip_code VARCHAR(200),
  custodian_street_address VARCHAR(200),
  custodian_suite VARCHAR(200),
  custodian_city VARCHAR(200),
  custodian_state VARCHAR(200),
  custodian_zip_code VARCHAR(200),
  address_maintain_street_address VARCHAR(200),
  address_maintain_suite VARCHAR(200),
  address_maintain_city VARCHAR(200),
  address_maintain_state VARCHAR(200),
  address_maintain_zip_code VARCHAR(200),
  filing_method VARCHAR(200),
  approved_vendor VARCHAR(200),
  submitted_on DATE,
  accepted_on DATE,
  referendum_date DATE,
  custodian_email VARCHAR(200),
  custodian_daytime_phone_number VARCHAR(200),
  date_first_contribution_accepted DATE,
  date_first_expenditure_made DATE,
  date_treasurer_appointed DATE,
  date_campaign_depository_designated DATE,
  is_local BOOLEAN,
  is_statewide BOOLEAN,
  is_regional BOOLEAN,
  referendum_location VARCHAR(200),
  position_of_referendum VARCHAR(200),
  referendum_subject VARCHAR(200),
  data_source_url VARCHAR(200) DEFAULT NULL,
  created_by VARCHAR(200) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(200),
  UNIQUE KEY md5 (md5_hash),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
