CREATE TABLE VA_RAW_SCHEDULEH
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  run_id int,
  schedule_H_id VARCHAR(255),
  report_id VARCHAR(255),
  beginning_balance VARCHAR(255),
  contributions_received VARCHAR(255),
  schedule_C_total VARCHAR(255),
  loans_received_total VARCHAR(255),
  contributions_and_receipts_received VARCHAR(255),
  total_expendable_funds VARCHAR(255),
  total_in_kind_and_expenditures VARCHAR(255),
  loans_paid_total VARCHAR(255),
  schedule_total VARCHAR(255),
  total_payments_made VARCHAR(255),
  expendable_funds_balance VARCHAR(255),
  total_un_paid_debts VARCHAR(255),
  balance_at_start_of_election_cycle VARCHAR(255),
  previous_receipts VARCHAR(255),
  current_receipts VARCHAR(255),
  total_receipts_this_election_cycle VARCHAR(255),
  total_funds_available VARCHAR(255),
  previous_disbursements VARCHAR(255),
  current_disbursements VARCHAR(255),
  total_disbursements VARCHAR(255),
  ending_balance VARCHAR(255),
  schedule_id VARCHAR(255),
  report_uid VARCHAR(255),
  data_source_url VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(255) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
