CREATE TABLE VA_RAW_SCHEDULEG
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  run_id int,
  schedule_G_id varchar(255),
  report_id varchar(255),
  schedule_A_count varchar(255),
  schedule_A_total varchar(255),
  schedule_B_count varchar(255),
  schedule_B_total varchar(255),
  un_itemized_count varchar(255),
  un_itemized_total varchar(255),
  un_itemized_in_kind_count varchar(255),
  un_itemized_in_kind_total varchar(255),
  all_contributions_count varchar(255),
  all_contributions_total varchar(255),
  schedule_C_total varchar(255),
  schedule_B_total_again varchar(255),
  un_itemized_in_kind_total_again varchar(255),
  schedule_D_total varchar(255),
  total_in_kind_and_expenditures varchar(255),
  beginning_loan_balance varchar(255),
  loans_received_total varchar(255),
  loans_received_and_existing_total varchar(255),
  loans_paid_total varchar(255),
  new_loan_balance varchar(255),
  schedule_id varchar(255),
  report_uid varchar(255),
  data_source_url VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(255) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
