CREATE TABLE VA_RAW_SCHEDULEE
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  run_id int,
  report_id VARCHAR(255),
  transaction_date DATE,
  amount VARCHAR(255),
  schedule_E_id VARCHAR(255),
  lender_committee_contact_id VARCHAR(255),
  lender_first_name VARCHAR(255),
  lender_middle_name VARCHAR(255),
  lender_last_or_company_name VARCHAR(255),
  lender_prefix VARCHAR(255),
  lender_suffix VARCHAR(255),
  lender_address_line1 VARCHAR(255),
  lender_address_line2 VARCHAR(255),
  lender_city VARCHAR(255),
  lender_state_code VARCHAR(255),
  lender_zip_code VARCHAR(255),
  lender_state varchar(255),
  lender_is_individual VARCHAR(255),
  co_borrower_committee_contact_id VARCHAR(255),
  co_borrower_first_name VARCHAR(255),
  co_borrower_middle_name VARCHAR(255),
  co_borrower_last_or_company_name VARCHAR(255),
  co_borrower_prefix VARCHAR(255),
  co_borrower_suffix VARCHAR(255),
  co_borrower_address_line1 VARCHAR(255),
  co_borrower_address_line2 VARCHAR(255),
  co_borrower_city VARCHAR(255),
  co_borrower_state varchar(255),
  co_borrower_state_code VARCHAR(255),
  co_borrower_zip_code VARCHAR(255),
  co_borrower_is_individual VARCHAR(255),
  transaction_type VARCHAR(255),
  loan_balance VARCHAR(255),
  schedule_id VARCHAR(255),
  report_uid VARCHAR(255),
  data_source_url VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(255) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
