CREATE TABLE la_general_info (
  `id` 					BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `is_district` 		TINYINT(1),
  `district_id`			BIGINT(20),
  `number` 				VARCHAR(50),
  `name` 				VARCHAR(255),
  `type`         VARCHAR(255),
 `low_grade` 			VARCHAR(255),
  `high_grade` 			VARCHAR(255),
  `charter` 		VARCHAR(255),
  `magnet` 	VARCHAR(255),
  `title_1_school` 		VARCHAR(255),
  `title_1_school_wide` 		VARCHAR(255),
  `nces_id` 			VARCHAR(50),
  `phone` 				VARCHAR(255),
  `address` 			VARCHAR(255),
  `city` 				VARCHAR(255),
  `state` 				VARCHAR(255),
  `zip` 				VARCHAR(255),
  `zip_4` 				VARCHAR(255),
  `data_source_url` 	VARCHAR(255),
  `created_by`     		VARCHAR(255)      DEFAULT 'Muhammad Musa',
  `created_at`      	DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id`          	BIGINT(20),
  `touched_run_id`  	BIGINT,
  `deleted`         	BOOLEAN           DEFAULT 0,
  `md5_hash`        	VARCHAR(255),
  UNIQUE KEY        	`md5` (`md5_hash`),
  INDEX             	`run_id` (`run_id`),
  INDEX             	`touched_run_id` (`touched_run_id`),
  INDEX             	`deleted` (`deleted`)
)   DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci
    COMMENT = 'Created by Muhammad Musa, Task #667';
