CREATE TABLE `remax_home_listings`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `property_id`       VARCHAR(255),
  `ouid`              VARCHAR(255),
  `listing_id`        VARCHAR(255),
  `state`             VARCHAR(255),
  `city`              VARCHAR(255),
  `zip`               VARCHAR(255),
  `address`           VARCHAR(255),
  `total_baths`       INT,
  `full_baths`        INT,
  `bedrooms`          INT,
  `square_feet`       BIGINT,
  `acres`             DECIMAL(20,2),
  `year_built`        VARCHAR(255),
  `selling_price`     DECIMAL(20,2),
  `status`            VARCHAR(255),
  `cooling`           BOOLEAN,
  `heating`           BOOLEAN,
  `hoa`               DECIMAL(20,2),
  `parking`           INT,
  `sq_ft_price`       INT,
  `property_type`     VARCHAR(255),
  `property_sub_type` VARCHAR(255),
  `listed_at_date`    DATE,
  `additional_info`   TEXT,
  `modify_timestamp`  BIGINT,
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Ray Piao',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id`            BIGINT(20),
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
