CREATE TABLE `NC_RAW_NCVOTER`(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `county_id` BIGINT UNSIGNED NOT NULL,
  `county_desc` VARCHAR(255) NULL,
  `voter_reg_num` VARCHAR(255) NULL,
  `ncid` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `middle_name` VARCHAR(255) NULL,
  `name_suffix_lbl` VARCHAR(255) NULL,
  `status_cd` VARCHAR(25) NULL,
  `voter_status_desc` VARCHAR(255) NULL,
  `reason_cd` VARCHAR(25) NULL,
  `voter_status_reason_desc` VARCHAR(255) NULL,
  `res_street_address` VARCHAR(255) NULL,
  `res_city_desc` VARCHAR(255) NULL,
  `state_cd` VARCHAR(25) NULL,
  `zip_code` VARCHAR(10) NULL,
  `mail_addr1` VARCHAR(255) NULL,
  `mail_addr2` VARCHAR(255) NULL,
  `mail_addr3` VARCHAR(255) NULL,
  `mail_addr4` VARCHAR(255) NULL,
  `mail_city` VARCHAR(255) NULL,
  `mail_state` VARCHAR(25) NULL,
  `mail_zipcode` VARCHAR(10) NULL,
  `full_phone_number` VARCHAR(255) NULL,
  `confidential_ind` VARCHAR(25) NULL,
  `registr_dt` date DEFAULT NULL,
  `race_code` VARCHAR(25) NULL,
  `ethnic_code` VARCHAR(25) NULL,
  `party_cd` VARCHAR(25) NULL,
  `gender_code` VARCHAR(25) NULL,
  `birth_year` VARCHAR(25) NULL,
  `age_at_year_end` VARCHAR(25) NULL,
  `birth_state` VARCHAR(25) NULL,
  `drivers_lic` VARCHAR(25) NULL,
  `precinct_abbrv` VARCHAR(25) NULL,
  `precinct_desc` VARCHAR(255) NULL,
  `municipality_abbrv` VARCHAR(25) NULL,
  `municipality_desc` VARCHAR(255) NULL,
  `ward_abbrv` VARCHAR(25) NULL,
  `ward_desc` VARCHAR(255) NULL,
  `super_court_abbrv` VARCHAR(25) NULL,
  `cong_dist_abbrv` VARCHAR(25) NULL,
  `judic_dist_abbrv` VARCHAR(25) NULL,
  `nc_senate_abbrv` VARCHAR(25) NULL,
  `nc_house_abbrv` VARCHAR(25) NULL,
  `county_commiss_abbrv` VARCHAR(25) NULL,
  `county_commiss_desc` VARCHAR(255) NULL,
  `township_abbrv` VARCHAR(25) NULL,
  `township_desc` VARCHAR(255) NULL,
  `school_dist_abbrv` VARCHAR(25) NULL,
  `school_dist_desc` VARCHAR(255) NULL,
  `fire_dist_abbrv` VARCHAR(25) NULL,
  `fire_dist_desc` VARCHAR(255) NULL,
  `water_dist_abbrv` VARCHAR(255) NULL,
  `water_dist_desc` VARCHAR(255) NULL,
  `sewer_dist_abbrv` VARCHAR(255) NULL,
  `sewer_dist_desc` VARCHAR(255) NULL,
  `sanit_dist_abbrv` VARCHAR(255) NULL,
  `sanit_dist_desc` VARCHAR(255) NULL,
  `rescue_dist_abbrv` VARCHAR(255) NULL,
  `rescue_dist_desc` VARCHAR(255) NULL,
  `munic_dist_abbrv` VARCHAR(255) NULL,
  `munic_dist_desc` VARCHAR(255) NULL,
  `dist_1_abbrv` VARCHAR(255) NULL,
  `dist_1_desc` VARCHAR(255) NULL,
  `vtd_abbrv` VARCHAR(255) NULL,
  `vtd_desc` VARCHAR(255) NULL,
  `file_name` VARCHAR(255) NULL,
  `row_num` VARCHAR(255) NULL,
  `touched_run_id` BIGINT NULL,
  `data_source_url` VARCHAR(255) DEFAULT "https://drive.google.com/drive/folders/1OyvyXxec2nPnUiPF_XMQvWCPJ0Ci8qKe",
  `created_by` VARCHAR(255) DEFAULT "Muhammad Qasim",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `md5_hash` VARCHAR(100) GENERATED ALWAYS AS (md5(CONCAT_WS('', county_id, county_desc, voter_reg_num, ncid, last_name, first_name, middle_name, name_suffix_lbl, status_cd, voter_status_desc, reason_cd, voter_status_reason_desc, res_street_address, res_city_desc, state_cd, zip_code, mail_addr1, mail_addr2, mail_addr3, mail_addr4, mail_city, mail_state, mail_zipcode, full_phone_number, confidential_ind, registr_dt, race_code, ethnic_code, party_cd, gender_code, birth_year, age_at_year_end, birth_state, drivers_lic, precinct_abbrv, precinct_desc, munic_dist_abbrv, munic_dist_desc, ward_abbrv, ward_desc, super_court_abbrv, cong_dist_abbrv, judic_dist_abbrv, nc_house_abbrv, nc_senate_abbrv, county_commiss_abbrv, county_commiss_desc, township_abbrv, township_desc, school_dist_abbrv, school_dist_desc, fire_dist_abbrv, fire_dist_desc, water_dist_abbrv, water_dist_desc, sewer_dist_abbrv, sewer_dist_desc, sanit_dist_abbrv, sanit_dist_desc, rescue_dist_abbrv, rescue_dist_desc, dist_1_abbrv, dist_1_desc, vtd_abbrv, vtd_desc))) STORED,
  UNIQUE KEY `md5` (`md5_hash`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
