CREATE TABLE `NC_RAW_Expenditures`(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  `street_line_1` VARCHAR(255) NULL,
  `street_line_2` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(2) NULL,
  `zip_code` VARCHAR(10) NULL,
  `profession_job_title` VARCHAR(255) NULL,
  `employer_name_specific_field` VARCHAR(255) NULL,
  `transaction_type` VARCHAR(255) NULL,
  `committee_name` VARCHAR(255) NULL,
  `committee_sboe_id` VARCHAR(255) NULL,
  `committee_street_1` VARCHAR(255) NULL,
  `committee_street_2` VARCHAR(255) NULL,
  `committee_city` VARCHAR(255) NULL,
  `committee_state` VARCHAR(2) NULL,
  `committee_zip_code` VARCHAR(10) NULL,
  `report_name` VARCHAR(255) NULL,
  `date_occurred` date DEFAULT NULL,
  `account_code` VARCHAR(255) NULL,
  `amount` DECIMAL(10,2) NULL,
  `form_of_payment` VARCHAR(255) NULL,
  `purpose` VARCHAR(255) NULL,
  `candidate_referendum_name` VARCHAR(255) NULL,
  `declaration` VARCHAR(255) NULL,
  `touched_run_id` BIGINT NULL,
  `data_source_url` VARCHAR(255) DEFAULT "https://drive.google.com/drive/folders/1OyvyXxec2nPnUiPF_XMQvWCPJ0Ci8qKe",
  `created_by` VARCHAR(255) DEFAULT "Muhammad Qasim",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `md5_hash` VARCHAR(100) GENERATED ALWAYS AS (md5(CONCAT_WS('', name, street_line_1, street_line_2, city, state, zip_code, profession_job_title, employer_name_specific_field, transaction_type, committee_name, committee_sboe_id, committee_street_1, committee_street_2, committee_city, committee_state, committee_zip_code, report_name, date_occurred, account_code, amount, form_of_payment, purpose, candidate_referendum_name, declaration ))) STORED,
  UNIQUE KEY `md5` (`md5_hash`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
