CREATE TABLE `NC_RAW_Candidates2018_extras`(
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `election_dt` date DEFAULT NULL,
  `county_name` VARCHAR(255) NULL,
  `contest_name` VARCHAR(255) NULL,
  `name_on_ballot` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `middle_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `name_suffix_lbl` VARCHAR(255) NULL,
  `nick_name` VARCHAR(255) NULL,
  `candidacy_dt` date DEFAULT NULL,
  `party_contest` VARCHAR(255) NULL,
  `party_candidate` VARCHAR(255) NULL,
  `is_unexpired` BOOLEAN DEFAULT 0,
  `has_primary` BOOLEAN DEFAULT 0,
  `is_partisan` BOOLEAN DEFAULT 0,
  `vote_for` INT NULL,
  `term` VARCHAR(255) NULL,
  `addr1` VARCHAR(255) NULL,
  `addr2` VARCHAR(255) NULL,
  `addr3` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(2) NULL,
  `zip_code` VARCHAR(10) NULL,
  `phone` VARCHAR(80) NULL,
  `email` VARCHAR(255) NULL,
  `touched_run_id` BIGINT NULL,
  `data_source_url` VARCHAR(255) DEFAULT "https://drive.google.com/drive/folders/1OyvyXxec2nPnUiPF_XMQvWCPJ0Ci8qKe",
  `created_by` VARCHAR(255) DEFAULT "Muhammad Qasim",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `md5_hash` VARCHAR(100) GENERATED ALWAYS AS (md5(CONCAT_WS('', election_dt, county_name, contest_name, name_on_ballot, first_name, middle_name, last_name, name_suffix_lbl, nick_name, city, state, zip_code, phone, candidacy_dt, party_contest, party_candidate, is_unexpired, is_partisan, has_primary, vote_for, term, addr1, addr2, addr3, email ))) STORED,
  UNIQUE KEY `md5` (`md5_hash`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
