CREATE TABLE `washington_state_campaign_contributions_csv`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `contribution_id`              BIGINT(20),
  `run_id`          BIGINT(20),

  `report_number`     BIGINT,
  `origin`            VARCHAR(50),
  `committee_id`     BIGINT,
  `filer_id`           VARCHAR(50),
  `type`           VARCHAR(50),
  `filer_name`           VARCHAR(150),
  `office`           VARCHAR(50),
  `legislative_district`           VARCHAR(50),
  `position`           VARCHAR(150),
  `party`           VARCHAR(50),
  `ballot_number`           VARCHAR(50),
  `for_or_against`           VARCHAR(50),
  `jurisdiction`           VARCHAR(100),
  `jurisdiction_county`           VARCHAR(50),
  `jurisdiction_type`           VARCHAR(50),
  `election_year`           INT,
  `amount`                 BIGINT,
  `cash_or_in_kind`           VARCHAR(50),
  `receipt_date`              DATE,
  `description`           VARCHAR(150),
  `memo`                 VARCHAR(50),
  `primary_general`      VARCHAR(50),
  `code`                   VARCHAR(50),
  `contributor_category`      VARCHAR(50),
  `contributor_name`     VARCHAR(100),
  `contributor_address`     VARCHAR(150),
  `contributor_city`      VARCHAR(50),
  `contributor_state`      VARCHAR(10),
  `contributor_zip`            INT,
  `contributor_occupation`     VARCHAR(100),
  `contributor_employer_name`     VARCHAR(100),
  `contributor_employer_city`      VARCHAR(50),
  `contributor_employer_state`   VARCHAR(10),
  `url`                     VARCHAR(150),
  `contributor_location`         VARCHAR(150),


  `data_source_url` VARCHAR(255)       DEFAULT 'https://data.wa.gov/Politics/Contributions-to-Candidates-and-Political-Committe/kv7h-kjye',
  `created_by`      VARCHAR(255)       DEFAULT 'Maxim G',
  `created_at`      DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  `touched_run_id`  BIGINT,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
