CREATE TABLE `ny_nysboe_reports` 
(
  id bigint(20) NOT NULL AUTO_INCREMENT,
  `filer_id` VARCHAR(255),
  `filer_previous_id` VARCHAR(255),
  `cand_comm_name` VARCHAR(255),
  `election_year` VARCHAR(255),
  `election_type` VARCHAR(255),
  `county_desc` VARCHAR(255),
  `filing_abbrev` VARCHAR(255),
  `filing_desc` VARCHAR(255),
  `r_amend` VARCHAR(255),
  `filing_cat_desc` VARCHAR(255),
  `filing_sched_abbrev` VARCHAR(255),
  `filing_sched_desc` VARCHAR(255),
  `loan_lib_number` VARCHAR(255),
  `trans_number` VARCHAR(255),
  `trans_mapping` VARCHAR(255),
  `sched_date` VARCHAR(255),
  `org_date` VARCHAR(255),
  `cntrbr_type_desc` VARCHAR(255),
  `cntrbn_type_desc` VARCHAR(255),
  `transfer_type_desc` VARCHAR(255),
  `receipt_type_desc` VARCHAR(255),
  `receipt_code_desc` VARCHAR(255),
  `purpose_code_desc` VARCHAR(255),
  `r_subcontractor` VARCHAR(255),
  `flng_ent_name` VARCHAR(255),
  `flng_ent_first_name` VARCHAR(255),
  `flng_ent_middle_name` VARCHAR(255),
  `flng_ent_last_name` VARCHAR(255),
  `flng_ent_add1` VARCHAR(255),
  `flng_ent_city` VARCHAR(255),
  `flng_ent_state` VARCHAR(255),
  `flng_ent_zip` VARCHAR(255),
  `flng_ent_country` VARCHAR(255),
  `payment_type_desc` VARCHAR(255),
  `pay_number` VARCHAR(255),
  `owed_amt` VARCHAR(255),
  `org_amt` VARCHAR(255),
  `loan_other_desc` VARCHAR(255),
  `trans_explntn` VARCHAR(255),
  `r_itemized` VARCHAR(255),
  `r_liability` VARCHAR(255),
  `election_year_r` VARCHAR(255),
  `office_desc` VARCHAR(255),
  `district` VARCHAR(255),
  `dist_off_cand_bal_prop` VARCHAR(255),
  data_source_url VARCHAR(255),
  created_by varchar(255) DEFAULT 'Hassan',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  run_id bigint(20) DEFAULT NULL,
  touched_run_id bigint(20) DEFAULT NULL,
  deleted tinyint(1) DEFAULT '0',
  md5_hash varchar(150) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY `md5_hash` (md5_hash),
  KEY `run_id` (run_id),
  KEY `touched_run_id` (touched_run_id),
  KEY `deleted` (deleted)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
