CREATE TABLE `ny_nyccfb_contributions` 
(
  id bigint(20) NOT NULL AUTO_INCREMENT,
  election VARCHAR(255),
  officecd VARCHAR(255),
  recipid VARCHAR(255),
  canclass VARCHAR(255),
  recipname VARCHAR(255),
  committee VARCHAR(255),
  filing VARCHAR(255),
  schedule VARCHAR(255),
  pageno VARCHAR(255),
  sequenceno VARCHAR(255),
  refno VARCHAR(255),
  date VARCHAR(255),
  refunddate VARCHAR(255),
  name VARCHAR(255),
  c_code VARCHAR(255),
  strno VARCHAR(255),
  strname VARCHAR(255),
  apartment VARCHAR(255),
  boroughcd VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  zip VARCHAR(255),
  occupation VARCHAR(255),
  empname VARCHAR(255),
  empstrno VARCHAR(255),
  empstrname VARCHAR(255),
  empcity VARCHAR(255),
  empstate VARCHAR(255),
  amnt VARCHAR(255),
  matchamnt VARCHAR(255),
  prevamnt VARCHAR(255),
  pay_method VARCHAR(255),
  intermno VARCHAR(255),
  intermname VARCHAR(255),
  intstrno VARCHAR(255),
  intstrnm VARCHAR(255),
  intaptno VARCHAR(255),
  intcity VARCHAR(255),
  intst VARCHAR(255),
  intzip VARCHAR(255),
  intempname VARCHAR(255),
  intempstno VARCHAR(255),
  intempstnm VARCHAR(255),
  intempcity VARCHAR(255),
  intempst VARCHAR(255),
  intoccupa VARCHAR(255),
  purposecd VARCHAR(255),
  exemptcd VARCHAR(255),
  adjtypecd VARCHAR(255),
  rr_ind VARCHAR(255),
  seg_ind VARCHAR(255),
  int_c_code VARCHAR(255),
  data_source_url VARCHAR(255),
  created_by varchar(255) DEFAULT 'Hassan',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  run_id bigint(20) DEFAULT NULL,
  touched_run_id bigint(20) DEFAULT NULL,
  deleted tinyint(1) DEFAULT '0',
  md5_hash varchar(150) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY `md5_hash` (md5_hash),
  KEY `run_id` (run_id),
  KEY `touched_run_id` (touched_run_id),
  KEY `deleted` (deleted)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
