CREATE TABLE `ny_nyccfb_intermediaries` 
(
  id bigint(20) NOT NULL AUTO_INCREMENT,
  election VARCHAR(255),
  officecd VARCHAR(255),
  candid VARCHAR(255),
  canclass VARCHAR(255),
  candlast VARCHAR(255),
  candfirst VARCHAR(255),
  candmi VARCHAR(255),
  committee VARCHAR(255),
  name VARCHAR(255),
  c_code VARCHAR(255),
  strno VARCHAR(255),
  strname VARCHAR(255),
  apartment VARCHAR(255),
  boroughcd VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  zip VARCHAR(255),
  occupation VARCHAR(255),
  empname VARCHAR(255),
  empstrno VARCHAR(255),
  empstrname VARCHAR(255),
  empcity VARCHAR(255),
  empstate VARCHAR(255),
  amnt VARCHAR(255),
  data_source_url VARCHAR(255),
  created_by varchar(255) DEFAULT 'Hassan',
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  run_id bigint(20) DEFAULT NULL,
  touched_run_id bigint(20) DEFAULT NULL,
  deleted tinyint(1) DEFAULT '0',
  md5_hash varchar(150) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY `md5_hash` (md5_hash),
  KEY `run_id` (run_id),
  KEY `touched_run_id` (touched_run_id),
  KEY `deleted` (deleted)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
