CREATE TABLE `chicago_public_schools_suppliers_payments` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`fiscal_year` int(4),
`payment_amount` varchar(255) DEFAULT NULL,
`supplier_payment_id` varchar(255) DEFAULT NULL,
`oracle_vendor_id` varchar(255) DEFAULT NULL,
`supplier_id` varchar(255) DEFAULT NULL,
`name` varchar(255) DEFAULT NULL,
`full_address` varchar(255) DEFAULT NULL,
`city` varchar(255) DEFAULT NULL,
`state` varchar(255) DEFAULT NULL,
`zip_code` varchar(255) DEFAULT NULL,
`created_date` datetime DEFAULT NULL,
`created_by` datetime DEFAULT NULL,
`updated_date` datetime DEFAULT NULL,
`updated_by` datetime DEFAULT NULL,
`created_at` datetime DEFAULT NULL,
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`last_scrape_date` date DEFAULT NULL,
`next_scrape_date` date DEFAULT NULL,
`expected_scrape_frequency` varchar(255) DEFAULT NULL,
`dataset_name_prefix` varchar(255) DEFAULT NULL,
`scrape_status` varchar(255) DEFAULT NULL,
`pl_gather_task_id` varchar(255) DEFAULT NULL,
`run_id` int(11),
PRIMARY KEY (`id`),
UNIQUE KEY `chicago_public_schools_suppliers_payments__u` (`fiscal_year`, `supplier_name`, `payment_amount`)
);