# frozen_string_literal: true

require 'active_record'
require 'active_support/all'
require 'active_support/message_encryptor'
require 'active_support/encrypted_file'
require 'awesome_print'
require 'aws-sdk-s3'
require 'colorize'
require 'csv'
require 'date'
require 'digest'
require 'docsplit'
require 'faraday'
require 'ferrum'
require 'fileutils'
require 'json'
require 'nokogiri'
require 'minitar'
require 'mechanize'
require 'mysql2'
require 'open-uri'
require 'pdf-reader'
require 'slack-ruby-client'
require 'socksify'
require 'socksify/http'
require 'soda/client'
require 'telegram/bot'
require 'rtesseract'
require 'pdftoimage'
require 'two_captcha'
require 'time'
require 'zlib'
require 'wicked_pdf'
require 'pry'
require 'yaml'
require 'irb'

require_relative 'lib/hamster'
require_relative 'lib/harvester'
require_relative 'lib/keeper'
require_relative 'lib/parser'
require_relative 'lib/scraper'
require_relative 'lib/storage'
require_relative 'lib/fake_agent'
require_relative 'lib/proxy_filter'
require_relative 'lib/camouflage'
require_relative 'lib/scrapers'
require_relative 'lib/granary'
require_relative 'lib/captcha_solver'

require_relative 'lib/extras/faraday/net_http_connection'
require_relative 'lib/specials/scrape/net_http/persistent/net_http_persistent'
require_relative 'lib/specials/scrape/mechanize_http/agent/mechanize_http_agent'
require_relative 'lib/specials/activerecord/mysql2_adapter_patch'
require_relative 'lib/specials/pacer/pacer_md5'
require_relative 'lib/specials/md5_hash'
require_relative 'lib/specials/aws_s3'
require_relative 'lib/specials/run_id'
require_relative 'lib/specials/teaser_corrector'
require_relative 'lib/specials/number_in_words/numbers_in_words'

require_relative 'lib/robohamster/rh_scraper'
require_relative 'lib/robohamster/rh_keeper'
require_relative 'lib/robohamster/rh_parser'
require_relative 'lib/robohamster/rh_page_url'
require_relative 'lib/robohamster/rh_config_compiler'
require_relative 'lib/specials/zip_generator'

require_relative 'lib/code_map'
require_relative 'lib/captcha_adapter/captcha_adapter'    # extends class Hamster with several methods
Hamster.start_trace { Hamster.wakeup }
