#!/usr/bin/env bash

help="
Usage: hamster COMMAND [ARGUMENT]…

COMMANDS LIST:
    build [PROJECT_NUMBER]          builds the main Hamster docker image or
                                    the pointed project's image
    grab PROJECT_NUMBER [ARGUMENT]… runs the pointed project in docker container with
                                    passed arguments
    dig PROJECT_NUMBER              makes initial directory and file structure for
                                    the pointed project
    do TASK_NAME [ARGUMENT]…        runs a task from the unexpected_tasks directory with
                                    passed arguments
    docker                          runs the Hamster docker container and puts you into

    telegram                        runs the Hamster's Telegram bot to hear messeages

    help                            prints this help
"

if [ -z "$1" ] ; then
  echo -ne "\033[31mError: It necessary to put the command and needed parameters after that!\033[0m\n" >&2
  echo "$help"

  exit 1
fi

action=$1

shift

if [ $action == 'help' ] ; then
  echo "$help"
else
  bash $(cat ${HOME}/.config/hamster/local.path)bin/${action} $@
fi

exit 0

