CREATE TABLE `ca_calbar_bar`
(
  `id`                          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                      BIGINT(20),
  `bar_number`                  VARCHAR(255),
  `name`                        VARCHAR(255),
  `first_name`                  VARCHAR(255),
  `last_name`                   VARCHAR(255),
  `middle_name`                 VARCHAR(255),
  `date_admitted`               DATE,
  `registration_status`         VARCHAR(255),
  `sections`                    TEXT,
  `type`                        VARCHAR(255),
  `phone`                       VARCHAR(255),
  `email`                       VARCHAR(255),
  `fax`                         VARCHAR(255),
  `address_original`            VARCHAR(255),
  `law_firm_name`               VARCHAR(255),
  `law_firm_address`            VARCHAR(255),
  `law_firm_zip`                VARCHAR(255),
  `law_firm_city`               VARCHAR(255),
  `law_firm_state`              VARCHAR(255),
  `law_firm_county`             VARCHAR(255),
  `name_prefix`                 VARCHAR(255),
  `law_school`                  VARCHAR(255),
  `proffesional_affilitaion`    TEXT,
  `bio`                         LONGTEXT,
  `website`                     VARCHAR(255),
  `linkedin`                    VARCHAR(255),
  `facebook`                    VARCHAR(255),
  `twitter`                     VARCHAR(255),
  `law_firm_website`            VARCHAR(255),
  `other_jurisdictions`         TEXT,
  `judicial_district`           VARCHAR(255),
  `disciplinary_actions`        TEXT,
  `private_practice`            VARCHAR(255),
  `insurance`                   VARCHAR(255),
  `courts_of_admittance`        VARCHAR(255),
  `scrape_frequency`            VARCHAR(255)       DEFAULT 'weekly',
  `data_source_url`             TEXT,
  `created_by`                  VARCHAR(255)       DEFAULT 'Igor Sas',
  `created_at`                  DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`              BIGINT,
  `deleted`                     BOOLEAN            DEFAULT 0,
  `md5_hash`                    VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
