CREATE TABLE `milb_people`
(
  `id`                 BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`             BIGINT(20),
  `mlb_id`             BIGINT,
  `current_team_id`    BIGINT,
  `full_name`          VARCHAR(255),
  `alias`              VARCHAR(255),
  `first_name`         VARCHAR(255),
  `middle_name`        VARCHAR(255),
  `last_name`          VARCHAR(255),
  `full_position`      VARCHAR(255),
  `number`             VARCHAR(255),
  `status`             VARCHAR(255),
  `mlb_40_man`         BOOLEAN,
  `b_t`                VARCHAR(255),
  `height`             VARCHAR(255),
  `weight`             VARCHAR(255),
  `birth_date`         DATE,
  `country`            VARCHAR(255),
  `city`               VARCHAR(255),
  `state`              VARCHAR(255),
  `mlb_debut`          DATE,
  `college_name`       VARCHAR(255),
  `college_city`       VARCHAR(255),
  `college_state`      VARCHAR(255),
  `high_school_name`   VARCHAR(255),
  `high_school_city`   VARCHAR(255),
  `high_school_state`  VARCHAR(255),
  `instagram`          VARCHAR(255),
  `twitter`            VARCHAR(255),
  `draft_year`         YEAR,
  `draft_team`         VARCHAR(255),
  `draft_round`        VARCHAR(255),
  `draft_overall_pick` VARCHAR(255),
  `bio_info`           TEXT,
  `org_img_url`        TEXT,
  `aws_img_url`        TEXT,
  `data_source_url`    TEXT,
  `created_by`         VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`         DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`     BIGINT,
  `deleted`            BOOLEAN           DEFAULT 0,
  `md5_hash`           VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
