CREATE TABLE `milb_career_stats`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `roster_hash`     VARCHAR(255),
  `league`          VARCHAR(255),
  `level`           VARCHAR(255),
  `group`           VARCHAR(255),
  `wins`            INT,
  `losses`          INT,
  `era`             FLOAT,
  `games`           INT,
  `games_started`   INT,
  `complete_games`  INT,
  `shutouts`        INT,
  `holds`           INT,
  `saves`           INT,
  `save_opp`        INT,
  `innings_pitched` FLOAT,
  `hits`            INT,
  `runs`            INT,
  `earned_runs`     INT,
  `home_runs`       INT,
  `no_of_pitches`   INT,
  `hit_batsmen`     INT,
  `base_on_balls`   INT,
  `intent_walks`    INT,
  `strikeouts`      INT,
  `batting_avg`     FLOAT,
  `whip`            FLOAT,
  `go_ao`           FLOAT,
  `at_bats`         INT,
  `total_bases`     INT,
  `doubles`         INT,
  `triples`         INT,
  `rbi`             INT,
  `stolen_bases`    INT,
  `caught_stealing` INT,
  `obp`             FLOAT,
  `slg`             FLOAT,
  `ops`             FLOAT,
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
