version: '3'

services:

  project_0397:
    image: hamster-0397
    container_name: project_0397
    environment:
      - HAMSTER_CONFIG_LOCATION
      - HAMSTER_PROJECT_LOCATION
      - HAMSTER_STORAGE_LOCATION
    volumes:
      - hamster_config:/home/hamster/ini/Hamster
      - hamster_storage:/home/hamster/HarvestStorehouse
      - hamster_project:/home/hamster/Hamster
    command: /bin/sh -cl "ruby hamster.rb --grab=0397 --update --weather"

volumes:
  hamster_project:
    driver_opts:
      type: none
      o: bind
      device: $HAMSTER_PROJECT_LOCATION
  hamster_storage:
    driver_opts:
      type: none
      o: bind
      device: $HAMSTER_STORAGE_LOCATION
  hamster_config:
    driver_opts:
      type: none
      o: bind
      device: $HAMSTER_CONFIG_LOCATION

