create table dallas_police_arrests_updates
(
  id                            BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id                        BIGINT,
  incidentnum                   VARCHAR(255),
  arrestyr                      INT,
  arrestnumber                  VARCHAR(255),
  ararrestdate                  VARCHAR(255),
  ararresttime                  VARCHAR(255),
  arbkdate                      VARCHAR(255),
  arladdress                    VARCHAR(255),
  arlapt                        VARCHAR(255),
  arlzip                        INT,
  arlcity                       VARCHAR(255),
  arstate                       VARCHAR(255),
  arlcounty                     VARCHAR(255),
  arlra                         INT,
  arlbeat                       INT,
  arldistrict                   VARCHAR(255),
  arlsector                     INT,
  aradow                        VARCHAR(255),
  arpremises                    VARCHAR(255),
  cfs_number                    VARCHAR(255),
  arofcr1                       VARCHAR(255),
  arofcr2                       VARCHAR(255),
  transport1                    VARCHAR(255),
  transport2                    VARCHAR(255),
  transport3                    VARCHAR(255),
  search1                       VARCHAR(255),
  araction                      VARCHAR(255),
  arweapon                      VARCHAR(255),
  arosr                         VARCHAR(255),
  arresisted                    VARCHAR(255),
  arcurrloc                     VARCHAR(255),
  arcond                        VARCHAR(255),
  armedflag                     VARCHAR(255),
  armedloc                      VARCHAR(255),
  aropcomm                      VARCHAR(255),
  arresteename                  VARCHAR(255),
  arresteename_cleaned          VARCHAR(255),
  arresteename_cleaned_manually BOOLEAN            DEFAULT 0,
  nickname                      VARCHAR(255),
  aliasname                     VARCHAR(255),
  birthplace                    VARCHAR(255),
  age                           INT,
  ageatarresttime               INT,
  haddress                      VARCHAR(255),
  hapt                          VARCHAR(255),
  hzip                          INT,
  hcity                         VARCHAR(255),
  hstate                        VARCHAR(255),
  hra                           INT,
  hbeat                         INT,
  height                        VARCHAR(255),
  weight                        INT,
  hair                          VARCHAR(255),
  eyes                          VARCHAR(255),
  race                          VARCHAR(255),
  ethnic                        VARCHAR(255),
  sex                           VARCHAR(255),
  tatoo                         VARCHAR(255),
  tatoocomment                  VARCHAR(255),
  occupation                    VARCHAR(255),
  jobschstatus                  VARCHAR(255),
  employer                      VARCHAR(255),
  drug                          VARCHAR(255),
  drugrelated                   VARCHAR(255),
  drugtype                      VARCHAR(255),
  clothingworn                  TEXT,
  expunged                      TEXT,
  upzdate                       VARCHAR(255),
  data_source_url               VARCHAR(255)       DEFAULT 'https://www.dallasopendata.com/Public-Safety/Police-Arrests/sdr7-6v3j',
  created_by                    VARCHAR(255)       DEFAULT 'Art Jarocki',
  created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id                BIGINT,
  deleted                       BOOLEAN            DEFAULT 0,
  md5_hash                      VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX run_id (run_id),
  INDEX touched_run_id (touched_run_id),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;
