CREATE TABLE `il_higher_ed_salaries`
(
  `id`                        BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                    BIGINT(20),
  `year`                      int,
  `institution`               varchar(255) Default NULL,
  `name`                      varchar(255) Default NULL,
  `position`                  varchar(255) Default NULL,
  `title`                     varchar(255) Default NULL,
  `salary`                    DECIMAL(12, 2),
  `compensation`              DECIMAL(12, 2),
  `vacation_days`             DECIMAL(12, 2),
  `sick_days`                 DECIMAL(12, 2),
  `bonuses`                   DECIMAL(12, 2),
  `annuities`                 DECIMAL(12, 2),
  `retirement_enhancements`   DECIMAL(12, 2),
  `tuition_waivers`           DECIMAL(12, 2),
  `benefits`                  DECIMAL(12, 2),
  `employment_status`         VARCHAR(256) DEFAULT NULL,
  `employment_classification` VARCHAR(256) DEFAULT NULL,
  `data_source_url`           VARCHAR(256) DEFAULT NULL,
  `created_by`                VARCHAR(255)      DEFAULT 'Afia',
  `created_at`                DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`            BIGINT,
  `deleted`                   BOOLEAN           DEFAULT 0,
  `md5_hash`                  VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'Afia';
