CREATE TABLE `ri_court_rijudiciary`
(
  `id`              BIGINT(20) AUTO_INCREMENT,
  `run_id`          BIGINT(20),
  `bar_number`      varchar(255) default "",
  `name`            varchar(255) default "",
  `date_admited`    date,
  `registration_status` varchar(255) default "",
  `sections`       text ,
  `raw_name_or_address`   varchar(255) default "",
  `phone`          varchar(255) default "",
  `email`          varchar(255) default "",
  `fax`            varchar(255) default "",
  `law_firm_name`  varchar(255) default "",
  `raw_address2`  varchar(255) default "",
  `law_firm_city_state_zip` varchar(255) default "",
  `law_firm_zip`      varchar(255) default "",
  `law_firm_city`     varchar(255) default "",
  `law_firm_state`    varchar(255) default "",
  `law_firm_county`   varchar(255) default "",
  `name_prefix`       varchar(255) default "",
  `university`        varchar(255) default "",
  `professional_affiliation`  varchar(255) default "",
  `bio`         varchar(255) default "",
  `website`     varchar(255) default "",
  `linkedin`    varchar(255) default "",
  `facebook`    varchar(255) default "",
  `twitter`     varchar(255) default "",
  `law_firm_website`  varchar(255) default "",
  `other_jurisdictions`  varchar(255) default "",
  `judicial_district`  varchar(255) default "",
  `disciplinary_actions`   varchar(255) default "",
  `private_practice`  varchar(255) default "",
  `insurance`  varchar(255) default "",
  `courts_of_admittance`  varchar(255) default "",
  `scrape_frequency`  varchar(255)  default 'weekly',
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Abdur Rehman',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  KEY `id` (`id`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
  