CREATE TABLE `mn_public_employee_salaries`
(
  `id`                      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                  BIGINT(20),
  `temporary_id`            INT,
  `record_number`           INT,
  `employee_last_name`      VARCHAR (256),
  `employee_first_name`     VARCHAR (256),
  `employee_middle_name` VARCHAR (256),
  `agency_number`           VARCHAR (256),
  `agency_name`             VARCHAR (256),
  `department_number`       VARCHAR (256),
  `branch_code`             VARCHAR (256),
  `branch_name`             VARCHAR (256),
  `job_code`                INT,
  `job_title`               VARCHAR (256),
  `location_number`         VARCHAR (256),
  `locatoin_name`           VARCHAR (256),
  `location_county_name`    VARCHAR (256),
  `location_postal_code`    INT,
  `reg_temp_code`           VARCHAR (256),
  `reg_temp_desc`           VARCHAR (256),
  `classified_code`         VARCHAR (256),
  `classified_desc`         VARCHAR (256),
  `original_hire_date`      VARCHAR (256),
  `last_hire_date`          VARCHAR (256),
  `job_entry_date`          VARCHAR (256),
  `full_part_time_code`     VARCHAR (256),
  `full_part_time_code`     VARCHAR (256),
  `salary_plan_grid`        VARCHAR (256),
  `salary_grade_range`      INT,
  `max_salary_step`         INT,
  `compensation_rate`       decimal(12,4),
  `comp_frequency_code`     VARCHAR (256),
  `comp_frequency_desc`     VARCHAR (256),
  `position_fte`            decimal (6,2),
  `bargaining_unit_number`  INT,
  `bargaining_unit_name`    VARCHAR (256),
  `active_on_june_30_2018`  VARCHAR (256),
  `year`                    INT,
  `created_by`      VARCHAR(255)      DEFAULT 'Aqeel',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci
    COMMENT = 'Aqeel Anwar';
