CREATE TABLE ky_general_info (
  `id` 					BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `is_district` 		TINYINT(1),
  `district_id`			BIGINT(20),
  `number` 				VARCHAR(15),
  `name` 				VARCHAR(255),
  `school_code` 		VARCHAR(15),
  `state_school_id` 	VARCHAR(15),
  `county_number` 		VARCHAR(255),
  `nces_id` 			VARCHAR(50),
  `coop_code` 			VARCHAR(50),
  `coop_name` 			VARCHAR(255),
  `school_type` 		VARCHAR(255),
  `low_grade` 			VARCHAR(255),
  `high_grade` 			VARCHAR(255),
  `title_1_status` 		VARCHAR(255),
  `program_type` 		VARCHAR(255),
  `education_program`	VARCHAR(255),
  `locale` 				VARCHAR(255),
  `phone` 				VARCHAR(255),
  `fax` 				VARCHAR(255),
  `website` 			VARCHAR(255),
  `address` 			VARCHAR(255),
  `city` 				VARCHAR(255),
  `county` 				VARCHAR(255),
  `state` 				VARCHAR(255),
  `zip` 				VARCHAR(255),
  `lat` 				VARCHAR(255),
  `lon` 				VARCHAR(255),
  `data_source_url` 	TEXT,
  `created_by`     		VARCHAR(255)      DEFAULT 'Frank Rao',
  `created_at`      	DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id`          	BIGINT(20),
  `touched_run_id`  	BIGINT,
  `deleted`         	BOOLEAN           DEFAULT 0,
  `md5_hash`        	VARCHAR(255),
  UNIQUE KEY        	`md5` (`md5_hash`),
  INDEX             	`run_id` (`run_id`),
  INDEX             	`touched_run_id` (`touched_run_id`),
  INDEX             	`deleted` (`deleted`)
)   DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci;

