create table `public_companies_stock_ft_com_equities_prices`
(
  `id`                     int auto_increment  primary key,
  `equity_symbol`          VARCHAR(255),
  `data_as_of`             datetime not null,
  `5yr_beta`               float,
  `price_usd`              float,
  `shares_traded`          VARCHAR(255),
  `yearly_change_pct`      VARCHAR(255),
  `open`                   float,
  `high`                   float,
  `low`                    float,
  `bid`                    float,
  `offer`                  float,
  `prev_close`             float,
  `avg_volume`             VARCHAR(255),
  `shares_outstanding`     VARCHAR(255),
  `free_float`             VARCHAR(255),
  `price_earnings_ratio`   VARCHAR(255),
  `market_cap_usd`         VARCHAR(255),
  `earnings_per_share_usd` VARCHAR(255),
  `52_wk_min_price`        float,
  `52_wk_min_price_date`   date,
  `52_wk_max_price`        float,
  `52_wk_max_price_date`   date,
  `data_source_url`        VARCHAR(255),
  `created_by`             VARCHAR(255)       DEFAULT 'Adeel',
  `created_at`             DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted`             tinyint(1)         default 0,
  `date_string`            VARCHAR(255),
  UNIQUE KEY `unique_data` (`data_source_url` ,`data_as_of`)
)DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
