CREATE TABLE `iowa_professional_licensing_scrape`
(
  `id`                                 bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id`                             int,
  `licensing_board`                    varchar(155) DEFAULT NULL,
  `licensee`                           varchar(155) DEFAULT NULL,
  `number`                             varchar(15)  DEFAULT NULL,
  `address_state`                      varchar(155) DEFAULT NULL,
  `license_type`                       varchar(155) DEFAULT NULL,
  `expiration_date`                    date DEFAULT NULL,
  `address_zip_postal_code`            varchar(15)  DEFAULT NULL,
  `renewed_date`                       date DEFAULT NULL,
  `reinstate_date`                     date DEFAULT NULL,
  `license_status`                     varchar(155) DEFAULT NULL,
  `address_city`                       varchar(155) DEFAULT NULL,
  `address_street`                     varchar(155) DEFAULT NULL,
  `firm_name`                          varchar(155) DEFAULT NULL,
  `conversion_date`                    date DEFAULT NULL,
  `original_created_date`              date DEFAULT NULL,
  `address_type`                       varchar(155) DEFAULT NULL,
  `last_status_change_date`            date DEFAULT NULL,
  `data_source_url`                    varchar(255) DEFAULT NULL,
  `data_source`                        varchar(255) DEFAULT 'Iowa Professional Licensing Scrape',
  `address_city_normalized`            varchar(155) DEFAULT NULL,
  `org_type`                           int(11) DEFAULT NULL,
  `org_category`                       int(11) DEFAULT NULL,
  `firm_name_cleaned`                  varchar(155) DEFAULT NULL,
  `lic_first_name`                     varchar(155) DEFAULT NULL,
  `lic_last_name`                      varchar(155) DEFAULT NULL,
  `lic_middle_name`                    varchar(155) DEFAULT NULL,
  `pl_production_org_name`             varchar(255) DEFAULT NULL,
  `pl_staging_org_status`              varchar(30)  DEFAULT NULL,
  `pl_staging_org_name`                varchar(255) DEFAULT NULL,
  `pl_production_org_id`               bigint(20)   DEFAULT NULL,
  `pl_production_org_status`           varchar(30)  DEFAULT NULL,
  `pl_staging_org_id`                  bigint(20)   DEFAULT NULL,
  `deleted`                            Boolean         DEFAULT 0,
  `touched_run_id`                     int          DEFAULT 0,
  `created_by`                         VARCHAR(255) DEFAULT 'Adeel',
  `created_at`                         DATETIME     DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `md5_hash`                           char(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `md5_hash` (`md5_hash`),
  KEY `iowa_professional_licensing_scrape_address_city_index` (`address_city`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
