 
create table `maine_campaign_finance_contributions_json`
 (
  `id`                        bigint AUTO_INCREMENT PRIMARY KEY,
-- Begin json fields --
  `entity_type`                     varchar(255),
  `committee_type_code`             varchar(255),
  `state_type`                      varchar(255),
  `state_name`                      varchar(255),
  `city`                            varchar(255),
  `amount`                          decimal(15,2),
  `name`                            varchar(255),
  `transaction_date`                date,
  `contributor_payee_name`          varchar(255),
  `address`                         varchar(255),
  `type`                            varchar(255),
  `transaction_id`                  bigint,
  `transaction_version_id`          int,
  `employment_occupation`           varchar(255),
  `committee_id`                    bigint,
  `committee_version_id`            int,
  `office_id`                       bigint,
  `election_id`                     bigint,
  `district_id`                     bigint,
  `election_cycle_id`               bigint,
  `election_name`                   varchar(255),
  `entity_type_description`         text,
  `transaction_category_code`       varchar(255),
  `transaction_purpose_description` text,
  `transaction_mode`                varchar(255),
  `election_period`                 varchar(255),
  `filed_date`                      date,
  `election_date`                   date,
  `employer`                        varchar(255),
  `occupation`                      varchar(255),
  `amended`                         varchar(255),
  `election_year`                   smallint,
  `report_name`                     varchar(255),
  `twenty_four_hour_report`         varchar(255),
  `contributor_payee_type`          varchar(255),
  `description`                     text,
  `series_amount`                   decimal(15,2),
  `bq_short_title`                  varchar(255),
  `bq_number`                       varchar(255),
  `support_oppose_candidate_ballot_question`      varchar(255),
  `support_oppose_ballot_question`                varchar(255),
  `bq_stance`                                     varchar(255),
  `operating_expense`                             varchar(255),
  `entity_type_desc`                              varchar(255),
  `stance`                                        varchar(255),
  `candidate_name`                                varchar(255),
  `candidate_id`                                  bigint,
  `committee_name`                                varchar(255),
  `office`                                        varchar(255),
  `district`                                      varchar(255),
  `office_status`                                 varchar(255),
  `incumbent_status_code`                         varchar(255),
  `jurisdiction`                                  varchar(255),
  `party`                                         varchar(255),
  `financing`                                     varchar(255),
  `transaction_amount`                            decimal(15,2),
  `is_off_set`                                    varchar(7),
  `ie_report`                                     varchar(7),
  `row_number`                                    bigint,
  `total_rows`                                    bigint,
  `election_type`                                 varchar(255),
  `can_comm_office`                               varchar(255),
  `can_comm_district`                             varchar(255),
  `cam_comm_jurisdiction`                         varchar(255),
  `can_comm_party`                                varchar(255),
  `can_comm_incumbent_status`                     varchar(255),
  `cam_comm_financing_status`                     varchar(255),
  `committee_type`                                varchar(255),
  `external_reference_id`                         bigint,
  `data_source_url`                               varchar(255) default 'https://mainecampaignfinance.com/index.html#/transaction/CON' null,
-- End json fields ------
  `created_by`                varchar(255)        default 'Frank Rao'         null,
  `created_at`                datetime            default CURRENT_TIMESTAMP   null,
  `updated_at`                timestamp           default CURRENT_TIMESTAMP   not null on update CURRENT_TIMESTAMP,
  `run_id`                    bigint                                          null,
  `touched_run_id`            bigint                                          null,
  `deleted`                   tinyint(1)          default 0                   null,
  `md5_hash`                  varchar(255)                                    null,
  UNIQUE KEY `unique_data` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;


