 
create table `maine_campaign_finance_expenditures_csv`
 (
  `id`                        bigint AUTO_INCREMENT PRIMARY KEY,
-- Begin csv fields --
  `year`                      smallint,
  `election_year`             smallint,
  `org_id`                    bigint,
  `legacy_id`                 bigint,
  `committee_type`            varchar(255),
  `committee_name`            varchar(255),
  `candidate_name`            varchar(255),
  `jurisdiction`              varchar(255),
  `office`                    varchar(255),
  `district`                  varchar(255),
  `party`                     varchar(255),
  `incumbent_status`          varchar(255),
  `financing_type`            varchar(255),
  `payee_last_name`           varchar(255),
  `payee_first_name`          varchar(255),
  `payee_middle_name`         varchar(255),
  `suffix`                    varchar(255),
  `address1`                  varchar(255),
  `address2`                  varchar(255),
  `city`                      varchar(255),
  `state`                     varchar(255),
  `zip`                       varchar(255),
  `expenditure_id`            bigint,
  `expenditure_date`          date,
  `expenditure_purpose`       varchar(255),
  `expenditure_amount`        decimal(15, 2),
  `expenditure_type`          varchar(255),
  `explanation`               varchar(255),
  `date_filed`                date,
  `amended`                   varchar(255),
  `ie_report`                 varchar(255),
  `24_hour_report`            varchar(255),
  `report_name`               varchar(255),
  `operating_expense`         varchar(255),
  `support_oppose_ballot_question`  varchar(255),
  `support_oppose_candidate`        varchar(255),
  `ballot_question_number`          varchar(255),
  `ballot_question_description_title` varchar(255),
  `candidate`                         varchar(255),
  `candidate_id`                      bigint,
  `candidate_office`                  varchar(255),      
  `candidate_district`                varchar(255),
  `candidate_party`                   varchar(255),
  `candidate_incumbent_status`        varchar(255),
  `candidate_financing_type`          varchar(255),
  `data_source_url`                   varchar(255) default 'https://mainecampaignfinance.com/index.html#/dataDownload' null,
-- End csv fields ------
  `created_by`                varchar(255)        default 'Frank Rao'         null,
  `created_at`                datetime            default CURRENT_TIMESTAMP   null,
  `updated_at`                timestamp           default CURRENT_TIMESTAMP   not null on update CURRENT_TIMESTAMP,
  `run_id`                    bigint                                          null,
  `touched_run_id`            bigint                                          null,
  `deleted`                   tinyint(1)          default 0                   null,
  `md5_hash`                  varchar(63)                                     null,
  UNIQUE KEY `unique_data` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;


