CREATE TABLE `us_tax_exempt_organization`
(
  `id`                                      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                                  BIGINT(20),
  `year`                                    VARCHAR(255),
  `legal_name`                              VARCHAR(255),
  `tax_period_to`                           VARCHAR(255),
  `tax_period_from`                         VARCHAR(255),
  `ein`                                     VARCHAR(255),
  `mailing_address`                         VARCHAR(255),
  `city`                                    VARCHAR(255),
  `state`                                   VARCHAR(255),
  `zip`                                     VARCHAR(255),
  `country`                                 VARCHAR(255),
  `principal_name`                          VARCHAR(255),
  `principal_address`                       VARCHAR(255),
  `principal_city`                          VARCHAR(255),
  `principal_state`                         VARCHAR(255),
  `principal_zip`                           VARCHAR(255),
  `principal_country`                       VARCHAR(255),
  `gross_receipts_not_greater_than_value`   INT(11),
  `gross_receipts_not_greater_than`         VARCHAR(255),
  `organization_terminated`                 VARCHAR(255),
  `website`                                 VARCHAR(255),
  `data_source_url`                         TEXT,
  `scrape_dev_name`                         VARCHAR(255)      DEFAULT 'Adeel',
  `scrape_frequency`                        VARCHAR(255),
  `created_at`                              DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`                          BIGINT,
  `deleted`                                 BOOLEAN           DEFAULT 0,
  `md5_hash`                                VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci
COMMENT = 'Adeel';
