CREATE TABLE `ct_state_employee_payroll_data`  
( 
   `id`                             int auto_increment  primary key, 
   `run_id`                         BIGINT(20),
   `Payment_fiscal_year`            int                  DEFAULT NULL, 
   `Calendar_Year`                  int                  DEFAULT NULL, 
   `Dept_ID`                        VARCHAR(256)         DEFAULT NULL, 
   `Employee_ID`                    VARCHAR(256)         DEFAULT NULL, 
   `First_Name`                     VARCHAR(256)         DEFAULT NULL, 
   `Middle_name`                    VARCHAR(256)         DEFAULT NULL, 
   `Last_Name`                      VARCHAR(256)         DEFAULT NULL, 
   `Name_suffix`                    VARCHAR(256)         DEFAULT NULL,
   `Check`                          int                  DEFAULT NULL,
   `Check_Date`                     DATE,
   `Check_option`                   VARCHAR(256)         DEFAULT NULL,
   `Check_Status`                   VARCHAR(256)         DEFAULT NULL,
   `Annual_rate`                    DECIMAL(12,2)        DEFAULT NULL,
   `Be_week_comp_rate`              DECIMAL(12,2)        DEFAULT NULL,
   `Other`                          int                  DEFAULT NULL,
   `Fringe`                         DECIMAL(12,2)        DEFAULT NULL,
   `Overtime`                       int                  DEFAULT NULL,
   `Salary_wages`                   DECIMAL(12,2)        DEFAULT NULL,
   `fringe_amt_no_retire`           DECIMAL(12,2)        DEFAULT NULL,
   `SERS_amount`                    DECIMAL(12,2)        DEFAULT NULL,
   `ARP_amount`                     int                  DEFAULT NULL,
   `Teachers_amount`                int                  DEFAULT NULL,
   `Judges_amount`                  int                  DEFAULT NULL,
   `Total_gross`                    DECIMAL(12,2)        DEFAULT NULL,
   `Age`                            int                  DEFAULT NULL,
   `Job_Code_description`           VARCHAR(256)         DEFAULT NULL,
   `ee_class_descr`                 VARCHAR(256)         DEFAULT NULL,
   `job_indicator`                  VARCHAR(256)         DEFAULT NULL,
   `Ethnicity`                      VARCHAR(256)         DEFAULT NULL,
   `Sex`                            VARCHAR(256)         DEFAULT NULL,
   `Full_Part`                      VARCHAR(256)         DEFAULT NULL,
   `Hire_date`                      DATE,
   `Termination_date`               VARCHAR(256)         DEFAULT NULL,
   `City`                           VARCHAR(256)         DEFAULT NULL,
   `postal`                         VARCHAR(256)         DEFAULT NULL,
   `State`                          VARCHAR(256)         DEFAULT NULL,
   `Union`                          VARCHAR(256)         DEFAULT NULL,
   `Agency`                         VARCHAR(256)         DEFAULT NULL,
   `deleted`                        BOOLEAN              DEFAULT 0, 
   `touched_run_id`                 int                  not null,
   `created_by`                     VARCHAR(255)         DEFAULT 'Afia', 
   `created_at`                     DATETIME             DEFAULT CURRENT_TIMESTAMP, 
   `updated_at`                     TIMESTAMP            DEFAULT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
   `md5_hash`                       VARCHAR(100)         DEFAULT NULL,
   UNIQUE KEY `unique_data` (`md5_hash`),
   INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci,
COMMENT = 'Created by Afia, Task #665';
