create table eada_equity_in_athletic(
  `id`                     int auto_increment   primary key,
  `run_id`                 BIGINT(20),
  `year`                   INT DEFAULT NULL,
  `unit_id`                INT DEFAULT NULL,
  `institution_name`       VARCHAR (255) DEFAULT NULL,
  `address1`               VARCHAR (255) DEFAULT NULL,
  `address2`               VARCHAR (255) DEFAULT NULL,
  `city`                   VARCHAR (255) DEFAULT NULL,
  `state`                  VARCHAR (255) DEFAULT NULL,
  `zip`                    VARCHAR (255) DEFAULT NULL,
  `classification_code`    INT DEFAULT NULL,
  `classification_name`    VARCHAR(255) DEFAULT NULL,
  `ef_male_count`          INT DEFAULT NULL,
  `ef_female_count`        INT DEFAULT NULL,
  `ef_total_count`         INT DEFAULT NULL,
  `sector_code`            INT DEFAULT NULL,
  `sector_name`            VARCHAR(255) DEFAULT NULL,
  `student_aid_men`        INT DEFAULT NULL,
  `student_aid_women`      INT DEFAULT NULL,
  `student_aid_coed`       INT DEFAULT NULL,
  `student_aid_total`      INT DEFAULT NULL,
  `aid_men_ratio`          INT DEFAULT NULL,
  `aid_women_ratio`        INT DEFAULT NULL,
  `aid_coed_ratio`         INT DEFAULT NULL,
  `hd_coach_sal_men`       INT DEFAULT NULL,
  `hd_coach_sal_women`     INT DEFAULT NULL,
  `hd_coach_sal_coed`      INT DEFAULT NULL,
  `num_hd_coach_men`       INT DEFAULT NULL,
  `num_hd_coach_women`     INT DEFAULT NULL,
  `num_hd_coach_coed`      INT DEFAULT NULL,
  `hd_coach_sal_fte_men`   INT DEFAULT NULL,
  `hd_coach_sal_fte_women` INT DEFAULT NULL,
  `hd_coach_sal_fte_coed`  INT DEFAULT NULL,
  `fte_hd_coach_men`       FLOAT DEFAULT NULL,
  `fte_hd_coach_women`     FLOAT DEFAULT NULL,
  `fte_hd_coach_coed`      FLOAT DEFAULT NULL,
  `as_coach_sal_men`       INT DEFAULT NULL,
  `as_coach_sal_women`     INT DEFAULT NULL,
  `as_coach_sal_coed`      INT DEFAULT NULL,
  `num_as_coach_men`       INT DEFAULT NULL,
  `num_as_coach_women`     INT DEFAULT NULL,
  `num_as_coach_coed`      INT DEFAULT NULL,
  `as_coach_sal_fte_men`   FLOAT DEFAULT NULL,
  `as_coach_sal_fte_women` FLOAT DEFAULT NULL,
  `as_coach_sal_fte_coed`  FLOAT DEFAULT NULL,
  `fte_as_coach_men`       FLOAT DEFAULT NULL,
  `fte_as_coach_women`     FLOAT DEFAULT NULL,
  `fte_as_coach_coed`      FLOAT DEFAULT NULL,
  `undup_ct_patric_men`    INT DEFAULT NULL,
  `undup_ct_patric_women`  INT DEFAULT NULL,
  `grand_total_revenue`    INT DEFAULT NULL,
  `total_exp_all_notalloc` INT DEFAULT NULL,
  `total_exp_bskball`      INT DEFAULT NULL,
  `exp_men_bskball`        INT DEFAULT NULL,
  `exp_women_bskball`      INT DEFAULT NULL,
  `total_exp_football`     INT DEFAULT NULL,
  `exp_men_football`       INT DEFAULT NULL,
  `exp_women_football`     INT DEFAULT NULL,
  `grand_total_expense`    INT DEFAULT NULL,
  `touched_run_id`         INT NULL,
  `data_source_url`        varchar(255) DEFAULT 'https://ope.ed.gov/athletics/#/datafile/list',
  `md5_hash`               varchar(255) GENERATED ALWAYS AS (md5(CONCAT_WS('', `year`, `unit_id`, `institution_name`, `address1`, `address2`, `city`,
  `state`, `zip`, `classification_code`, `classification_name`, `ef_male_count`, `ef_female_count`, `ef_total_count`, `sector_code`, `sector_name`, `student_aid_men`, `student_aid_women`, `student_aid_coed`,
  `student_aid_total`, `aid_men_ratio`, `aid_women_ratio`, `aid_coed_ratio`, `hd_coach_sal_men`, `hd_coach_sal_women`, `hd_coach_sal_coed`, `num_hd_coach_men`, `num_hd_coach_women`, `num_hd_coach_coed`,
  `hd_coach_sal_fte_men`, `hd_coach_sal_fte_women`, `hd_coach_sal_fte_coed`, `fte_hd_coach_men`, `fte_hd_coach_women`, `fte_hd_coach_coed`, `as_coach_sal_men`, `as_coach_sal_women`, `as_coach_sal_coed`, `fte_as_coach_men`, `fte_as_coach_women`, `fte_as_coach_coed`, `undup_ct_patric_men`, `undup_ct_patric_women`, `total_exp_all_notalloc`, 
  `grand_total_revenue`, `total_exp_bskball`, `exp_men_bskball`, `exp_women_bskball`, `total_exp_football`, `exp_men_football`, `exp_women_football`, `grand_total_expense`))) STORED,
  `deleted`             boolean          DEFAULT 0,
  `created_by`           VARCHAR(255)       DEFAULT 'Raza',
  `created_at`           DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_data` (`md5_hash`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
  COMMENT = 'Created by Raza Aslam, Task #514';
