CREATE TABLE `lawyer_status.ks_court_kscourts_org`
(
  `id`                              INT AUTO_INCREMENT PRIMARY KEY                                  NULL,
  `bar_number`                      VARCHAR(255)                                                    NULL,
  `name`                            VARCHAR(255)                                                    NULL,
  `name_prefix`                    VARCHAR(255)                                                    NULL,
  `first_name`                      VARCHAR(255)                                                    NULL,
  `last_name`                       VARCHAR(255)                                                    NULL,
  `middle_name`                     VARCHAR(255)                                                    NULL,
  `date_admited`                    DATE                                                            NULL,
  `registration_status`             VARCHAR(255)                                                    NULL,
  `sections`                        TEXT                                                            NULL,
  `type`                            VARCHAR(255)                                                    NULL,
  `phone`                           VARCHAR(255)                                                    NULL,
  `email`                           VARCHAR(255)                                                    NULL,
  `fax`                             VARCHAR(255)                                                    NULL,
  `law_firm_name`                   VARCHAR(255)                                                    NULL,
  `law_firm_address`                VARCHAR(255)                                                    NULL,
  `raw_address`                     TEXT                                                            NULL,
  `law_firm_zip`                    VARCHAR(255)                                                    NULL,
  `law_firm_city`                   VARCHAR(255)                                                    NULL,
  `law_firm_state`                  VARCHAR(255)                                                    NULL,
  `law_firm_county`                 VARCHAR(255)                                                    NULL,
  `university`                      VARCHAR(255)                                                    NULL,
  `professional_affiliation`        TEXT                                                            NULL,
  `bio`                             LONGTEXT                                                        NULL,
  `website`                         VARCHAR(255)                                                    NULL,
  `linkedin`                        VARCHAR(255)                                                    NULL,
  `facebook`                        VARCHAR(255)                                                    NULL,
  `twitter`                         VARCHAR(255)                                                    NULL,
  `law_firm_website`                VARCHAR(255)                                                    NULL,
  `other_jurisdictions`             TEXT                                                            NULL,
  `judicial_district`               VARCHAR(255)                                                    NULL,
  `disciplinary_actions`            TEXT                                                            NULL,
  `private_practice`                VARCHAR(255)                                                    NULL,
  `insurance`                       VARCHAR(255)                                                    NULL,
  `courts_of_admittance`            VARCHAR(255)                                                    NULL,

  `data_source_url`                 VARCHAR(255),
  `scrape_frequency`                VARCHAR(255)                        DEFAULT 'weekly'            NULL,
  `created_by`                      VARCHAR(255)                        DEFAULT 'AGlazkov',
  `created_at`                      DATETIME                            DEFAULT CURRENT_TIMESTAMP   NULL,
  `updated_at`                      TIMESTAMP                           DEFAULT CURRENT_TIMESTAMP   NOT NULL  ON UPDATE CURRENT_TIMESTAMP,
  
  `run_id`                          BIGINT(20)                                                      NULL,
  `touched_run_id`                  BIGINT                                                          NULL,
  `deleted`                         TINYINT(1)                          DEFAULT 0                   NULL,
  `md5_hash`                        VARCHAR(255)                                                    NULL,
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
  
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
