CREATE TABLE `north_carolina_business_licenses_new_business_csv` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`corp_name` varchar(255) DEFAULT NULL,
`date_formed` date DEFAULT NULL,
`citizenship` varchar(255) DEFAULT NULL,
`type_license` varchar(255) DEFAULT NULL,
`status` varchar(255) DEFAULT NULL,
`sos_id` varchar(255) DEFAULT NULL,
`registered_agent_name` varchar(255) DEFAULT NULL,
`reg_office_address1` varchar(255) DEFAULT NULL,
`reg_office_address2` varchar(255) DEFAULT NULL,
`reg_office_city` varchar(255) DEFAULT NULL,
`reg_office_state` varchar(255) DEFAULT NULL,
`reg_office_zip` varchar(255) DEFAULT NULL,
`reg_office_county` varchar(255) DEFAULT NULL,
`pitem_id` varchar(255) DEFAULT NULL,
`prin_address1` varchar(255) DEFAULT NULL,
`prin_address2` varchar(255) DEFAULT NULL,
`prin_city` varchar(255) DEFAULT NULL,
`prin_state` varchar(255) DEFAULT NULL,
`prin_zip` varchar(255) DEFAULT NULL,
`prin_county` varchar(255) DEFAULT NULL,
`scrape_dev_name` varchar(255) DEFAULT NULL,
`data_source_url` varchar(255) DEFAULT NULL,
`created_at` DATETIME           DEFAULT CURRENT_TIMESTAMP,
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`scrape_frequency` varchar(255) DEFAULT NULL,
`last_scrape_date` date DEFAULT NULL,
`next_scrape_date` date DEFAULT NULL,
`expected_scrape_frequency` varchar(255) DEFAULT NULL,
`pl_gather_task_id` varchar(255) DEFAULT NULL,
`dataset_name_prefix` varchar(255) DEFAULT NULL,
`scrape_status` varchar(255) DEFAULT NULL,
`scraped_by_pitem_id` boolean DEFAULT FALSE,
PRIMARY KEY (`id`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
