CREATE TABLE `north_carolina_business_licenses` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `year` int(11) DEFAULT NULL,
    `name` varchar(255) DEFAULT NULL,
    `sos_id` varchar(255) DEFAULT NULL,
    `status` varchar(255) DEFAULT NULL,
    `date_formed` date DEFAULT NULL,
    `citizenship` varchar(255) DEFAULT NULL,
    `fiscal_month` varchar(255) DEFAULT NULL,
    `annual_report_due_date` varchar(255) DEFAULT NULL,
    `registered_agent_name` varchar(255) DEFAULT NULL,
    `reg_office_full_address` varchar(255) DEFAULT NULL,
    `reg_office_address1` varchar(255) DEFAULT NULL,
    `reg_office_address2` varchar(255) DEFAULT NULL,
    `reg_office_city` varchar(255) DEFAULT NULL,
    `reg_office_state` varchar(255) DEFAULT NULL,
    `reg_office_zip` varchar(255) DEFAULT NULL,
    `reg_mailing_full_address` varchar(255) DEFAULT NULL,
    `reg_mailing_address1` varchar(255) DEFAULT NULL,
    `reg_mailing_address2` varchar(255) DEFAULT NULL,
    `reg_mailing_city` varchar(255) DEFAULT NULL,
    `reg_mailing_state` varchar(255) DEFAULT NULL,
    `reg_mailing_zip` varchar(255) DEFAULT NULL,
    `mailing_full_address` varchar(255) DEFAULT NULL,
    `mailing_address1` varchar(255) DEFAULT NULL,
    `mailing_address2` varchar(255) DEFAULT NULL,
    `mailing_city` varchar(255) DEFAULT NULL,
    `mailing_state` varchar(255) DEFAULT NULL,
    `mailing_zip` varchar(255) DEFAULT NULL,
    `scrape_dev_name` varchar(255) DEFAULT NULL,
    `data_source_url` varchar(255) DEFAULT NULL,
    `created_at` datetime DEFAULT NULL,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `scrape_frequency` varchar(255) DEFAULT NULL,
    `last_scrape_date` date DEFAULT NULL,
    `next_scrape_date` date DEFAULT NULL,
    `expected_scrape_frequency` varchar(255) DEFAULT NULL,
    `pl_gather_task_id` varchar(255) DEFAULT NULL,
PRIMARY KEY (`id`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;