CREATE TABLE `nc_general_info`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`          BIGINT(20),
  `is_district`         TINYINT(1),
  `district_id`         BIGINT(20),
  `number`              VARCHAR(20),
  `name`                VARCHAR(255),
  `type`                VARCHAR(255),
  `low_grade`           VARCHAR(20),
  `high_grade`          VARCHAR(20),
  `charter`             VARCHAR(20),
  `magnet`              VARCHAR(20),
  `title_1_school`      VARCHAR(20),
  `title_1_school_wide` VARCHAR(20),
  `nces_id`             VARCHAR(50),
  `phone`               VARCHAR(100),
  `county`              VARCHAR(255),
  `address`             VARCHAR(255),
  `city`                VARCHAR(255),
  `state`               VARCHAR(20),
  `zip`                 VARCHAR(20),
  `zip_4`               VARCHAR(20),
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'agegic',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nc_assessment`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(50),
  `school_code`      VARCHAR(50),
  `aggregation`      VARCHAR(255),
  `subject_group`    VARCHAR(255),
  `letter`           VARCHAR(20),
  `score`            VARCHAR(50),
  `achivement_sc`    VARCHAR(50),
  `growth_sc`        VARCHAR(50),
  `growth`           VARCHAR(50),
  `grows_idx`        VARCHAR(50),
  `assessment_sc`    VARCHAR(50),
  `science_eog_sc`   VARCHAR(50),
  `el_progress_sc`   VARCHAR(50),
  `4y_graduation_sc` VARCHAR(50),
  `biology_eoc_sc`   VARCHAR(50),
  `act_sc`           VARCHAR(50),
  `math_3_sc`        VARCHAR(50),
  `data_source_url`  TEXT,
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nc_assessment_act`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(50),
  `grade`            VARCHAR(50),
  `subject`          VARCHAR(255),
  `mean`             VARCHAR(50),
  `met_benchmark`    VARCHAR(50),
  `number_tested`    VARCHAR(50),
  `data_source_url`  TEXT,
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nc_assessment_ap_sat`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(50),
  `test`             VARCHAR(50),
  `statistics`       VARCHAR(255),
  `number`           VARCHAR(50),
  `data_source_url`  TEXT,
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nc_finaces_expenditures`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(50),
  `prc`              VARCHAR(50),
  `description`      VARCHAR(255),
  `expenditures`     VARCHAR(50),
  `data_source_url`  TEXT,
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nc_finances_salaries`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(50),
  `code`             VARCHAR(50),
  `description`      VARCHAR(255),
  `expenditures`     VARCHAR(50),
  `percent`          VARCHAR(50),
  `data_source_url`  TEXT,
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;
