CREATE TABLE us_courts_staging_working_copy.non_lawyer_parties LIKE us_courts_staging.non_lawyer_parties;
INSERT us_courts_staging_working_copy.non_lawyer_parties SELECT * FROM us_courts_staging.non_lawyer_parties;


CREATE TABLE us_courts_staging_working_copy.lawyers_universities LIKE us_courts_staging.lawyers_universities;
INSERT us_courts_staging_working_copy.lawyers_universities SELECT * FROM us_courts_staging.lawyers_universities;

CREATE TABLE us_courts_staging_working_copy.law_schools LIKE us_courts_staging.law_schools;
INSERT us_courts_staging_working_copy.law_schools SELECT * FROM us_courts_staging.law_schools;


CREATE TABLE us_courts_staging_working_copy.lawyers_law_schools LIKE us_courts_staging.lawyers_law_schools;
INSERT us_courts_staging_working_copy.lawyers_law_schools SELECT * FROM us_courts_staging.lawyers_law_schools;

CREATE TABLE us_courts_staging_working_copy.judges LIKE us_courts_staging.judges;
INSERT us_courts_staging_working_copy.judges SELECT * FROM us_courts_staging.judges;

CREATE TABLE us_courts_staging_working_copy.judges_universities LIKE us_courts_staging.judges_universities;
INSERT us_courts_staging_working_copy.judges_universities SELECT * FROM us_courts_staging.judges_universities;

CREATE TABLE us_courts_staging_working_copy.court_addresses LIKE us_courts_staging.court_addresses;
INSERT us_courts_staging_working_copy.court_addresses SELECT * FROM us_courts_staging.court_addresses;

CREATE TABLE us_courts_staging_working_copy.judges_law_schools LIKE us_courts_staging.judges_law_schools;
INSERT us_courts_staging_working_copy.judges_law_schools SELECT * FROM us_courts_staging.judges_law_schools;


