CREATE DATABASE us_courts_staging_working_copy;



CREATE TABLE us_courts_staging_working_copy.law_firm_names SELECT * FROM us_courts_staging.law_firm_names;
CREATE TABLE us_courts_staging_working_copy.law_firm_names_addresses SELECT * FROM us_courts_staging.law_firm_names_addresses;
CREATE TABLE us_courts_staging_working_copy.law_firm_addresses SELECT * FROM us_courts_staging.law_firm_addresses;

CREATE TABLE us_courts_staging_working_copy.judges_law_firms_new SELECT * FROM us_courts_staging.judges_law_firms;
CREATE TABLE us_courts_staging_working_copy.judges_law_firms_BACKUP SELECT * FROM us_courts_staging.judges_law_firms_BACKUP;


SELECT * from us_courts_staging_working_copy.judges_law_firm_names;

INSERT IGNORE INTO us_courts_staging.law_firm_names_addresses SELECT * FROM us_courts_staging_working_copy.law_firm_names_addresses;