create table `nevada_criminal_offenders_offenses`
 (
  `id`  int auto_increment   primary key,
  `offender_id` varchar(255) DEFAULT NULL,
  `offender_book_id` varchar(255) DEFAULT NULL,
  `charge_seq` varchar(255) DEFAULT NULL,
  `offense_code` varchar(255) DEFAULT NULL,
  `sent_seq` varchar(255) DEFAULT NULL,
  `sent_status` varchar(255) DEFAULT NULL,
  `sent_min_yrs` varchar(255) DEFAULT NULL,
  `sent_min_mths` varchar(255) DEFAULT NULL,
  `sent_min_days` varchar(255) DEFAULT NULL,
  `sent_max_yrs` varchar(255) DEFAULT NULL,
  `sent_max_mths` varchar(255) DEFAULT NULL,
  `sent_max_days` varchar(255) DEFAULT NULL,
  `sent_ped` date DEFAULT NULL,
  `sent_mpr` varchar(255) DEFAULT NULL,
  `sent_county` varchar(255) DEFAULT NULL,
  `sent_pexd` date DEFAULT NULL,
  `sent_type` varchar(255) DEFAULT NULL,
  `sent_rrd` varchar(255) DEFAULT NULL,
  `sent_start_date` date DEFAULT NULL,
  `scrape_dev_name` varchar(255) DEFAULT 'Adeel',
  `data_source_url` varchar(255) DEFAULT 'https://ofdsearch.doc.nv.gov/form.php',
  `scrape_frequency` varchar(255) DEFAULT NULL,
  `last_scrape_date` date DEFAULT NULL,
  `next_scrape_date` date DEFAULT NULL,
  `expected_scrape_frequency` varchar(255) DEFAULT NULL,
  `dataset_name_prefix` varchar(255) DEFAULT NULL,
  `scrape_status` varchar(255) DEFAULT NULL,
  `pl_gather_task_id` int(11) DEFAULT NULL,
  `created_by`           VARCHAR(255)       DEFAULT 'Adeel',
  `created_at`           DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `md5hash` varchar(100) DEFAULT NULL,
  `is_deleted` int(1) DEFAULT '0',
  UNIQUE KEY `unique_data` (`md5_hash`)
  ) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
