CREATE TABLE `oh_professional_licences`
(
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name`  VARCHAR(255),
  `company_name` VARCHAR(255),
  `first_name` VARCHAR(255) ,
  `middle_name` VARCHAR(255) ,
  `last_name` VARCHAR(255) ,
  `status` VARCHAR(255) ,
  `sub_status` VARCHAR(255) ,
  `sub_category` VARCHAR(255) ,
  `board` VARCHAR(255) ,
  `license_type` VARCHAR(255) ,
  `license_num` VARCHAR(255) ,
  `issue_date`  DATE,
  `issue_date_unix_timestamp` bigint,
  `effective_date`  DATE,
  `effective_date_unix_timestamp` bigint,
  `expiration_date`  DATE,
  `expiration_date_unix_timestamp` bigint,
  `city` VARCHAR(255) ,
  `state` VARCHAR(255) ,
  `county` VARCHAR(255) ,
  `country` VARCHAR(255) ,
  `zip`  VARCHAR(255) ,
  `is_business_license` VARCHAR(255) ,
  `board_action` VARCHAR(255) ,
  `address` VARCHAR(255) ,
  `md5_hash`  VARCHAR(255) GENERATED ALWAYS AS (md5(CONCAT_WS('', company_name, name, status, sub_status, sub_category, board, license_type, license_num, CAST(issue_date as CHAR), CAST(effective_date as CHAR), CAST(expiration_date as CHAR), city, state, country, zip, address, county, CAST(is_business_license as CHAR), board_action, data_source_url))) STORED,
  `data_source_url` VARCHAR(255),
  `deleted` int DEFAULT 0,
  `run_id`  VARCHAR(255),
  `touch_run_id`  VARCHAR(255),
  `scrape_frequency`    varchar(255)       DEFAULT 'Weekly',
  `scrape_dev_name`          VARCHAR(255)       DEFAULT 'Adeel',
  `created_at`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_data` (`md5_hash`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
