CREATE TABLE `ny_assessment`
(
  `id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id` BIGINT(20),
  `general_id`  bigint(20),
  `school_year` varchar(50),
  `subject` varchar(255),
  `grade` varchar(50),
  `subgroup_code` varchar(255),
  `subgroup`  varchar(255),
  `total_enrolled`  varchar(255),
  `total_not_tested`  varchar(255),
  `total_tested`  varchar(255),
  `l1_count`  varchar(255),
  `l1_percent`  varchar(255),
  `l2_count`  varchar(255),
  `l2_percent`  varchar(255),
  `l3_count`  varchar(255),
  `l3_percent`  varchar(255),
  `l4_count`  varchar(255),
  `l4_percent`  varchar(255),
  `proficient_percent` varchar(255),
  `mean_scale_score`  varchar(255),
  `assessment` VARCHAR(255),
  `total_not_tested_pct` VARCHAR(255),
  `total_tested_pct` VARCHAR(255),
  `proficient_count` VARCHAR(255),
  `l5_count` VARCHAR(255),
  `l5_percent` VARCHAR(255),
  `total_scale_score` VARCHAR(255),
  `data_source_url` TEXT,
  `created_by` VARCHAR(255) DEFAULT 'Hassan',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id` BIGINT,
  `deleted` BOOLEAN DEFAULT 0,
  `md5_hash` VARCHAR(255) GENERATED ALWAYS AS (MD5(CONCAT_WS('',general_id,school_year,subject,grade,subgroup_code,subgroup,total_enrolled,total_not_tested,total_tested,l1_count,l1_percent,l2_count,l2_percent,l3_count,l3_percent,l4_count,l4_percent,proficient_percent,mean_scale_score,assessment,total_not_tested_pct,total_tested_pct,proficient_count,l5_count,l5_percent,total_scale_score))) STORED,
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
