CREATE TABLE `ny_graduation`
(
  `id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id` BIGINT(20),
  `general_id`  bigint(20),
  `school_year` varchar(50),
  `membership_code` varchar(255),
  `membership_key`  varchar(255),
  `membership_desc` varchar(255),
  `subgroup_code` varchar(255),
  `subgroup`  varchar(255),
  `enroll_count`  varchar(255),
  `grad_count`  varchar(255),
  `grad_percent`  varchar(255),
  `local_count` varchar(255),
  `local_percent` varchar(255),
  `reg_count` varchar(255),
  `reg_percent` varchar(255),
  `reg_adv_count` varchar(255),
  `reg_adv_percent` varchar(255),
  `non_diploma_credential_count`  varchar(255),
  `non_diploma_credential_percent`  varchar(255),
  `still_enr_count` varchar(255),
  `still_enr_percent` varchar(255),
  `ged_count` varchar(255),
  `ged_percent` varchar(255),
  `dropout_count` varchar(255),
  `dropout_percent` varchar(255),
  `data_source_url` TEXT,
  `created_by` VARCHAR(255) DEFAULT 'Hassan',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id` BIGINT,
  `deleted` BOOLEAN DEFAULT 0,
  `md5_hash` VARCHAR(255) GENERATED ALWAYS AS (MD5(CONCAT_WS('',general_id,school_year,membership_code,membership_key,membership_desc,subgroup_code,subgroup,enroll_count,grad_count,grad_percent,local_count,local_percent,reg_count,reg_percent,reg_adv_count,reg_adv_percent,non_diploma_credential_count,non_diploma_credential_percent,still_enr_count,still_enr_percent,ged_count,ged_percent,dropout_count,dropout_percent))) STORED,
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
