CREATE TABLE `ok_bar__okbar_org` 
(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `bar_number` varchar(255) DEFAULT NULL,
  `lawyer_type` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `middle_name` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `data_source_url` varchar(255) DEFAULT NULL,
  `law_firm_name` varchar(255) DEFAULT NULL,
  `law_firm_address` varchar(255) DEFAULT NULL,
  `law_firm_zip` varchar(255) DEFAULT NULL,
  `law_firm_city` varchar(255) DEFAULT NULL,
  `law_firm_state` varchar(255) DEFAULT NULL,
  `law_firm_county` varchar(255) DEFAULT NULL,
  `name_prefix` varchar(255) DEFAULT NULL,
  `university` json DEFAULT NULL,
  `professional_affiliation` text,
  `bio` longtext,
  `website` varchar(255) DEFAULT NULL,
  `linkedin` varchar(512) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `law_firm_website` varchar(255) DEFAULT NULL,
  `other_jurisdictions` text,
  `judicial_district` varchar(255) DEFAULT NULL,
  `disciplinary_actions` text,
  `private_practice` varchar(255) DEFAULT NULL,
  `insurance` varchar(255) DEFAULT NULL,
  `courts_of_admittance` varchar(255) DEFAULT NULL,
  `date_admitted` date DEFAULT NULL,
  `registration_status` varchar(255) DEFAULT NULL,
  `sections` json DEFAULT NULL,
  `created_by` varchar(255) DEFAULT 'Hassan',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` bigint(20) DEFAULT NULL,
  `touched_run_id` bigint(20) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  `scrape_frequency` varchar(255) DEFAULT 'weekly',
  `md5_hash` varchar(150) GENERATED ALWAYS AS (md5(CONCAT_WS('', bar_number, law_firm_city, law_firm_state, type, registration_status, CAST(date_admitted as char))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `md5_hash` (`md5_hash`),
  KEY `run_id` (`run_id`),
  KEY `touched_run_id` (`touched_run_id`),
  KEY `deleted` (`deleted`),
  KEY `bar_number` (`bar_number`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
