CREATE TABLE `il_lake_county_sheriff_info`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`          BIGINT(20),
  `booking_id`      VARCHAR(255),
  `name`            VARCHAR(255),
  `sex`             VARCHAR(10),
  `address`         VARCHAR(255),
  `location`        VARCHAR(255),
  `status`          VARCHAR(255),
  `booked_date`     DATE,
  `photo_url`       VARCHAR(1024),
  `race`            VARCHAR(255),
  `width`           VARCHAR(255),
  `height`          VARCHAR(255),
  `city`            VARCHAR(255),
  `zip`             VARCHAR(255),
  `state`           VARCHAR(255),
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Mikhail Golovanov',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
