CREATE TABLE `new_jersey_state_campaign_contributions_csv`
(
  `id`                      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `year`                    VARCHAR(255),
  `file_name`               VARCHAR(255),
  `CONT_LNAME`              VARCHAR(255),
  `CONT_FNAME`              VARCHAR(255),
  `CONT_MNAME`              VARCHAR(255),
  `CONT_SUFFIX`             VARCHAR(255),
  `CONT_NON_IND_NAME`       VARCHAR(255),
  `CONT_NON_IND_NAME2`      VARCHAR(255),
  `CONT_STREET1`            VARCHAR(255),
  `CONT_STREET2`            VARCHAR(255),
  `CONT_CITY`               VARCHAR(255),
  `CONT_STATE`              VARCHAR(255),
  `CONT_ZIP`                VARCHAR(255),
  `CONT_TYPE`               VARCHAR(255),
  `CONT_AMT`                VARCHAR(255),
  `RECEIPT_TYPE`            VARCHAR(255),
  `CONT_DATE`               DATE,
  `OCCUPATION`              VARCHAR(255),
  `EMP_NAME`                VARCHAR(255),
  `EMP_STREET1`             VARCHAR(255),
  `EMP_STREET2`             VARCHAR(255),
  `EMP_CITY`                VARCHAR(255),
  `EMP_STATE`               VARCHAR(255),
  `EMP_ZIP`                 VARCHAR(255),
  `REC_LNAME`               VARCHAR(255),
  `REC_FNAME`               VARCHAR(255),
  `REC_MNAME`               VARCHAR(255),
  `REC_SUFFIX`              VARCHAR(255),
  `REC_NON_IND_NAME`        VARCHAR(255),
  `REC_NON_IND_NAME2`       VARCHAR(255),
  `OFFICE`                  VARCHAR(255),
  `PARTY`                   VARCHAR(255),
  `LOCATION`                VARCHAR(255),
  `ELECTION_YEAR`           VARCHAR(255),
  `ELECTION_TYPE`           VARCHAR(255),
  `data_source_url`         VARCHAR(255)      DEFAULT 'https://www.elec.state.nj.us/publicinformation/contrib_quickdownload.htm',
  `created_by`              VARCHAR(255)       DEFAULT 'Adeel',
  `created_at`              DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
