CREATE TABLE `cdc_weekly_counts_of_deaths_by_state_and_select_causes`
(
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `data_source_url` varchar(255) DEFAULT NULL,
     `jurisdiction` varchar(255) NOT NULL,
     `mmwr_year` smallint NOT NULL,
     `mmwr_week` tinyint NOT NULL,
     `week_ending_date` date NOT NULL,
     `allcause` varchar(10) NOT NULL,
     `natcause` varchar(10) NOT NULL,
     `sept` varchar(10) NOT NULL,
     `neopl` varchar(10) NOT NULL,
     `diab` varchar(10) NOT NULL,
     `alz` varchar(10) NOT NULL,
     `inflpn` varchar(10) NOT NULL,
     `clrd` varchar(10) NOT NULL,
     `otherresp` varchar(10) NOT NULL,
     `nephr` varchar(10) NOT NULL,
     `otherunk` varchar(10) NOT NULL,
     `hd` varchar(10) NOT NULL,
     `stroke` varchar(10) NOT NULL,
     `cov19mcod` varchar(10) NOT NULL,
     `cov19ucod` varchar(10) NOT NULL,
     `deleted_at` date DEFAULT NULL,
     `created_by` varchar(255) DEFAULT NULL,
     `created_at` datetime DEFAULT NULL,
     `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     `last_scrape_date` date DEFAULT NULL,
     `next_scrape_date` date DEFAULT NULL,
     `expected_scrape_frequency` varchar(255) DEFAULT NULL,
     `dataset_name_prefix` varchar(255) DEFAULT NULL,
     `scrape_status` varchar(255) DEFAULT NULL,
     `pl_gather_task_id` varchar(255) DEFAULT NULL,
     PRIMARY KEY (`id`),
     UNIQUE KEY `unique_cdc_weekly_counts_of_deaths` (`jurisdiction`,
                                                      `week_ending_date`,
                                                      `allcause`,
                                                      `natcause`,
                                                      `sept`,
                                                      `neopl`,
                                                      `diab`,
                                                      `alz`,
                                                      `inflpn`,
                                                      `clrd`,
                                                      `otherresp`,
                                                      `nephr`,
                                                      `hd`,
                                                      `stroke`,
                                                      `cov19mcod`,
                                                      `cov19ucod`)
);