CREATE TABLE `delaware_voter_registrations`
(
  `id`                          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                      BIGINT(20),
  `month`                       VARCHAR(255),
  `year`                        VARCHAR(255),
  `county`                      VARCHAR(255),
  `amer_delta`                  VARCHAR(255),
  `american`                    VARCHAR(255),
  `blue_enigima`                VARCHAR(255),
  `conservative`                VARCHAR(255),
  `constitution`                VARCHAR(255),
  `democratic`                  VARCHAR(255),
  `green`                       VARCHAR(255),
  `ind_pty_of_de`               VARCHAR(255),
  `liberal`                     VARCHAR(255),
  `libertarian`                 VARCHAR(255),
  `mandalorians`                VARCHAR(255),
  `natural_law`                 VARCHAR(255),
  `no_party`                    VARCHAR(255),
  `nonpartisan`                 VARCHAR(255),
  `other`                       VARCHAR(255),
  `reform`                      VARCHAR(255),
  `republican`                  VARCHAR(255),
  `socialst_wr`                 VARCHAR(255),
  `working_fam`                 VARCHAR(255),
  `grand_total`                 VARCHAR(255),
  `scrape_dev_name`             varchar(255)   DEFAULT 'Adeel',   
  `data_source_url`             TEXT,
  `created_at`                  DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,                                                                                                  
  `scrape_frequency`            varchar(255)   DEFAULT 'Monthly',                                                    
  `last_scrape_date`            date ,                                                       
  `next_scrape_date`            date ,                                                   
  `expected_scrape_frequency`   varchar(255)   DEFAULT 'Monthly',                                                    
  `dataset_name_prefix`         varchar(255)   DEFAULT 'delaware_voter_registrations',                                          
  `scrape_status`               varchar(255)   DEFAULT 'Live' ,                                                       
  `pl_gather_task_id`           int(11)        DEFAULT '8689' ,
  `md5_hash`        VARCHAR(255)GENERATED ALWAYS AS (md5(concat_ws('',month,year,county,amer_delta,american,blue_enigima,conservative,constitution,democratic,green,ind_pty_of_de,liberal,libertarian,mandalorians,natural_law,no_party,nonpartisan,other,reform,republican,socialst_wr,working_fam,grand_total))) STORED,
  UNIQUE KEY `md5` (`md5_hash`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci
    COMMENT = 'The Scrape made by ';
