CREATE TABLE ak_revenue 
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  general_id BIGINT(20),
  school_year VARCHAR(50),
  revenues_type VARCHAR(255),
  type VARCHAR(255),
  adm VARCHAR(255),
  op_fund_local VARCHAR(255),
  op_fund_state VARCHAR(255),
  op_fund_federal VARCHAR(255),
  op_fund_other VARCHAR(255),
  special_rev_funds VARCHAR(255),
  total_revenue VARCHAR(255),
  pupil_trans VARCHAR(255),
  grand_total VARCHAR(255),
  data_source_url TEXT,
  created_by VARCHAR(255) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  run_id BIGINT(20),
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX general_id (general_id),
  INDEX run_id (run_id),
  INDEX touched_run_id (touched_run_id),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;
