CREATE TABLE ak_teacher_counts 
(
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  general_id BIGINT(20),
  school_year VARCHAR(50),
  remedial_specialist_count VARCHAR(255),
  remedial_specialist_fte VARCHAR(255),
  head_teacher_count VARCHAR(255),
  head_teacher_fte VARCHAR(255),
  teacher_count VARCHAR(255),
  teacher_fte VARCHAR(255),
  visiting_teacher_count VARCHAR(255),
  visiting_teacher_fte VARCHAR(255),
  sped_teacher_count VARCHAR(255),
  sped_teacher_fte VARCHAR(255),
  esl_teacher_count VARCHAR(255),
  esl_teacher_fte VARCHAR(255),
  onsite_supervis_teacher_count VARCHAR(255),
  onsite_supervis_teacher_fte VARCHAR(255),
  correspond_teacher_count VARCHAR(255),
  correspond_teacher_fte VARCHAR(255),
  online_course_fac_teacher_count VARCHAR(255),
  online_course_fac_teacher_fte VARCHAR(255),
  associate_teacher_count VARCHAR(255),
  associate_teacher_fte VARCHAR(255),
  total_teacher_count VARCHAR(255),
  total_teacher_fte VARCHAR(255),
  total_students_kg_12 VARCHAR(255),
  total_students_pk_12 VARCHAR(255),
  student_teacher_ratio VARCHAR(255),
  data_source_url TEXT,
  created_by VARCHAR(255) DEFAULT 'Umar',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  touched_run_id BIGINT,
  deleted BOOLEAN DEFAULT 0,
  md5_hash VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `general_id` (`general_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_520_ci;
