create table `co_assessment_sat_psat`
(
  `id`                               int auto_increment   primary key,
  `run_id`                           int,
  `general_id`                       bigint  (20),
  `school_year`                      varchar (50),
  `subject`                          varchar (255),
  `grade`                            varchar (255),
  `total_records`                    varchar (255),
  `valid_scores`                     varchar (255),
  `no_scores`                        varchar (255),
  `parcipation_rate`                 varchar (255),
  `mean_scale_score`                 varchar (255),
  `standart_deviation`               varchar (255),
  `not_yet_meet_count`               varchar (255),
  `not_yet_meet_percent`             varchar (255),
  `partially_met_count`              varchar (255),
  `partially_met_percent`            varchar (255),
  `approached_count`                 varchar (255),
  `approached_percent`               varchar (255),
  `met_count`                        varchar (255),
  `met_percent`                      varchar (255),
  `exceeded_count`                   varchar (255),
  `exceeded_percent`                 varchar (255),
  `met_and_exceeded_count`           varchar (255),
  `met_and_exceeded_percent`         varchar (255),
  `deleted`                          BOOLEAN            DEFAULT 0,
  `touched_run_id`                   int,
  `md5_hash`                         VARCHAR(255)       DEFAULT NULL,
  `data_source_url`                  varchar (350),      
  `created_by`                       VARCHAR(255)       DEFAULT 'Tauseeq',
  `created_at`                       DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id_index` (`run_id`),
  INDEX `general_id_index` (`general_id`),
  INDEX `school_year_index` (`school_year`),
  INDEX `deleted_index` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
  COMMENT = 'Created by Tauseeq Tufail, Task #662';
