CREATE TABLE `michigan_campaign_finance_candidates`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`          BIGINT(20),
  `statement_year`  VARCHAR(255),
  `committee_id`    INT,
  `doc_seq_num`     BIGINT,
  `committee_type`  VARCHAR(255),
  `committee_name`  VARCHAR(255),
  `full_name`       VARCHAR(255),
  `last_name`       VARCHAR(255),
  `first_name`      VARCHAR(255),
  `middle_name`     VARCHAR(255),
  `party`           VARCHAR(30),
  `curr_occupation` VARCHAR(255),
  `position_sought` VARCHAR(255),
  `district`        VARCHAR(255),
  `full_address`    VARCHAR(255),
  `address1`        VARCHAR(255),
  `address2`        VARCHAR(255),
  `city`            VARCHAR(255),
  `county`          VARCHAR(255),
  `state`           VARCHAR(255),
  `zip`             VARCHAR(20),
  `phone`           VARCHAR(255),
  `email`           VARCHAR(255),
  `website`         VARCHAR(255),
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
