CREATE TABLE `michigan_campaign_finance_committees`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  `candidate_id`      BIGINT,
  `committee_name`    VARCHAR(255),
  `committee_number`  VARCHAR(255),
  `district`          VARCHAR(255),
  `party`             VARCHAR(255),
  `election_year`     VARCHAR(255),
  `office_sought`     VARCHAR(255),
  `county`            VARCHAR(255),
  `chair_name`        VARCHAR(255),
  `chair_address`     VARCHAR(255),
  `chair_city`        VARCHAR(255),
  `chair_state`       VARCHAR(255),
  `chair_zip`         VARCHAR(20),
  `chair_phone`       VARCHAR(255),
  `chair_email`       VARCHAR(255),
  `treasurer_name`    VARCHAR(255),
  `treasurer_address` VARCHAR(255),
  `treasurer_city`    VARCHAR(255),
  `treasurer_state`   VARCHAR(255),
  `treasurer_zip`     VARCHAR(20),
  `treasurer_phone`   VARCHAR(255),
  `treasurer_email`   VARCHAR(255),
  `parent_entity`     VARCHAR(255),
  `parent_address`    VARCHAR(255),
  `parent_city`       VARCHAR(255),
  `parent_state`      VARCHAR(255),
  `parent_zip`        VARCHAR(20),
  `contact_name`      VARCHAR(255),
  `contact_address`   VARCHAR(255),
  `contact_city`      VARCHAR(255),
  `contact_state`     VARCHAR(255),
  `contact_zip`       VARCHAR(20),
  `contact_phone`     VARCHAR(255),
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`        DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN           DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
