CREATE TABLE `michigan_campaign_finance_contributions`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`          BIGINT(20),
  `doc_seq_num`     BIGINT,
  `page_no`         BIGINT,
  `contributor_id`  BIGINT,
  `cont_detail_id`  BIGINT,
  `doc_stmnt_year`  VARCHAR(255),
  `doc_type_desc`   VARCHAR(255),
  `committee_name`  VARCHAR(255),
  `committee_type`  VARCHAR(255),
  `committee_id`    BIGINT,
  `type`            VARCHAR(255),
  `date`            DATE,
  `amount`          DECIMAL(15,2),
  `type2`           VARCHAR(255),
  `check_number`    VARCHAR(255),
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
