CREATE TABLE `michigan_campaign_finance_expenditures`
(
  `id`                        BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                    BIGINT(20),
  `doc_seq_num`               BIGINT,
  `expenditure_type`          VARCHAR(255),
  `page_num`                  BIGINT,
  `date`                      DATE,
  `payee_id`                  VARCHAR(255),
  `detail_id`                 VARCHAR(255),
  `doc_stmnt_year`            VARCHAR(255),
  `doc_type_desc`             VARCHAR(255),
  `payee_name`                VARCHAR(255),
  `payee_type`                VARCHAR(255),
  `amount`                    DECIMAL(15,2),
  `type`                      VARCHAR(255),
  `type2`                     VARCHAR(255),
  `check_number`              VARCHAR(255),
  `committee_name`            VARCHAR(255),
  `committee_id`              VARCHAR(255),
  `expense_category`          VARCHAR(255),
  `expense_description`       VARCHAR(255),
  `expense_purpose`           VARCHAR(255),
  `extra_expense_description` VARCHAR(255),
  `expense_method`            VARCHAR(255),
  `address`                   VARCHAR(255),
  `city`                      VARCHAR(255),
  `county`                    VARCHAR(255),
  `state`                     VARCHAR(255),
  `zip`                       VARCHAR(20),
  `state_loc`                 VARCHAR(255),
  `support_oppose`            VARCHAR(255),
  `candidate_or_ballot`       VARCHAR(255),
  `debt_payment`              VARCHAR(255),
  `vend_name`                 VARCHAR(255),
  `vend_addr`                 VARCHAR(255),
  `vend_city`                 VARCHAR(255),
  `vend_state`                VARCHAR(255),
  `vend_zip`                  VARCHAR(20),
  `gotv_ink_ind`              VARCHAR(255),
  `data_source_url`           TEXT,
  `created_by`                VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`                DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`            BIGINT,
  `deleted`                   BOOLEAN           DEFAULT 0,
  `md5_hash`                  VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
