CREATE TABLE IF NOT EXISTS `ga_assessment_eog_by_grade` (
  `id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `general_id` BIGINT(20),
  `school_year` VARCHAR(50),
  `grade` VARCHAR(50),
  `subgroup` VARCHAR(255),
  `test` VARCHAR(255),
  `tested_count` VARCHAR(255),
  `begin_count` VARCHAR(255),
  `begin_percent` VARCHAR(255),
  `developing_count` VARCHAR(255),
  `developing_percent` VARCHAR(255),
  `proficient_count` VARCHAR(255),
  `proficient_percent` VARCHAR(255),
  `distinguished_count` VARCHAR(255),
  `distinguished_percent` VARCHAR(255),
  `data_source_url` VARCHAR(255),
  `created_by` VARCHAR(255) DEFAULT 'Shahrukh Nawaz',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT,
  `touched_run_id` BIGINT,
  `deleted` BOOLEAN DEFAULT 0,
  `md5_hash` VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;