CREATE TABLE IF NOT EXISTS `ga_salaries_benefits` (
  `id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `general_id` BIGINT(20),
  `school_year` VARCHAR(50),
  `category` VARCHAR(255),
  `salaries` VARCHAR(255),
  `benefits` VARCHAR(255),
  `salaries_and_benefits` VARCHAR(255),
  `rev_gf_title_lottery_percent` VARCHAR(255),
  `rev_total_k_12_percent` VARCHAR(255),
  `exp_gf_title_lottery_percent` VARCHAR(255),
  `exp_total_k_12_percent` VARCHAR(255),
  `data_source_url` VARCHAR(255),
  `created_by` VARCHAR(255) DEFAULT 'Shahrukh Nawaz',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT,
  `touched_run_id` BIGINT,
  `deleted` BOOLEAN DEFAULT 0,
  `md5_hash` VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;