create table usa_raw.new_york_city_crime_statistics_weekly
(
    id                                                 int auto_increment   primary key,
    crime_category                                    varchar(255)                        null,
    year_1                                               varchar(255)                        null,
    year_2                                               varchar(255)                        null,
    report_start_date                                      date                                null,
    report_end_date                                      date                                null,
    week_to_date_year1                                                int                        null,
    week_to_date_year2                                                int                        null,
    year_to_date_year1                                                int                        null,
    year_to_date_year2                                                int                        null,
    last_28_days_year1                                                int                        null,
    last_28_days_year2                                                int                        null,
    scrape_frequency                                    varchar(255)  DEFAULT 'weekly',
    data_source_url  VARCHAR(255) DEFAULT 'https://www1.nyc.gov/site/nypd/stats/crime-statistics/citywide-crime-stats.page',
    created_by      VARCHAR(255)       DEFAULT 'Raza',
    created_at      DATETIME           DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);
