create table alabama_business_licenses_temp_temp(
  `id`                                      BIGINT(20),
  `entity_id`                               INT(11),
  `entity_name`                             VARCHAR(255),
  `entity_type`                             VARCHAR(255),
  `principal_address`                       VARCHAR (255),
  `principal_address_clean`                 VARCHAR(255),
  `principal_city_state_zip`                VARCHAR(255),
  `principal_city`                          VARCHAR(255),
  `principal_state`                         VARCHAR(255),
  `principal_zip`                           VARCHAR(15),
  `status`                                  VARCHAR(255),
  `formation_date`							            DATE,
  `withdrawn_date`                          DATE,
  `dissolved_date`                          DATE,
  `revoked_date`                            DATE,
  `merged_date`                             DATE,
  `merged_into`                             VARCHAR(255),
  `cancelled_date`                          DATE,
  `consolidated_date`                       DATE,
  `consolidated_to`                         DATE,
  `service_of_process_name`                 VARCHAR(255) ,
  `place_of_formation`                      VARCHAR(255),
  `qualify_date`                            DATE,
  `service_of_process_address`              VARCHAR(255),
  `service_of_process_city_state_zip`       VARCHAR(255),
  `registered_agent_name`                   VARCHAR(255),
  `resigned_date`                           DATE,
  `registered_office_address`				        VARCHAR(255),
  `registered_office_city`                  VARCHAR(255),
  `registered_office_zip`                   VARCHAR(15),
  `registered_office_state`                 VARCHAR(255),
  `registered_office_address_clean`			    VARCHAR(255),
  `nature_of_business`                      BIGINT(20),
  `capital_authorized`                      BIGINT(20),
  `capital_paid_in`                         VARCHAR(255),
  `data_source_url`                         VARCHAR(255) ,
  `created_by`                              VARCHAR(255) DEFAULT 'Mariam',
  `deleted`                                 BOOLEAN DEFAULT FALSE,
  `created_at`                              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_scrape_date`                        DATE,
  `next_scrape_date`                        DATE,
  `expected_scrape_frequency`               VARCHAR(255) DEFAULT 'Monthly',
  `scrape_status`                           VARCHAR(255) DEFAULT 'Live',
  `pl_gather_task_id`                       VARCHAR(255),
  `on_site`                                 TINYINT(1),
  `run_id`                                  INT,
  `touched_run_id`							            INT,
  `md5_hash`                                VARCHAR(255) GENERATED ALWAYS AS (md5(CONCAT_WS('', CAST(withdrawn_date as CHAR), CAST(dissolved_date as CHAR), CAST(merged_date as CHAR), CAST(revoked_date as CHAR), CAST(formation_date as CHAR), CAST(cancelled_date as CHAR), registered_office_state, registered_office_zip, registered_office_city, principal_state, principal_zip, principal_city, capital_authorized, capital_paid_in))) STORED UNIQUE KEY
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
