-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 16:15:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crime_inmate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crime_inmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crime_inmate` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `crime_inmate` ;

-- -----------------------------------------------------
-- Table `crime_inmate`.`ny_erie_inmates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crime_inmate`.`ny_erie_inmates` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `middle_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `data_source_url` TEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT 'Hatri',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `touched_run_id` BIGINT(20) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5` (`md5_hash` ASC) VISIBLE,
  INDEX `run_id` (`run_id` ASC) VISIBLE,
  INDEX `touched_run_id` (`touched_run_id` ASC) VISIBLE,
  INDEX `deleted` (`deleted` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2377
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `crime_inmate`.`ny_erie_inmate_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crime_inmate`.`ny_erie_inmate_ids` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `inmate_id` BIGINT(20) NULL DEFAULT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `data_source_url` TEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT 'Hatri',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `touched_run_id` BIGINT(20) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5` (`md5_hash` ASC) VISIBLE,
  INDEX `run_id` (`run_id` ASC) VISIBLE,
  INDEX `touched_run_id` (`touched_run_id` ASC) VISIBLE,
  INDEX `deleted` (`deleted` ASC) VISIBLE,
  INDEX `fk_il_tazewell__arrestee_ids_il_tazewell__arrestees1_idx` (`inmate_id` ASC) VISIBLE,
  CONSTRAINT `fk_il_tazewell__arrestee_ids_il_tazewell__arrestees1`
    FOREIGN KEY (`inmate_id`)
    REFERENCES `crime_inmate`.`ny_erie_inmates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2375
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `crime_inmate`.`ny_erie_arrests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crime_inmate`.`ny_erie_arrests` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `inmate_id` BIGINT(20) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `arrest_date` DATETIME NULL DEFAULT NULL,
  `booking_date` DATE NULL DEFAULT NULL,
  `data_source_url` TEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT 'Hatri',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `touched_run_id` BIGINT(20) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5` (`md5_hash` ASC) VISIBLE,
  INDEX `run_id` (`run_id` ASC) VISIBLE,
  INDEX `touched_run_id` (`touched_run_id` ASC) VISIBLE,
  INDEX `deleted` (`deleted` ASC) VISIBLE,
  INDEX `fk_il_tazewell__arrests_il_tazewell__arrestees_idx` (`inmate_id` ASC) VISIBLE,
  CONSTRAINT `fk_il_tazewell__arrests_il_tazewell__arrestees`
    FOREIGN KEY (`inmate_id`)
    REFERENCES `crime_inmate`.`ny_erie_inmates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1385
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `crime_inmate`.`ny_erie_holding_facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crime_inmate`.`ny_erie_holding_facilities` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `arrest_id` BIGINT(20) NULL DEFAULT NULL,
  `facility` VARCHAR(255) NULL DEFAULT NULL,
  `facility_type` VARCHAR(255) NULL DEFAULT NULL,
  `data_source_url` TEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT 'Hatri',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `touched_run_id` BIGINT(20) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5` (`md5_hash` ASC) VISIBLE,
  INDEX `run_id` (`run_id` ASC) VISIBLE,
  INDEX `touched_run_id` (`touched_run_id` ASC) VISIBLE,
  INDEX `deleted` (`deleted` ASC) VISIBLE,
  INDEX `fk_il_tazewell__holding_facilities_il_tazewell__arrests1_idx` (`arrest_id` ASC) VISIBLE,
  CONSTRAINT `fk_il_tazewell__holding_facilities_il_tazewell__arrests1`
    FOREIGN KEY (`arrest_id`)
    REFERENCES `crime_inmate`.`ny_erie_arrests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
