CREATE TABLE `va_general_info` (
  `id` bigint(20) AUTO_INCREMENT PRIMARY KEY,
  `is_district` tinyint(1) DEFAULT NULL,
  `district_id` bigint(20) DEFAULT NULL,
  `number` varchar(50) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `name_clean` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `low_grade` varchar(50) DEFAULT NULL,
  `high_grade` varchar(50) DEFAULT NULL,
  `charter` varchar(255) DEFAULT NULL,
  `magnet` varchar(50) DEFAULT NULL,
  `title_1_school` varchar(255) DEFAULT NULL,
  `title_1_school_wide` varchar(255) DEFAULT NULL,
  `nces_id` varchar(50) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `county` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `zip` varchar(50) DEFAULT NULL,
  `zip_4` varchar(50) DEFAULT NULL,
  `data_source_url` varchar(255) DEFAULT NULL,
  `pl_production_org_id` bigint(20) DEFAULT NULL,
  `pl_production_org_status` varchar(30) DEFAULT NULL,
  `pl_production_org_name` varchar(255) DEFAULT NULL,
  `pl_production_org_date` date DEFAULT NULL,
  `alias` varchar(255) DEFAULT NULL,
  
  `md5_hash` varchar(255),
  `run_id` int(11) DEFAULT NULL,
  `touched_run_id` int(11) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT 'Frank Rao',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)

) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

