 Create table colorado_voter_registrations(
 id bigint(20) NOT NULL AUTO_INCREMENT,
 run_id  bigint(20) NOT NULL,
 year VARCHAR (255),
 month VARCHAR (255),
 county VARCHAR (255),
 uaf_acn VARCHAR (255),
 uaf_apv VARCHAR (255),
 uaf_dem VARCHAR (255),
 uaf_grn VARCHAR (255),
 uaf_libl VARCHAR (255),
 uaf_rep VARCHAR (255),
 uaf_uni VARCHAR (255),
 uaf_total VARCHAR (255),
 md5_hash VARCHAR(255) GENERATED ALWAYS AS (md5(CONCAT_WS('', year, month, county, uaf_acn, uaf_apv, uaf_dem, uaf_grn, uaf_libl, uaf_rep, uaf_uni, uaf_total))) STORED,
 scrape_dev_name VARCHAR(255),
 scrape_frequency VARCHAR(255),
 data_source_url varchar(255),
 last_scrape_date date,
 next_scrape_date date,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 expected_scrape_frequency VARCHAR(255),
 scrape_status VARCHAR(255),
 dataset_name_prefix VARCHAR(255),
 pl_gather_task_id int,
 PRIMARY KEY (id)
 );
