CREATE Table ihsa_schools__info(
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    short_name VARCHAR(255),
    year int,
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip VARCHAR(255),
    phone VARCHAR(255),
    fax VARCHAR(255),
    website VARCHAR(255),
    enrollment VARCHAR(255),
    conference VARCHAR(255),
    nicknames VARCHAR(255),
    colors VARCHAR(255),
    school_type VARCHAR(255),
    county VARCHAR(255),
    cities_in_district VARCHAR(255),
    board_division VARCHAR(255),
    legislative_division VARCHAR(255),
    data_source_url TEXT,
    created_by      VARCHAR(255)      DEFAULT 'Abdur Rehman',
    created_at      DATETIME          DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    run_id   BIGINT(20),
    touched_run_id  BIGINT,
    deleted         BOOLEAN           DEFAULT 0,
    md5_hash        VARCHAR(255),
    UNIQUE KEY md5 (md5_hash)
);