CREATE TABLE `oh_general_info`
(
  `id`                  BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`              BIGINT(20),
  `is_district`         TINYINT(1),
  `district_id`         BIGINT(20),
  `number`              VARCHAR(20),
  `name`                VARCHAR(255),
  `type`                VARCHAR(255),
  `low_grade`           VARCHAR(20),
  `high_grade`          VARCHAR(20),
  `charter`             VARCHAR(20),
  `magnet`              VARCHAR(20),
  `title_1_school`      VARCHAR(20),
  `title_1_school_wide` VARCHAR(20),
  `nces_id`             VARCHAR(50),
  `phone`               VARCHAR(100),
  `county`              VARCHAR(255),
  `address`             VARCHAR(255),
  `city`                VARCHAR(255),
  `state`               VARCHAR(20),
  `zip`                 VARCHAR(20),
  `zip_4`               VARCHAR(20),
  `data_source_url` VARCHAR(255),
  `created_by`      VARCHAR(255)      DEFAULT 'agegic',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_enrollment`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(255),
  `subgroup`         VARCHAR(255),
  `grade`            VARCHAR(255),
  `count`            VARCHAR(255),
  `data_source_url`  VARCHAR(255),
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_performance`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(255),
  `indicator`        VARCHAR(255),
  `percent`          VARCHAR(255),
  `data_source_url`  VARCHAR(255),
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_graduation`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       bigint(20),
  `school_year`      VARCHAR(50),
  `criteria_group`   VARCHAR(255),
  `subgroup`         VARCHAR(255),
  `numerator`        VARCHAR(50),
  `denominator`      VARCHAR(50),
  `graduation_rate`  VARCHAR(50),
  `data_source_url`  VARCHAR(255),
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_gifted`
(
  `id`                         BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                     BIGINT(20),
  `general_id`                 BIGINT(20),
  `school_year`                VARCHAR(50),
  `criteria_group`             VARCHAR(50),
  `not_identified`             VARCHAR(50),
  `ident_served`               VARCHAR(50),
  `ident_not_served`           VARCHAR(50),
  `identified`                 VARCHAR(50),
  `served`                     VARCHAR(50),
  `enrollment`                 VARCHAR(50),
  `performance_idx`            VARCHAR(50),
  `data_source_url`            VARCHAR(255),
  `created_by`                 VARCHAR(255)   DEFAULT 'agegic',
  `created_at`                 DATETIME       DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`             BIGINT,
  `deleted`                    BOOLEAN        DEFAULT 0,
  `md5_hash`                   VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_attendance`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(255),
  `subgroup`         VARCHAR(255),
  `rate`             VARCHAR(255),
  `data_source_url`  VARCHAR(255),
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_educators`
(
  `id`               BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`           BIGINT(20),
  `general_id`       BIGINT(20),
  `school_year`      VARCHAR(255),
  `measure`          VARCHAR(255),
  `value_type`       VARCHAR(50),
  `number`           VARCHAR(50),
  `percent`          VARCHAR(50),
  `data_source_url`  VARCHAR(255),
  `created_by`       VARCHAR(255)      DEFAULT 'agegic',
  `created_at`       DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`   BIGINT,
  `deleted`          BOOLEAN           DEFAULT 0,
  `md5_hash`         VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `oh_expenditures`
(
  `id`                         BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                     BIGINT(20),
  `general_id`                 BIGINT(20),
  `school_year`                VARCHAR(50),
  `weighted_adm`               VARCHAR(50),
  `operating_total`            VARCHAR(50),
  `expend_per_equival_pupil`   VARCHAR(50),
  `cri`                        VARCHAR(50),
  `ncr`                        VARCHAR(50),
  `cri_epep`                   VARCHAR(50),
  `ncr_epep`                   VARCHAR(50),
  `cri_pct`                    VARCHAR(50),
  `group_cri_pct_rank`         VARCHAR(50),
  `overall_cri_pct_rank`       VARCHAR(50),
  `overall_epep_rank`          VARCHAR(50),
  `operating_revenue`          VARCHAR(50),
  `federal`                    VARCHAR(50),
  `state`                      VARCHAR(50),
  `local`                      VARCHAR(50),
  `other_non_tax`              VARCHAR(50),
  `lowest_20_pct_epep`         VARCHAR(50),
  `highest_20_pct_pi`          VARCHAR(50),
  `data_source_url`            VARCHAR(255),
  `created_by`                 VARCHAR(255)   DEFAULT 'ageic',
  `created_at`                 DATETIME       DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`             BIGINT,
  `deleted`                    BOOLEAN        DEFAULT 0,
  `md5_hash`                   VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;
