CREATE TABLE `connecticut_professional_licensing_tmp`
(
    `id`                        BIGINT(20)         AUTO_INCREMENT PRIMARY KEY,
    `credential_id`             BIGINT(20)         DEFAULT NULL,
    `name`                      VARCHAR(255)       DEFAULT NULL,
    `type`                      VARCHAR(255)       DEFAULT NULL,
    `business_name`             VARCHAR(255)       DEFAULT NULL,
    `dba`                       VARCHAR(255)       DEFAULT NULL,
    `full_credential_code`      VARCHAR(255)       DEFAULT NULL,
    `credential_type`           VARCHAR(255)       DEFAULT NULL,
    `credential_number`         VARCHAR(255)       DEFAULT NULL,
    `credential_sub_category`   VARCHAR(255)       DEFAULT NULL,
    `credential`                VARCHAR(255)       DEFAULT NULL,
    `status`                    VARCHAR(255)       DEFAULT NULL,
    `status_reason`             VARCHAR(255)       DEFAULT NULL,
    `active`                    VARCHAR(255)       DEFAULT NULL,
    `issue_date`                DATE               DEFAULT NULL,
    `effective_date`            DATE               DEFAULT NULL,
    `expiration_date`           DATE               DEFAULT NULL,
    `address`                   VARCHAR(255)       DEFAULT NULL,
    `city`                      VARCHAR(255)       DEFAULT NULL,
    `state`                     VARCHAR(255)       DEFAULT NULL,
    `zip`                       VARCHAR(255)       DEFAULT NULL,
    `record_refreshed_on`       DATE               DEFAULT NULL,
    `data_source_url`           TEXT,
    `created_by`                VARCHAR(255),
    `created_at`                DATETIME           DEFAULT CURRENT_TIMESTAMP,
    `updated_at`                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `md5_hash_sql`              VARCHAR(55),
    `scrape_frequency`          VARCHAR(255)       DEFAULT NULL,
    `last_scrape_date`          DATE               DEFAULT NULL,
    `next_scrape_date`          DATE               DEFAULT NULL,
    `expected_scrape_frequency` VARCHAR(255)       DEFAULT NULL,
    `dataset_name_prefix`       VARCHAR(255)       DEFAULT NULL,
    `scrape_status`             VARCHAR(255)       DEFAULT NULL,
    INDEX `md5_hash_sql__index` (`md5_hash_sql`),
    INDEX `credential_id__index` (`credential_id`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
