CREATE TABLE `counts_of_death_by_cause_week_state`
(
  `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`          BIGINT(20),
  `data_as_of` DATE,
  `jurisdiction_of_occurrence` VARCHAR(255),
  `mm_wr_year` VARCHAR(255),
  `mm_wr_week` VARCHAR(255),
  `week_ending_date`      VARCHAR(255),
  `all_cause`          int,
  `natural_cause`      int,
  `septicemia_a40_a41`  int,
  `malignant_neoplasms_c00_c97`   int,
  `diabetes_mellitus_e10_e14`      int,
  `alzheimer_disease_g30`         int, 
  `influenza_and_pneumonia_j09_j18`  int,
  `chronic_lower_respiratory`     int,
  `other_diseases_of_respiratory` int,
  `nephritis_nephrotic_syndrome`  int,
  `symptoms_signs_and_abnormal`   int,
  `diseases_of_heart_i00_i09`     int,
  `cerebrovascular_diseases`      int,
  `covid_19_u071_multiple_cause_of_death` int,
  `covid_19_u071_underlying_cause_of_death` int, 
  `data_source_url` TEXT,
  `created_by`      VARCHAR(255)      DEFAULT 'Abdur Rehman',
  `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`  BIGINT,
  `deleted`         BOOLEAN           DEFAULT 0,
  `md5_hash`        VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`),
  KEY `id` (`id`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
