CREATE TABLE IF NOT EXISTS `tx_general_assembly_senate_committees`(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` INT DEFAULT NULL,
  `year`   VARCHAR(255),
  `committee` VARCHAR(255),
  `committee_code` varchar(255),
  `legislature` VARCHAR(255),
  `appointment_date` date,
  `clerk` VARCHAR(255),
  `phone` VARCHAR(255),
  `room` VARCHAR(255),
  `md5_hash` varchar(255),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_dev_name` varchar(255) DEFAULT "Adeel",
  `scrape_frequency` varchar(255) Default "Daily",
  `scrape_status` VARCHAR(255) DEFAULT "Live",
  `pl_gather_task_id` bigint(20) DEFAULT 177970811,
  `data_source_url` varchar(255),
  `touched_run_id` int DEFAULT NULL,
  `deleted` INT(1) default 0,
  PRIMARY KEY (`id`),
UNIQUE KEY `unique_records` (`md5_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=1010341 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
