CREATE TABLE IF NOT EXISTS `tx_general_assembly_bills`(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` INT DEFAULT NULL,
  `bill_number` VARCHAR(255),
  `legislative_session` VARCHAR(255),
  `year` VARCHAR(255),
  `last_action` date,
  `effecive_date` date,
  `caption_version` VARCHAR(255),
  `caption_text` text,
  `author` text,
  `sponsor` VARCHAR(255),
  `subject` text,
  `house_committee` VARCHAR(255),
  `house_committee_link` varchar(255),
  `house_committee_id` bigint(20) DEFAULT NULL,
  `house_status` VARCHAR(255),
  `house_yes_votes` int,
  `house_no_votes` int,
  `house_present_not_voting` int,
  `house_absent` int,
  `senate_committee` VARCHAR(255),
  `senate_committee_link` varchar(255),
  `senate_committee_id` bigint(20) DEFAULT NULL,
  `senate_status` VARCHAR(255),
  `senate_yes_votes` int,
  `senate_no_votes` int,
  `senate_present_not_voting` int,
  `senate_absent` int,
  `md5_hash` varchar(100),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_dev_name` varchar(255) DEFAULT "Adeel",
  `scrape_frequency` varchar(255) DEFAULT "Daily",
  `scrape_status` VARCHAR(255) DEFAULT "Live",
  `pl_gather_task_id` bigint(20) DEFAULT 177970811,
  `data_source_url` varchar(255),
   `deleted` int(1) default 0,
  PRIMARY KEY (`id`),
UNIQUE KEY `unique_records` (`md5_hash`),
FOREIGN KEY (`house_committee_id`) REFERENCES `tx_general_assembly_house_committees_temp`(`id`),
FOREIGN KEY (`senate_committee_id`) REFERENCES `tx_general_assembly_senate_committees_temp`(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1010341 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
