CREATE TABLE IF NOT EXISTS `tx_general_assembly_bill_actions`(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` INT DEFAULT NULL,
  `bill_number` VARCHAR(255),
  `legislative_session` VARCHAR(255),
  `year` VARCHAR(255),
  `description` varchar(255),
  `comment` VARCHAR(255),
  `date` date,
  `time` time,
  `journal_page` int,
  `md5_hash` varchar(100),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_dev_name` varchar(255) DEFAULT "Adeel",
  `scrape_frequency` varchar(255) DEFAULT "Daily",
  `scrape_status` VARCHAR(255) DEFAULT "Live",
  `pl_gather_task_id` bigint(20) DEFAULT 177970811,
  `data_source_url` varchar(255),
  `touched_run_id` INT DEFAULT NULL,
   `deleted` int(1) default 0,
  PRIMARY KEY (`id`),
UNIQUE KEY `unique_records` (`md5_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=1010341 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
