use us_court_cases;
truncate sc_saac_case_additional_info;
truncate sc_saac_case_activities;
truncate sc_saac_case_info;
truncate sc_saac_case_party;
truncate sc_saac_case_pdfs_on_aws;
truncate sc_saac_case_relations_activity_pdf;
truncate sc_saac_case_runs;