CREATE TABLE IF NOT EXISTS `usa_raw`.`va_home_loan_by_state` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`run_id` int(11) DEFAULT NULL,
`year` varchar(255),
`quarter_no` varchar(255),
`state_code` varchar(255),
`total_loans` int,
`avg_loan_amount` int,
`loan_amount_sum` bigint(20),
`total_purchase_loans` int,
`total_purchase_loans_percent` decimal(5,2),
`loan_amount_avg_purchase` int,
`total_loan_amount_purchase` bigint(20),
`total_irrl_loans` int,
`total_irrl_loans_percent` decimal(5,2),
`loan_amount_avg_irrl` int,
`total_loan_amount_irrl` bigint(20),
`total_cash_out_loans` int,
`total_cash_out_percent` decimal(5,2),
`loan_amount_avg_cash_out` int,
`total_loan_amount_cash_out` bigint(20),
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`data_source_url` varchar(255),
`scrape_dev_name` varchar(255),
`scrape_frequency` varchar(255) DEFAULT "Quarterly",
`created_by` varchar(255) DEFAULT 'Adeel',
`touched_run_id` int(11) DEFAULT NULL,
`md5_hash` varchar(100) GENERATED ALWAYS AS (md5(concat_ws('',`year`, `quarter_no`,`state_code`,cast(`total_loans` as char),cast(`avg_loan_amount` as char),cast(`loan_amount_sum` as char),cast(`total_purchase_loans` as char), cast(`total_purchase_loans_percent` as char), cast(`loan_amount_avg_purchase` as char), cast(`total_loan_amount_purchase` as char), cast(`total_irrl_loans` as char), cast(`total_irrl_loans_percent` as char), cast(`loan_amount_avg_irrl` as char), cast(`total_loan_amount_irrl` as char), cast(`total_cash_out_loans` as char), cast(`total_cash_out_percent` as char), cast(`loan_amount_avg_cash_out` as char), cast(`total_loan_amount_cash_out` as char)))) STORED,
`deleted` int(11) DEFAULT '0',
PRIMARY KEY (`id`),
UNIQUE INDEX `unique_records` (`md5_hash`),
INDEX `run_id_index` (`run_id`),
INDEX `created_at_idx` (`created_at`)
)DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
COMMENT = 'Created by Muhammad Adeel Anwar, Task #430';
