create table usa_raw.election_coverage__2022__candidates
(
    id                                       bigint auto_increment primary key,
    candidate_id                             int                                                                                                                            null,
    race_id                                  int                                                                                                                            null,
    race                                     varchar(255)                                                                                                                   null,
    state                                    varchar(31)                                                                                                                    null,
    year_candidates                          year                                                                                                                           null,
    candidate_full_name                      varchar(255)                                                                                                                   null,
    candidate_first_name                     varchar(255)                                                                                                                   null,
    candidate_middle_name                    varchar(255)                                                                                                                   null,
    candidate_last_name                      varchar(255)                                                                                                                   null,
    candidate_suffix                         varchar(255)                                                                                                                   null,
    party                                    varchar(255)                                                                                                                   null,
    hometown                                 varchar(255)                                                                                                                   null,
    hometown_state                           varchar(255)                                                                                                                   null,
    campaign_official_website                varchar(255)                                                                                                                   null,
    campaign_committee_name                  varchar(255)                                                                                                                   null,
    campaign_twitter                         varchar(1023)                                                                                                                  null,
    news_page_url                            varchar(255)                                                                                                                   null,
    press_release_rss_feed                   varchar(255)                                                                                                                   null,
    twitter_handle                           varchar(1023)                                                                                                                  null,
    candidate_photo                          varchar(255)                                                                                                                   null,
    filing_date                              date                                                                                                                           null,
    incumbent                                tinyint(1)                                                                                                                     null,
    incumbent_since_year                     year                                                                                                                           null,
    most_recent_election_year                year                                                                                                                           null,
    most_recent_election_number_of_votes     int                                                                                                                            null,
    most_recent_election_percentage_of_votes float                                                                                                                          null,
    most_recent_election_main_opponent       varchar(255)                                                                                                                   null,
    previous_election_1_year                 year                                                                                                                            null,
    previous_election_1_number_of_votes      int                                                                                                                            null,
    previous_election_1_percentage_of_votes  float                                                                                                                          null,
    previous_election_1_main_opponent        varchar(255)                                                                                                                   null,
    previous_election_2_year                 year                                                                                                                           null,
    previous_election_2_number_of_votes      int                                                                                                                            null,
    previous_election_2_percentage_of_votes  float                                                                                                                          null,
    previous_election_2_main_opponent        varchar(255)                                                                                                                   null,
    previous_election_3_year                 year                                                                                                                           null,
    previous_election_3_number_of_votes      int                                                                                                                            null,
    previous_election_3_percentage_of_votes  float                                                                                                                          null,
    previous_election_3_main_opponent        varchar(255)                                                                                                                   null,
    previous_election_4_year                 year                                                                                                                           null,
    previous_election_4_number_of_votes      int                                                                                                                            null,
    previous_election_4_percentage_of_votes  float                                                                                                                          null,
    previous_election_4_main_opponent        varchar(255)                                                                                                                   null,
    notes                                    varchar(255)                                                                                                                   null,
    gatherer_id                              int                                                                                                                            null,
    date_gathered                            date                                                                                                                           null,
    submitted                                tinyint(1)                                                                                                                          null,
    done                                     int                                                                                                                            null,
    candidate_photo_aws                      varchar(255)                                                                                                                   null,
    scrape_frequency                         varchar(31)  default 'once'                                                                                                    null,
    data_source_url                          varchar(255) default 'https://docs.google.com/spreadsheets/d/1Utl77CEMYb7uO0TCsbPyA9mKdrpFNRmmjW1mQWErnWc/edit#gid=1437065541' null,
    created_by                               varchar(255) default 'Eldar Eminov'                                                                                            null,
    created_at                               datetime     default CURRENT_TIMESTAMP                                                                                         null,
    updated_at                               timestamp    default CURRENT_TIMESTAMP                                                                                         null on update CURRENT_TIMESTAMP
)
    DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci;