CREATE TABLE `university_of_pittsburgh_directory`(
`id` bigint(20) NOT NULL AUTO_INCREMENT primary key,
`vcard_index` varchar(255),
`year` varchar(255),
`last_name` varchar(255),
`first_name` varchar(255),
`middle_name` varchar(255),
`full_name` varchar(255),
`nickname` varchar(255),
`employee_type` varchar(255),
`employee_department` varchar(255),
`email` varchar(255) ,
`office_phone` varchar(255) ,
`office_mailing_address` varchar(255) ,
`student_campus` varchar(255) ,
`student_plans` varchar(255) ,
`web_page` varchar(255) ,
`student_schools` varchar(255) ,
`employee_information` varchar(255) ,
`position` varchar(255) ,
`data_source_url` varchar(255) default "https://find.pitt.edu/",
`search_params` varchar(255) ,
`scrape_dev_name` varchar(255)  default "Asim Saeed",
`created_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`last_scrape_date` date ,
`next_scrape_date` date ,
`mobile_number` varchar(255),
`run_id`                 int,
`deleted`         boolean default '0',
`md5_hash`       varchar(255) GENERATED ALWAYS AS (md5(CONCAT_WS('', vcard_index, full_name, employee_type, employee_department,  employee_information, email, office_mailing_address,  student_campus, student_plans))) STORED UNIQUE KEY,
`scrape_frequency` varchar(255) DEFAULT "Daily",
`expected_scrape_frequency` varchar(255) DEFAULT "Daily",
`dataset_name_prefix` varchar(255) default "university_of_pittsburgh_directory",
`scrape_status` varchar(255) default "live",
`pl_gather_task_id` varchar(255),
UNIQUE KEY `unique_data` (`md5_hash`),
INDEX vcard_index_idx (`vcard_index`),
INDEX run_id_idx (`run_id`),
INDEX deleted_idx (`deleted`)
)DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci COMMENT = 'Created by Asim Saeed, Task #0285';
