CREATE TABLE `us_fsa_subsidies` (
  `id` BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id` BIGINT(20),
  `state_fsa_code` VARCHAR(50),
  `state_fsa_name` VARCHAR(255),
  `county_fsa_code` VARCHAR(50),
  `county_fsa_name` VARCHAR(255),
  `formatted_payee_name` VARCHAR(255),
  `information_address` VARCHAR(255),
  `delivery_address` VARCHAR(255),
  `city` VARCHAR(255),
  `state` VARCHAR(50),
  `zip` VARCHAR(50),
  `delivery_point_bar_code` VARCHAR(255),
  `disbursement_amount` FLOAT,
  `payment_date` DATE,
  `accounting_program_code` VARCHAR(50),
  `accounting_program_desc` VARCHAR(255),
  `accounting_program_year` INT,
  `data_source_url` TEXT,
  `created_by` VARCHAR(255) DEFAULT 'Shahrukh Nawaz',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id` BIGINT,
  `deleted` BOOLEAN DEFAULT 0,
  `md5_hash` VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Shahrukh Nawaz';