CREATE TABLE `california_voter_registrations`
(
  `id`                   BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`               BIGINT(20),
  `link`                 VARCHAR (255),
  `month`                VARCHAR (255),
  `day`                  VARCHAR (255),
  `year`                 VARCHAR (255),
  `county`              VARCHAR (255),
  `eligible`             VARCHAR (255),
  `total_registered`     VARCHAR (255),
  `democratic`           VARCHAR (255),
  `republican`           VARCHAR (255),
  `american_independent` VARCHAR (255),
  `green`                VARCHAR (255),
  `libertarian`          VARCHAR (255),
  `peace_and_freedom`    VARCHAR (255),
  `unknown`              VARCHAR (255),
  `other`                VARCHAR (255),
  `no_party_preference`  VARCHAR (255),
  `scrape_dev_name`           VARCHAR(255)      DEFAULT 'Adeel',
  `data_source_url`      VARCHAR(255) DEFAULT 'https://www.sos.ca.gov/elections/voter-registration/voter-registration-statistics',
  `created_at`           DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_frequency`     VARCHAR(255) DEFAULT 'monthly',
  `last_scrape_date`     Date,
  `next_scrape_date`     Date,
  `expected_scrape_frequency`     VARCHAR(255) DEFAULT 'monthly',
  `dataset_name_prefix`  varchar(255) DEFAULT 'california_voter_registrations',
  `scrape_status`        varchar(255) DEFAULT 'Live',
  `md5_hash`             varchar(100) GENERATED ALWAYS AS (md5(CONCAT_WS('', month, day,year, county, eligible, total_registered, democratic, republican, american_independent, green, libertarian, peace_and_freedom, unknown, other, no_party_preference))) STORED,
  UNIQUE KEY `md5` (`md5_hash`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
