use lawyer_status;
drop table `ms_mississippi_bar`;
CREATE TABLE `ms_mississippi_bar`
(
    `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    `run_id`              BIGINT,
    `bar_number`                    VARCHAR(255),
    `full_name`                          VARCHAR(255),
    `first_name`                  VARCHAR(255),
    `last_name`                       VARCHAR(255),
    `middle_name`                 VARCHAR(255),
    `date_admited`		    DATETIME,
    `registration_status`    VARCHAR(255),
    `sections`		          TEXT,
    `type`                   VARCHAR(255),
    `phone`                   VARCHAR(255),
    `email`                   VARCHAR(255),
    `fax`                   VARCHAR(255),
    `law_firm_name`         VARCHAR(255),
    `law_firm_address`      VARCHAR(255),
    `law_firm_address1`      VARCHAR(255),
    `law_firm_address2`      VARCHAR(255),
    `law_firm_zip`          VARCHAR(255),
    `law_firm_city`          VARCHAR(255),
    `law_firm_state`         VARCHAR(255),
    `law_firm_county`         VARCHAR(255),
    `name_prefix`           VARCHAR(255),
    `university`             VARCHAR(255),
    `professional_affiliation`		  TEXT,
    `bio`		        LONGTEXT,
    `website`             VARCHAR(255),
    `linkedin`             VARCHAR(255),
    `facebook`             VARCHAR(255),
    `twitter`             VARCHAR(255),
    `law_firm_website`             VARCHAR(255),
    `other_jurisdictions`		          TEXT,
    `judicial_district`             VARCHAR(255),
    `disciplinary_actions`		          TEXT,
    `private_practice`             VARCHAR(255),
    `insurance`             VARCHAR(255),
    `courts_of_admittance`             VARCHAR(255),
    `touched_run_id`        bigint                                 null,
    `deleted`               tinyint(1)   default 0                 null,
    `md5_hash`              varchar(255)                           null,
    `scrape_frequency`             VARCHAR(255) DEFAULT 'weekly',
    `data_source_url` VARCHAR(255),
    `created_by`      VARCHAR(255)      DEFAULT 'Pospelov Vyacheslav',
    `created_at`      DATETIME          DEFAULT CURRENT_TIMESTAMP,
    `updated_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `run_id` (`run_id`),
    INDEX `created_by` (`created_by`),
    INDEX `updated_at` (`updated_at`),
    INDEX `touched_run_id` (`touched_run_id`),
    INDEX `first_name` (`first_name`),
    INDEX `last_name` (`last_name`),
    INDEX `middle_name` (`middle_name`),
    INDEX `law_firm_city` (`law_firm_city`),
    INDEX `law_firm_state` (`law_firm_state`),
    INDEX `full_name` (`full_name`),
    UNIQUE KEY `md5_hash` (`md5_hash`)
)
    COMMENT = 'Mississippi Bar(attorney data)'
    DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci;

