CREATE TABLE `la_campaign_candidates` 
(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `candidate_name` VARCHAR(2048),
  `candidate_complete_address` VARCHAR(1024),
  `candidate_city` VARCHAR(256),
  `candidate_state` VARCHAR(256),
  `candidate_zip` VARCHAR(64),
  `candidate_office_sought` VARCHAR(255),
  `filing_date` DATE,
  `report_number` VARCHAR(255),
  `candidate_financial_institution_name` VARCHAR(255),
  `candidate_financial_institution_address` VARCHAR(255),
  `candidate_treasurer_name` VARCHAR(255),
  `candidate_treasurer_address` VARCHAR(255),
  `report_preparing_person_name` VARCHAR(255),
  `daytime_telephone` VARCHAR(255),
  `candidate_election_date` DATE,
  `report_link` VARCHAR(255),
  `created_by` varchar(255) DEFAULT 'Hassan',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` bigint(20) DEFAULT NULL,
  `touched_run_id` bigint(20) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  `data_source_url` varchar(255) DEFAULT NULL,
  `scrape_frequency` varchar(255) DEFAULT 'daily',
  `md5_hash` varchar(150),
  PRIMARY KEY (`id`),
  UNIQUE KEY `md5_hash` (`md5_hash`),
  KEY `run_id` (`run_id`),
  KEY `touched_run_id` (`touched_run_id`),
  KEY `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
