create table `oh_supremecourt_attorneys`
(
  `id`                        int auto_increment   primary key,
  `run_id`                    int,
  `md5_hash`                  varchar (255),
  `bar_number`                varchar (255),
  `name`                      varchar (255),
  `first_name`                varchar (255),
  `last_name`                 varchar (255),
  `middle_name`               varchar (255),
  `date_admited`              date,
  `registration_status`       varchar (255),
  `sections`                  text,
  `type`                      varchar (255),
  `phone`                     varchar (255) DEFAULT NULL,
  `email`                     varchar(255),
  `fax`                       varchar (255),
  `law_firm_name`             varchar (255)   DEFAULT NULL,
  `law_firm_address`          varchar (255),
  `law_firm_zip`              varchar (255),
  `law_firm_city`             varchar (255),
  `law_firm_state`            varchar (255),
  `law_firm_county`           varchar (255),
  `name_prefix`               varchar (255),
  `law_school`                varchar (255),
  `job_title`                 varchar (255),
  `admitted_by`               varchar (255),
  `discipline_history`        varchar (255),
  `administrative_sanctions`  varchar (255),
  `professional_affilitaion`  text,
  `bio`                       longtext,
  `website`                   varchar (255),
  `linkedin`                  varchar (255),
  `facebook`                  varchar (255),
  `twitter`                   varchar (255),
  `law_firm_website`          varchar (255),
  `other_jurisdictions`       text,
  `judicial_district`         varchar (255),
  `disciplinary_actions`      text,
  `private_practice`          varchar (255),
  `insurance`                 varchar (255),
  `courts_of_admittance`      varchar (255),
  `scrape_frequency`          varchar (255),
  `data_source_url`           varchar (255),
  `deleted`                BOOLEAN    DEFAULT 0,
  `created_by`                varchar (255)   DEFAULT 'Tauseeq',    
  `created_at`                DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_data` (`md5_hash`)
  )DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
