create table `minnesota_campaign_finance_committees` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `data_source_url` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registered_entity_id` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `year` varchar(5) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `role_type` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `formatted_name` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `address1` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `address2` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `city` varchar(80) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `state` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `zip_code` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `phone_number` varchar(15) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `email_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `web_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `first_registered_date` date DEFAULT NULL,
  `registered_entity_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `role_sort_order` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_role_type` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_master_name_id` varchar(15) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_formatted_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_address1` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_address2` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_city` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_state` varchar(25) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_zip_code` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_phone_number` varchar(25) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_email_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_web_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_committee_type` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_first_registered_date` date DEFAULT NULL,
  `chair_registered_entity_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `chair_role_sort_order` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_role_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_master_name_id` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_formatted_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_address1` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_address2` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_city` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_state` varchar(25) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_zip_code` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_phone_number` varchar(15) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_email_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_web_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_committee_type` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_first_registered_date` date DEFAULT NULL,
  `treasurer_registered_entity_type` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `treasurer_role_sort_order` varchar(155) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_role_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_formatted_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_address1` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_address2` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_city` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_state` varchar(25) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_zip_code` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_phone_number` varchar(25) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_email_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_web_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_committee_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_first_registered_date` date DEFAULT NULL,
  `depository_registered_entity_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `depository_role_sort_order` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_role_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_formatted_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_address1` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_address2` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_city` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_state` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_zip_code` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_phone_number` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_email_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_web_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_committee_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_first_registered_date` date DEFAULT NULL,
  `deputy_treasurer_registered_entity_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deputy_treasurer_role_sort_order` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_scrape_date` date DEFAULT NULL,
  `next_scrape_date` date DEFAULT NULL,
  `expected_scrape_frequency` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `dataset_name_prefix` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `scrape_status` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pl_production_org_id` int(1) DEFAULT NULL,
  `committee_name_clean` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_name_new_clean` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deleted`         BOOLEAN           DEFAULT 0,
  `touched_run_id` INT NULL,
  `md5_hash` VARCHAR(100),
  UNIQUE KEY `md5` (`md5_hash`),
  KEY `deleted` (`deleted`),
  KEY `run_id` (`run_id`),
  KEY `touched_run_id` (`touched_run_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;
