CREATE TABLE `minnesota_campaign_finance_tmp_contributions` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `data_source_url` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `filer` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `filing_year` int(11) DEFAULT NULL,
  `candidate_first_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_last_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_party` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_jurisdiction` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `site_source_candidate_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_name` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `committee_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_sub_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_party` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registered_entity_id` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `source_candidate_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributor_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributor_reg_ent_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributor_full_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributors_first_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributors_last_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributor_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `zip` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pac_affiliation` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `occupation` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `employer` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `received_date` date NOT NULL DEFAULT '0000-01-01',
  `contribution_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cash_amount` decimal(15,2) NOT NULL,
  `in_kind_amount` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `in_kind_description` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `employer_master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contributor_employer_full_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `md5_hash` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
