create table `minnesota_campaign_finance_candidates`(
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `data_source_url` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registered_entity_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `committee_full_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `committee_street_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `committee_city_state_zip` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `candidate_full_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `candidate_street_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `candidate_city_state_zip` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT "",
  `party_affiliation` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `election_cycle_start_date` date DEFAULT NULL,
  `election_cycle_end_date` date DEFAULT NULL,
  `election_year` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `office_sought_full_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `incumbent` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `public_subsidy_date` date DEFAULT NULL,
  `affidavit_of_candidacy_date` date DEFAULT NULL,
  `public_subsidy_amount` decimal(15,2) DEFAULT NULL,
  `affidavit_of_contribution_date` date DEFAULT NULL,
  `primary_election_winner` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `general_election_winner` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `district` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `affidavit_of_contribution` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `public_subsidy` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `public_subsidy_qualified` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `affidavit_of_candidacy` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `has_primary` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `unopposed_candidate` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `first_time_candidate` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `spend_limit_waived` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `economic_interest_filed` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `economic_interest_filed_date` date DEFAULT NULL,
  `camp_exp_limit` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `office_district_description` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `office_district_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `office_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `district_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `termination_date` date DEFAULT NULL,
  `special_election_indicator` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registered_entity_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `affidavit_year` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `ltgc_master_name_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `ltgc_formatted_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `office_sought` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `public_subsidy_estimate` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `contested_primary` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `deleted_at` date DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_scrape_date` date DEFAULT NULL,
  `next_scrape_date` date DEFAULT NULL,
  `expected_scrape_frequency` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `dataset_name_prefix` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `scrape_status` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `candidate_name_clean` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `touched_run_id` INT NULL,
  `deleted` INT NULL,
  `cleaned_manually` tinyint(1) DEFAULT '0',
  `md5_hash` VARCHAR(100),
  UNIQUE KEY `md5` (`md5_hash`),
  KEY `run_id` (`run_id`),
  KEY `deleted` (`deleted`),
  KEY `touched_run_id` (`touched_run_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci;
