FROM hamster:v%VERSION% AS repo

USER hamster:1001
WORKDIR /home/hamster/Hamster

RUN mkdir -p projects/%PROJECT%/
COPY projects/%PROJECT% projects/%PROJECT%/
CMD /bin/sh -lc "ruby hamster.rb --grab=%OPTIONS%"

