create table `wirepoints`
(
  `id`  int auto_increment   primary key,
  `run_id`  int,
  `district`                            varchar (255)   DEFAULT NULL,
  `pct_read_proficiency_all_students`   varchar (10)    DEFAULT NULL,
  `pct_math_proficiency_all_students`   varchar (10)    DEFAULT NULL,
  `pct_student_proficiency_white`       varchar (10)    DEFAULT NULL,
  `pct_student_proficiency_hispanic`    varchar (10)    DEFAULT NULL,
  `pct_student_proficiency_black`       varchar (10)    DEFAULT NULL,
  `pct_student_proficiency_asian`       varchar (10)    DEFAULT NULL,
  `pct_teachers_rating`                 varchar (10)    DEFAULT NULL,
  `pct_graduation_rating`               varchar (10)    DEFAULT NULL,
  `pct_graduation_read_proficiency_rating`       varchar (10)    DEFAULT NULL,
  `pct_grade_3rd_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_grade_4th_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_grade_5th_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_grade_6th_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_grade_7th_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_grade_8th_reading_proficiency`   varchar (10)    DEFAULT NULL,
  `pct_property_tax_2010_vs_2021`       varchar (10)    DEFAULT NULL,
  `pct_student_enrollment_2010_vs_2021`       varchar (10)    DEFAULT NULL,
  `pct_median_home_value_2010_vs_2021`        varchar (10)    DEFAULT NULL,
  `pct_spending_student_2010_vs_2021`   varchar (10)    DEFAULT NULL,
  `spending_per_student_2010`           varchar (10)    DEFAULT NULL,
  `spending_per_student_2021`           varchar (10)    DEFAULT NULL,
  `spending_per_student_illinois_2020`        varchar (10)    DEFAULT NULL,
  `spending_per_student_michigan_2020`        varchar (10)    DEFAULT NULL,
  `spending_per_student_wisconsin_2020`       varchar (10)    DEFAULT NULL,
  `spending_per_student_iowa_2020`            varchar (10)    DEFAULT NULL,
  `spending_per_student_kentucky_2020`        varchar (10)    DEFAULT NULL,
  `spending_per_student_missouri_2020`        varchar (10)    DEFAULT NULL,
  `spending_per_student_indiana_2020`         varchar (10)    DEFAULT NULL,
  `data_source_url`                     varchar (350)   DEFAULT NULL,
  `created_by`                          varchar (255)   DEFAULT 'Muhammad Qasim',
  `created_at`                          DATETIME        DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                          TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`                             BOOLEAN         DEFAULT 0,
  `touched_run_id`                      int             DEFAULT 0,
  `md5_hash`                            varchar (100),
  UNIQUE KEY  `md5`             (`md5_hash`),
  INDEX       `deleted`         (`deleted`),
  INDEX       `touched_run_id`  (`touched_run_id`),
  INDEX       `run_id`          (`run_id`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
