CREATE TABLE `MT_employee_salary_scrape`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  `year`              VARCHAR(255),
  `department`        VARCHAR(255),
  `full_name`         VARCHAR(255),
  `job_title`         VARCHAR(255),
  `city`              VARCHAR(255),
  `base_pay`          NUMERIC(12,2),
  `total_pay`         NUMERIC(12,2),
  `frequency`         VARCHAR(255),
  `data_source_url`   VARCHAR(255) NOT NULL DEFAULT "https://dataportal.mt.gov/t/DOASITSDDataPortalPub/views/SABHRSStateEmployeeData/EmployeeDataDashboard?%3Aembed=y&%3AshowAppBanner=false&%3AshowShareOptions=true&%3Adisplay_count=no&%3AshowVizHome=no",
  `created_by`        VARCHAR(255)      DEFAULT 'Adeel',
  `scrape_frequency`  VARCHAR(255)      DEFAULT 'Daily',
  `created_at`        DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN           DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Adeel';
