create table dallas_police_incidents
(
  `id`                        BIGINT AUTO_INCREMENT PRIMARY KEY,
  `run_id`                    BIGINT,
  `incidentnum`               VARCHAR(20),
  `servyr`                    INT,
  `servnumid`                 VARCHAR(20),
  `watch`                     INT,
  `signal`                    TEXT,
  `offincident`               TEXT,
  `premise`                   TEXT,
  `objattack`                 TEXT,
  `incident_address`          VARCHAR(255),
  `apt`                       TEXT,
  `ra`                        INT,
  `beat`                      INT,
  `division`                  TEXT,
  `sector`                    INT,
  `district`                  TEXT,
  `taag`                      TEXT,
  `community`                 TEXT,
  `date1`                     TEXT,
  `year1`                     INT,
  `month1`                    TEXT,
  `day1`                      TEXT,
  `time1`                     TEXT,
  `date1dayofyear`            INT,
  `date2_of_occurrence_2`     TEXT,
  `year2`                     INT,
  `month2`                    TEXT,
  `day2`                      TEXT,
  `time2`                     TEXT,
  `date2dayofyear`            INT,
  `reporteddate`              TEXT,
  `edate`                     TEXT,
  `eyear`                     INT,
  `emonth`                    TEXT,
  `eday`                      TEXT,
  `etime`                     TEXT,
  `edatedayofyear`            TEXT,
  `cfs_number`                TEXT,
  `callorgdate`               TEXT,
  `callreceived`              TEXT,
  `callcleared`               TEXT,
  `calldispatched`            TEXT,
  `splrpt`                    TEXT,
  `involvement`               TEXT,
  `victimtype`                TEXT,
  `compname`                  TEXT,
  `compname_cleaned`          VARCHAR(255),
  `compname_cleaned_manually` VARCHAR(255),
  `comprace`                  TEXT,
  `compethnicity`             TEXT,
  `compsex`                   TEXT,
  `compage`                   INT,
  `compageatoffensetime`      INT,
  `comphaddress`              TEXT,
  `comphapt`                  TEXT,
  `comphzipcode`              TEXT,
  `compcity`                  TEXT,
  `compstate`                 TEXT,
  `compbusname`               TEXT,
  `compbaddress`              TEXT,
  `compbphone`                TEXT,
  `ro1badge`                  TEXT,
  `ro1name`                   TEXT,
  `ro1name_cleaned`           VARCHAR(255),
  `ro1name_cleaned_manually`  VARCHAR(255),
  `ro2badge`                  TEXT,
  `ro2name`                   TEXT,
  `ro2name_cleaned`           VARCHAR(255),
  `ro2name_cleaned_manually`  VARCHAR(255),
  `reptoff`                   TEXT,
  `assoffbadge`               TEXT,
  `reviewbadgenum`            TEXT,
  `elenum`                    TEXT,
  `followup1`                 TEXT,
  `followup2`                 TEXT,
  `status`                    TEXT,
  `ucr_disp`                  TEXT,
  `victiminjurydesc`          TEXT,
  `victimcond`                TEXT,
  `mo`                        TEXT,
  `family`                    TEXT,
  `hate`                      TEXT,
  `hatecrimedescriptn`        TEXT,
  `weaponused`                TEXT,
  `gang`                      TEXT,
  `vicpckg`                   TEXT,
  `drug`                      TEXT,
  `offensecode`               TEXT,
  `cjis`                      INT,
  `penalcode`                 TEXT,
  `ucr_offense`               TEXT,
  `ucr_offdesc`               TEXT,
  `ucrcode`                   INT,
  `type`                      TEXT,
  `nibrs_crime`               TEXT,
  `nibrs_crime_category`      TEXT,
  `nibrs_crimeagainst`        TEXT,
  `nibrs_code`                TEXT,
  `nibrs_group`               TEXT,
  `nibrs_type`                TEXT,
  `upzdate`                   TEXT,
  `x_coordinate`              FLOAT,
  `y_coordinate`              FLOAT,
  `zip_code`                  INT,
  `city`                      TEXT,
  `state`                     TEXT,
  `geocoded_column`           TEXT,
  `data_source_url`           VARCHAR(255)       DEFAULT 'https://www.dallasopendata.com/Public-Safety/Police-Incidents/qv6i-rri7',
  `created_by`                VARCHAR(255)       DEFAULT 'Art Jarocki',
  `created_at`                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`            BIGINT,
  `deleted`                   BOOLEAN            DEFAULT 0,
  `md5_hash`                  VARCHAR(255),
  INDEX md5 (md5_hash),
  INDEX run_id (run_id),
  INDEX touched_run_id (touched_run_id),
  INDEX deleted (deleted),
  INDEX idx_geojoin (incident_address, zip_code, deleted)
) DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;
