CREATE TABLE `AZ_school_AzMERIT_and_MSAA_scores` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`year` varchar(255) DEFAULT NULL,
`school` varchar(255) DEFAULT NULL,
`school_id` varchar(255) DEFAULT NULL,
`school_CTDS_num` varchar(255) DEFAULT NULL,
`charter` varchar(255) DEFAULT NULL,
`district` varchar(255) DEFAULT NULL,
`district_id` varchar(255) DEFAULT NULL,
`district_CTDS_num` varchar(255) DEFAULT NULL,
`county` varchar(255) DEFAULT NULL,
`content_area` varchar(255) DEFAULT NULL,
`test_level` varchar(255) DEFAULT NULL,
`subgroup` varchar(255) DEFAULT NULL,
`subject` varchar(255) DEFAULT NULL,
`num_tested` varchar(255) DEFAULT NULL,
`pct_passing` varchar(255) DEFAULT NULL,
`pct_performance_level_1` varchar(255) DEFAULT NULL,
`pct_performance_level_2` varchar(255) DEFAULT NULL,
`pct_performance_level_3` varchar(255) DEFAULT NULL,
`pct_performance_level_4` varchar(255) DEFAULT NULL,
`data_source_url` varchar(255) DEFAULT NULL,
`scrape_dev_name` varchar(255) DEFAULT NULL,
`scrape_frequency` varchar(255) DEFAULT NULL,
`created_at` datetime DEFAULT NULL,
`update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`last_scrape_date` date DEFAULT NULL,
`next_scrape_date` date DEFAULT NULL,
`expected_scrape_frequency` varchar(255) DEFAULT NULL,
`dataset_name_prefix` varchar(255) DEFAULT NULL,
`scrape_status` varchar(255) DEFAULT NULL,
`pl_gather_task_id` varchar(255) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=960151 DEFAULT CHARSET=latin1