CREATE TABLE `az_school_dropout_scores` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`year` varchar(255) DEFAULT NULL,
`lea_entity_id` int(11) DEFAULT NULL,
`lea_name` varchar(255) DEFAULT NULL,
`school_id` int(11) DEFAULT NULL,
`school` varchar(255) DEFAULT NULL,
`county` varchar(255) DEFAULT NULL,
`charter` varchar(255) DEFAULT NULL,
`subgroup` varchar(255) DEFAULT NULL,
`dropout_percentage_rate` varchar(255) DEFAULT NULL,
`data_type` varchar(255) DEFAULT NULL,
`data_source_url` varchar(255) DEFAULT NULL,
`report_date` DATE,
`scrape_dev_name` varchar(255) DEFAULT NULL,
`scrape_frequency` varchar(255) DEFAULT NULL,
`created_at` datetime DEFAULT NULL,
`update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`last_scrape_date` date DEFAULT NULL,
`next_scrape_date` date DEFAULT NULL,
`expected_scrape_frequency` varchar(255) DEFAULT NULL,
`dataset_name_prefix` varchar(255) DEFAULT NULL,
`scrape_status` varchar(255) DEFAULT NULL,
`pl_gather_task_id` varchar(255) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
