CREATE TABLE `az_school_enroll_scores` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`fiscal_year` varchar(255) DEFAULT NULL,
`school_year` varchar(255) DEFAULT NULL,
`lea_entity_id` int(11) DEFAULT NULL,
`lea_name` varchar(255) DEFAULT NULL,
`school_id` int(11) DEFAULT NULL,
`school` varchar(255) DEFAULT NULL,
`school_type` varchar(255) DEFAULT NULL,
`county` varchar(255) DEFAULT NULL,
`subgroup` varchar(255) DEFAULT NULL,
`asian` varchar(255) DEFAULT NULL,
`american_indian_alaskan_native` varchar(255) DEFAULT NULL,
`black_african_american` varchar(255) DEFAULT NULL,
`hispanic_latino` varchar(255) DEFAULT NULL,
`white` varchar(255) DEFAULT NULL,
`native_hawaiian_pacific_islander` varchar(255) DEFAULT NULL,
`multiple_races` varchar(255) DEFAULT NULL,
`female` varchar(255) DEFAULT NULL,
`male` varchar(255) DEFAULT NULL,
`ps` varchar(255) DEFAULT NULL,
`kg` varchar(255) DEFAULT NULL,
`1` varchar(255) DEFAULT NULL,
`2` varchar(255) DEFAULT NULL,
`3` varchar(255) DEFAULT NULL,
`4` varchar(255) DEFAULT NULL,
`5` varchar(255) DEFAULT NULL,
`6` varchar(255) DEFAULT NULL,
`7` varchar(255) DEFAULT NULL,
`8` varchar(255) DEFAULT NULL,
`9` varchar(255) DEFAULT NULL,
`10` varchar(255) DEFAULT NULL,
`11` varchar(255) DEFAULT NULL,
`12` varchar(255) DEFAULT NULL,
`total` varchar(255) DEFAULT NULL,
`data_type` varchar(255) DEFAULT NULL,
`data_source_url` varchar(255) DEFAULT NULL,
`scrape_dev_name` varchar(255) DEFAULT NULL,
`report_date` DATE,
`scrape_frequency` varchar(255) DEFAULT NULL,
`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`last_scrape_date` date DEFAULT NULL,
`next_scrape_date` date DEFAULT NULL,
`expected_scrape_frequency` varchar(255) DEFAULT NULL,
`dataset_name_prefix` varchar(255) DEFAULT NULL,
`scrape_status` varchar(255) DEFAULT NULL,
`pl_gather_task_id` varchar(255) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci COMMENT="Created at: 2022-09-12 | by: Anton Storchak | #495 Arizona School Data";