CREATE TABLE `nppes_npi_registry__taxonomies`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`             BIGINT NOT NULL,
    `taxonomy_code`   VARCHAR(10) NOT NULL,
    `license_number`  VARCHAR(20),
    `state_code`      VARCHAR(2),
    `taxonomy_switch` VARCHAR(1) NOT NULL,
    `taxonomy_group`  VARCHAR(10) NOT NULL,
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry__identifiers`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`             BIGINT NOT NULL,
    `identifier`      VARCHAR(20) NOT NULL,
    `type_code`       VARCHAR(2),
    `state`           VARCHAR(2),
    `issuer`          VARCHAR(80),
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry__other_names`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`             BIGINT NOT NULL,
    `other_name`      VARCHAR(120) NOT NULL,
    `name_type_code`  VARCHAR(1) NOT NULL,
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry__person_names`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`             BIGINT NOT NULL,
    `name_type`     	VARCHAR(10), # MAIN / OTHER / OFFICIAL
    `last_name`      	VARCHAR(35),
    `first_name`     	VARCHAR(20),
    `middle_name`    	VARCHAR(20),
    `name_prefix`    	VARCHAR(5),
    `name_suffix`    	VARCHAR(5),
    `credential`     	VARCHAR(20),
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry__locations`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`             BIGINT NOT NULL,
    `location_type`   VARCHAR(10) NOT NULL DEFAULT 'SECONDARY',
    `address_line1`   VARCHAR(55) NOT NULL,
    `address_line2`   VARCHAR(55),
    `city_name`       VARCHAR(40) NOT NULL,
    `state_name`      VARCHAR(40) NOT NULL,
    `postal_code`     VARCHAR(20) NOT NULL,
    `country_code`    VARCHAR(2) NOT NULL,
    `phone_number`    VARCHAR(20),
    `phone_extension` VARCHAR(5),
    `fax_number`      VARCHAR(20),
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci;


CREATE TABLE `nppes_npi_registry__endpoints`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`                               BIGINT NOT NULL,
    `endpoint_type`                     VARCHAR(50) NOT NULL,
    `endpoint_type_description`         VARCHAR(255) NOT NULL,
    `endpoint`                          VARCHAR(1000) NOT NULL,
    `affiliation`                       VARCHAR(1) NOT NULL,
    `endpoint_description`              VARCHAR(1000),
    `affiliation_legal_buisiness_name`  VARCHAR(70),
    `use_code`                          VARCHAR(25),
    `use_description`                   VARCHAR(100),
    `other_use_description`             VARCHAR(200),
    `content_type`                      VARCHAR(25),
    `content_description`               VARCHAR(100),
    `other_content_description`         VARCHAR(200),
    `affiliation_address_line1`         VARCHAR(55),
    `affiliation_address_line2`         VARCHAR(55),
    `affiliation_address_city`          VARCHAR(40),
    `affiliation_address_state`         VARCHAR(40),
    `affiliation_address_country`       VARCHAR(2),
    `affiliation_address_postal_code`   VARCHAR(20),
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
    COLLATE = utf8mb4_unicode_520_ci;


CREATE TABLE `nppes_npi_registry__npidata`
(
  `id`                BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`            BIGINT(20),
  # BEGIN scrape 422
    `npi`                                                           BIGINT(10) NOT NULL,
    `entity_type_code`                                            	TINYINT(1),
    `replacement_npi`                                             	BIGINT(10) DEFAULT NULL,
    `employer_identification_number_(ein)`                        	VARCHAR(9),
    `provider_organization_name`                                  	VARCHAR(70),
    `provider_other_organization_name`                            	VARCHAR(70),
    `provider_other_organization_name_type_code`                    VARCHAR(1),
    `provider_other_last_name_type_code`                            TINYINT(1),
    `provider_enumeration_date`	                                    DATE,
    `last_update_date`                                            	DATE,
    `npi_deactivation_reason_code`                                	VARCHAR(2),
    `npi_deactivation_date`                                       	DATE,
    `npi_reactivation_date`                                       	DATE,
    `provider_gender_code`                                        	VARCHAR(1),
    `authorized_official_title_or_position`                       	VARCHAR(35),
    `authorized_official_telephone_number`                        	VARCHAR(20),
    `is_sole_proprietor`                                          	VARCHAR(1),
    `is_organization_subpart`                                     	VARCHAR(1),
    `parent_organization_lbn`                                     	VARCHAR(70),
    `parent_organization_tin`                                     	VARCHAR(9),
    `certification_date`                                            DATE,
  # END
  `data_source_url`   TEXT,
  `created_by`        VARCHAR(255)       DEFAULT 'Oleksii Kuts',
  `created_at`        DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`    BIGINT,
  `deleted`           BOOLEAN            DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry__npidata_csv`
(
  # BEGIN scrape 422
    `npi`                                                           BIGINT(10) NOT NULL,
    `entity_type_code`                                            	TINYINT(1),
    `replacement_npi`                                             	BIGINT(10) DEFAULT NULL,
    `employer_identification_number_(ein)`                        	VARCHAR(9),
    `provider_organization_name`                                  	VARCHAR(70),
    `provider_last_name`                                          	VARCHAR(35),
    `provider_first_name`                                         	VARCHAR(20),
    `provider_middle_name`                                        	VARCHAR(20),
    `provider_name_prefix_text`                                   	VARCHAR(5),
    `provider_name_suffix_text`                                   	VARCHAR(5),
    `provider_credential_text`                                    	VARCHAR(20),
    `provider_other_organization_name`                            	VARCHAR(70),
    `provider_other_organization_name_type_code`                    VARCHAR(1),
    `provider_other_last_name`                                    	VARCHAR(35),
    `provider_other_first_name`                                     VARCHAR(20),
    `provider_other_middle_name`                                    VARCHAR(20),
    `provider_other_name_prefix_text`                               VARCHAR(5),
    `provider_other_name_suffix_text`                               VARCHAR(5),
    `provider_other_credential_text`                                VARCHAR(20),
    `provider_other_last_name_type_code`                            TINYINT(1),
    `provider_first_line_business_mailing_address`                  VARCHAR(55),
    `provider_second_line_business_mailing_address`                 VARCHAR(55),
    `provider_business_mailing_address_city_name`                   VARCHAR(40),
    `provider_business_mailing_address_state_name`                  VARCHAR(40),
    `provider_business_mailing_address_postal_code`                 VARCHAR(20),
    `provider_business_mailing_address_country_code`	              VARCHAR(2),
    `provider_business_mailing_address_telephone_number`	          VARCHAR(20),
    `provider_business_mailing_address_fax_number`	                VARCHAR(20),
    `provider_first_line_business_practice_location_address`        VARCHAR(55),
    `provider_second_line_business_practice_location_address`       VARCHAR(55),
    `provider_business_practice_location_address_city_name`         VARCHAR(40),
    `provider_business_practice_location_address_state_name`        VARCHAR(40),
    `provider_business_practice_location_address_postal_code`       VARCHAR(20),
    `provider_business_practice_location_address_country_code`      VARCHAR(2),
    `provider_business_practice_location_address_telephone_number` 	VARCHAR(20),
    `provider_business_practice_location_address_fax_number`        VARCHAR(20),
    `provider_enumeration_date`	                                    VARCHAR(10),
    `last_update_date`                                            	VARCHAR(10),
    `npi_deactivation_reason_code`                                	VARCHAR(2),
    `npi_deactivation_date`                                       	VARCHAR(10),
    `npi_reactivation_date`                                       	VARCHAR(10),
    `provider_gender_code`                                        	VARCHAR(1),
    `authorized_official_last_name`                               	VARCHAR(35),
    `authorized_official_first_name`                              	VARCHAR(20),
    `authorized_official_middle_name`                             	VARCHAR(20),
    `authorized_official_title_or_position`                       	VARCHAR(35),
    `authorized_official_telephone_number`                        	VARCHAR(20),
    `healthcare_provider_taxonomy_code_1`                         	VARCHAR(10),
    `provider_license_number_1`	                                    VARCHAR(20),
    `provider_license_number_state_code_1`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_1`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_2`                         	VARCHAR(10),
    `provider_license_number_2`	                                    VARCHAR(20),
    `provider_license_number_state_code_2`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_2`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_3`                         	VARCHAR(10),
    `provider_license_number_3`	                                    VARCHAR(20),
    `provider_license_number_state_code_3`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_3`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_4`                         	VARCHAR(10),
    `provider_license_number_4`	                                    VARCHAR(20),
    `provider_license_number_state_code_4`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_4`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_5`                         	VARCHAR(10),
    `provider_license_number_5`	                                    VARCHAR(20),
    `provider_license_number_state_code_5`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_5`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_6`                         	VARCHAR(10),
    `provider_license_number_6`	                                    VARCHAR(20),
    `provider_license_number_state_code_6`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_6`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_7`                         	VARCHAR(10),
    `provider_license_number_7`	                                    VARCHAR(20),
    `provider_license_number_state_code_7`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_7`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_8`                         	VARCHAR(10),
    `provider_license_number_8`	                                    VARCHAR(20),
    `provider_license_number_state_code_8`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_8`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_9`                         	VARCHAR(10),
    `provider_license_number_9`	                                    VARCHAR(20),
    `provider_license_number_state_code_9`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_9`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_10`                         	VARCHAR(10),
    `provider_license_number_10`                                    VARCHAR(20),
    `provider_license_number_state_code_10`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_10`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_11`                         	VARCHAR(10),
    `provider_license_number_11`                                    VARCHAR(20),
    `provider_license_number_state_code_11`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_11`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_12`                         	VARCHAR(10),
    `provider_license_number_12`                                    VARCHAR(20),
    `provider_license_number_state_code_12`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_12`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_13`                         	VARCHAR(10),
    `provider_license_number_13`                                    VARCHAR(20),
    `provider_license_number_state_code_13`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_13`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_14`                         	VARCHAR(10),
    `provider_license_number_14`                                    VARCHAR(20),
    `provider_license_number_state_code_14`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_14`               	VARCHAR(1),
    `healthcare_provider_taxonomy_code_15`                         	VARCHAR(10),
    `provider_license_number_15`                                    VARCHAR(20),
    `provider_license_number_state_code_15`                        	VARCHAR(2),
    `healthcare_provider_primary_taxonomy_switch_15`               	VARCHAR(1),
    `other_provider_identifier_1`                                   VARCHAR(20),
    `other_provider_identifier_type_code_1`                       	VARCHAR(2),
    `other_provider_identifier_state_1`	                            VARCHAR(2),
    `other_provider_identifier_issuer_1`                          	TEXT,
    `other_provider_identifier_2`                                   VARCHAR(20),
    `other_provider_identifier_type_code_2`	                      	VARCHAR(2),
    `other_provider_identifier_state_2`	                          	VARCHAR(2),
    `other_provider_identifier_issuer_2`                          	TEXT,
    `other_provider_identifier_3`                                   VARCHAR(20),
    `other_provider_identifier_type_code_3`	                      	VARCHAR(2),
    `other_provider_identifier_state_3`                       	    VARCHAR(2),
    `other_provider_identifier_issuer_3`                          	TEXT,
    `other_provider_identifier_4`                                   VARCHAR(20),
    `other_provider_identifier_type_code_4`	                      	VARCHAR(2),
    `other_provider_identifier_state_4`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_4`                          	TEXT,
    `other_provider_identifier_5`                                   VARCHAR(20),
    `other_provider_identifier_type_code_5`	                      	VARCHAR(2),
    `other_provider_identifier_state_5`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_5`                          	TEXT,
    `other_provider_identifier_6`                                   VARCHAR(20),
    `other_provider_identifier_type_code_6`	                      	VARCHAR(2),
    `other_provider_identifier_state_6`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_6`                          	TEXT,
    `other_provider_identifier_7`                                   VARCHAR(20),
    `other_provider_identifier_type_code_7`	                      	VARCHAR(2),
    `other_provider_identifier_state_7`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_7`                          	TEXT,
    `other_provider_identifier_8`                                   VARCHAR(20),
    `other_provider_identifier_type_code_8`	                      	VARCHAR(2),
    `other_provider_identifier_state_8`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_8`                          	TEXT,
    `other_provider_identifier_9`                                   VARCHAR(20),
    `other_provider_identifier_type_code_9`	                      	VARCHAR(2),
    `other_provider_identifier_state_9`	                      	    VARCHAR(2),
    `other_provider_identifier_issuer_9`                          	TEXT,
    `other_provider_identifier_10`                                  VARCHAR(20),
    `other_provider_identifier_type_code_10`	                      VARCHAR(2),
    `other_provider_identifier_state_10`	                      	  VARCHAR(2),
    `other_provider_identifier_issuer_10`                          	TEXT,
    `other_provider_identifier_11`                                  VARCHAR(20),
    `other_provider_identifier_type_code_11`	                      VARCHAR(2),
    `other_provider_identifier_state_11`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_11`                          	TEXT,
    `other_provider_identifier_12`                                  VARCHAR(20),
    `other_provider_identifier_type_code_12`	                      VARCHAR(2),
    `other_provider_identifier_state_12`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_12`                          	TEXT,
    `other_provider_identifier_13`                                  VARCHAR(20),
    `other_provider_identifier_type_code_13`	                      VARCHAR(2),
    `other_provider_identifier_state_13`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_13`                          	TEXT,
    `other_provider_identifier_14`                                  VARCHAR(20),
    `other_provider_identifier_type_code_14`	                      VARCHAR(2),
    `other_provider_identifier_state_14`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_14`                          	TEXT,
    `other_provider_identifier_15`                                  VARCHAR(20),
    `other_provider_identifier_type_code_15`	                     	VARCHAR(2),
    `other_provider_identifier_state_15`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_15`                          	TEXT,
    `other_provider_identifier_16`                                  VARCHAR(20),
    `other_provider_identifier_type_code_16`	                     	VARCHAR(2),
    `other_provider_identifier_state_16`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_16`                          	TEXT,
    `other_provider_identifier_17`                                  VARCHAR(20),
    `other_provider_identifier_type_code_17`	                     	VARCHAR(2),
    `other_provider_identifier_state_17`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_17`                          	TEXT,
    `other_provider_identifier_18`                                  VARCHAR(20),
    `other_provider_identifier_type_code_18`	                     	VARCHAR(2),
    `other_provider_identifier_state_18`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_18`                          	TEXT,
    `other_provider_identifier_19`                                  VARCHAR(20),
    `other_provider_identifier_type_code_19`	                     	VARCHAR(2),
    `other_provider_identifier_state_19`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_19`                          	TEXT,
    `other_provider_identifier_20`                                  VARCHAR(20),
    `other_provider_identifier_type_code_20`	                     	VARCHAR(2),
    `other_provider_identifier_state_20`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_20`                          	TEXT,
    `other_provider_identifier_21`                                  VARCHAR(20),
    `other_provider_identifier_type_code_21`                      	VARCHAR(2),
    `other_provider_identifier_state_21`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_21`                          	TEXT,
    `other_provider_identifier_22`                                  VARCHAR(20),
    `other_provider_identifier_type_code_22`	                     	VARCHAR(2),
    `other_provider_identifier_state_22`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_22`                          	TEXT,
    `other_provider_identifier_23`                                  VARCHAR(20),
    `other_provider_identifier_type_code_23`	                     	VARCHAR(2),
    `other_provider_identifier_state_23`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_23`                          	TEXT,
    `other_provider_identifier_24`                                  VARCHAR(20),
    `other_provider_identifier_type_code_24`	                     	VARCHAR(2),
    `other_provider_identifier_state_24`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_24`                          	TEXT,
    `other_provider_identifier_25`                                  VARCHAR(20),
    `other_provider_identifier_type_code_25`	                     	VARCHAR(2),
    `other_provider_identifier_state_25`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_25`                          	TEXT,
    `other_provider_identifier_26`                                  VARCHAR(20),
    `other_provider_identifier_type_code_26`	                     	VARCHAR(2),
    `other_provider_identifier_state_26`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_26`                          	TEXT,
    `other_provider_identifier_27`                                  VARCHAR(20),
    `other_provider_identifier_type_code_27`	                     	VARCHAR(2),
    `other_provider_identifier_state_27`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_27`                          	TEXT,
    `other_provider_identifier_28`                                  VARCHAR(20),
    `other_provider_identifier_type_code_28`	                     	VARCHAR(2),
    `other_provider_identifier_state_28`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_28`                          	TEXT,
    `other_provider_identifier_29`                                  VARCHAR(20),
    `other_provider_identifier_type_code_29`	                     	VARCHAR(2),
    `other_provider_identifier_state_29`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_29`                          	TEXT,
    `other_provider_identifier_30`                                  VARCHAR(20),
    `other_provider_identifier_type_code_30`	                     	VARCHAR(2),
    `other_provider_identifier_state_30`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_30`                          	TEXT,
    `other_provider_identifier_31`                                  VARCHAR(20),
    `other_provider_identifier_type_code_31`	                     	VARCHAR(2),
    `other_provider_identifier_state_31`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_31`                          	TEXT,
    `other_provider_identifier_32`                                  VARCHAR(20),
    `other_provider_identifier_type_code_32`                      	VARCHAR(2),
    `other_provider_identifier_state_32`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_32`                          	TEXT,
    `other_provider_identifier_33`                                  VARCHAR(20),
    `other_provider_identifier_type_code_33`	                     	VARCHAR(2),
    `other_provider_identifier_state_33`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_33`                          	TEXT,
    `other_provider_identifier_34`                                  VARCHAR(20),
    `other_provider_identifier_type_code_34`	                     	VARCHAR(2),
    `other_provider_identifier_state_34`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_34`                          	TEXT,
    `other_provider_identifier_35`                                  VARCHAR(20),
    `other_provider_identifier_type_code_35`	                     	VARCHAR(2),
    `other_provider_identifier_state_35`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_35`                          	TEXT,
    `other_provider_identifier_36`                                  VARCHAR(20),
    `other_provider_identifier_type_code_36`	                     	VARCHAR(2),
    `other_provider_identifier_state_36`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_36`                          	TEXT,
    `other_provider_identifier_37`                                  VARCHAR(20),
    `other_provider_identifier_type_code_37`	                     	VARCHAR(2),
    `other_provider_identifier_state_37`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_37`                          	TEXT,
    `other_provider_identifier_38`                                  VARCHAR(20),
    `other_provider_identifier_type_code_38`	                     	VARCHAR(2),
    `other_provider_identifier_state_38`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_38`                          	TEXT,
    `other_provider_identifier_39`                                  VARCHAR(20),
    `other_provider_identifier_type_code_39`	                     	VARCHAR(2),
    `other_provider_identifier_state_39`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_39`                          	TEXT,
    `other_provider_identifier_40`                                  VARCHAR(20),
    `other_provider_identifier_type_code_40`	                     	VARCHAR(2),
    `other_provider_identifier_state_40`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_40`                          	TEXT,
    `other_provider_identifier_41`                                  VARCHAR(20),
    `other_provider_identifier_type_code_41`	                     	VARCHAR(2),
    `other_provider_identifier_state_41`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_41`                          	TEXT,
    `other_provider_identifier_42`                                  VARCHAR(20),
    `other_provider_identifier_type_code_42`	                     	VARCHAR(2),
    `other_provider_identifier_state_42`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_42`                          	TEXT,
    `other_provider_identifier_43`                                  VARCHAR(20),
    `other_provider_identifier_type_code_43`	                     	VARCHAR(2),
    `other_provider_identifier_state_43`	                      	  VARCHAR(2),
    `other_provider_identifier_issuer_43`                          	TEXT,
    `other_provider_identifier_44`                                  VARCHAR(20),
    `other_provider_identifier_type_code_44`                      	VARCHAR(2),
    `other_provider_identifier_state_44`	                         	VARCHAR(2),
    `other_provider_identifier_issuer_44`                          	TEXT,
    `other_provider_identifier_45`                                  VARCHAR(20),
    `other_provider_identifier_type_code_45`	                     	VARCHAR(2),
    `other_provider_identifier_state_45`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_45`                          	TEXT,
    `other_provider_identifier_46`                                  VARCHAR(20),
    `other_provider_identifier_type_code_46`	                     	VARCHAR(2),
    `other_provider_identifier_state_46`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_46`                          	TEXT,
    `other_provider_identifier_47`                                  VARCHAR(20),
    `other_provider_identifier_type_code_47`	                     	VARCHAR(2),
    `other_provider_identifier_state_47`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_47`                          	TEXT,
    `other_provider_identifier_48`                                  VARCHAR(20),
    `other_provider_identifier_type_code_48`	                     	VARCHAR(2),
    `other_provider_identifier_state_48`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_48`                          	TEXT,
    `other_provider_identifier_49`                                  VARCHAR(20),
    `other_provider_identifier_type_code_49`	                     	VARCHAR(2),
    `other_provider_identifier_state_49`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_49`                          	TEXT,
    `other_provider_identifier_50`                                  VARCHAR(20),
    `other_provider_identifier_type_code_50`	                     	VARCHAR(2),
    `other_provider_identifier_state_50`	                        	VARCHAR(2),
    `other_provider_identifier_issuer_50`                          	TEXT,
    `is_sole_proprietor`                                          	VARCHAR(1),
    `is_organization_subpart`                                     	VARCHAR(1),
    `parent_organization_lbn`                                     	VARCHAR(70),
    `parent_organization_tin`                                     	VARCHAR(9),
    `authorized_official_name_prefix_text`                          VARCHAR(5),
    `authorized_official_name_suffix_text`                        	VARCHAR(5),
    `authorized_official_credential_text`                         	VARCHAR(20),
    `healthcare_provider_taxonomy_group_1`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_2`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_3`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_4`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_5`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_6`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_7`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_8`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_9`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_10`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_11`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_12`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_13`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_14`                        	VARCHAR(10),
    `healthcare_provider_taxonomy_group_15`                        	VARCHAR(10),
    `certification_date`                                            VARCHAR(10)
  # END
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `nppes_npi_registry_runs`
(
    `id`              BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    `status`          VARCHAR(255)       DEFAULT  'processing',
    `created_by`      VARCHAR(255)       DEFAULT 'Oleksii Kuts',
    `created_at`      DATETIME           DEFAULT CURRENT_TIMESTAMP,
    `updated_at`      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci;
