CREATE TABLE az_bar__azbar_org
(
    id                       int not null auto_increment   primary key,
    run_id                   int            null,
    bar_number               varchar(255)   null,
    name                     varchar(255)   null,
    first_name               varchar(255)   null,
    last_name                varchar(255)   null,
    middle_name              varchar(255)   null,
    date_admited             date           null,
    registration_status      varchar(255)   null,
    sections                 text           null,
    type                     varchar(255)   null,
    phone                    varchar(255)   null,
    email                    varchar(255)   null,
    fax                      varchar(255)   null,
    law_firm_name            varchar(255)   null,
    law_firm_address         varchar(255)   null,
    law_firm_zip             varchar(255)   null,
    law_firm_city            varchar(255)   null,
    law_firm_state           varchar(255)   null,
    law_firm_county          varchar(255)   null,
    name_prefix              varchar(255)   null,
    university               varchar(255)   null,
    professional_affiliation text           null,
    bio                      longtext       null,
    website                  varchar(255)   null,
    linkedin                 varchar(255)   null,
    facebook                 varchar(255)   null,
    twitter                  varchar(255)   null,
    law_firm_website         varchar(255)   null,
    other_jurisdictions      text           null,
    judicial_district        varchar(255)   null,
    disciplinary_actions     text           null,
    private_practice         varchar(255)   null,
    insurance                varchar(255)   null,
    courts_of_admittance     varchar(255)   null,
    scrape_frequency         varchar(255)   DEFAULT 'weekly',
    data_source_url          varchar(255),
    created_by               varchar(255)   DEFAULT 'Halid Hibragimov',
    created_at               DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    touched_run_id           BIGINT,
    deleted                  BOOLEAN           DEFAULT 0,
    md5_hash                 VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`),
  INDEX `bar_number` (`bar_number`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci
    COMMENT = 'The Scrape made by Halid Ibragimov';
