CREATE TABLE `ar_employee_salaries`
(
  `id`                  BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`              BIGINT(20),
  `fiscal_year`         YEAR,
  `data_year`           YEAR,
  `agency`              VARCHAR(255),
  `pay_class_category`  VARCHAR(255),
  `pay_scale_type`      VARCHAR(255),
  `position_number`     BIGINT,
  `position_title`      VARCHAR(255),
  `extra_help_flag`     BOOLEAN,
  `class_code`          VARCHAR(255),
  `employee_name`       VARCHAR(255),
  `career_service_date` DATE,
  `pay_grade`           VARCHAR(255),
  `gender`              VARCHAR(255),
  `race`                VARCHAR(255),
  `percent_of_time`     VARCHAR(255),
  `annual_salary`       VARCHAR(255),
  `data_source_url`     TEXT,
  `created_by`          VARCHAR(255)      DEFAULT 'Ray Piao',
  `created_at`          DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`      BIGINT,
  `deleted`             BOOLEAN           DEFAULT 0,
  `is_active`           BOOLEAN GENERATED ALWAYS AS (IF(deleted, NULL, TRUE)) STORED,
  `md5_hash`            VARCHAR(255),
  UNIQUE KEY `md5_active` (`md5_hash`, `is_active`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4` COLLATE = utf8mb4_unicode_520_ci COMMENT = 'The Scrape made by Ray Piao';
