CREATE TABLE `MI_RAW_summary`
(
  `id`                                                  BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  `run_id`                                              BIGINT(20),
  `committee_id`                                        BIGINT(20),
  `document_sequence`                                   INT,
  `committee_type`                                      VARCHAR(255),	
  `committee_name`                                      VARCHAR(255),	
  `candidate_first_name`                                VARCHAR(255),
  `candidate_middle_name`                               VARCHAR(255),
  `candidate_last_name`                                 VARCHAR(255),
  `political_party_affiliation`                         VARCHAR(255),
  `office_sought`                                       VARCHAR(255),
  `district_sought`                                     VARCHAR(255),
  `statement_year`                                      INT,
  `report_type`                                         VARCHAR(255),
  `date_filed`                                          DATE,
  `report_covers_from`                                  DATE,
  `report_covers_to`                                    DATE,
  `t_contrib_receipts_this_period`                      DECIMAL(10,2),
  `t_contrib_receipts_cumulative_this_election_cycle`   DECIMAL(10,2),
  `inkind_contr_this_period`                            DECIMAL(10,2),
  `inkind_contr_cumulative_this_election_cycle`         DECIMAL(10,2),
  `inkind_exp_this_period`                              DECIMAL(10,2),
  `inkind_exp_cumulative_this_election_cycle`           DECIMAL(10,2),
  `t_exp_this_period`                                   DECIMAL(10,2),
  `t_exp_cumulative_this_election_cycle`                DECIMAL(10,2),
  `t_inc_exp_disb_this_period`                          DECIMAL(10,2),
  `t_inc_exp_disb_cumulative_this_election_cycle`       DECIMAL(10,2),
  `debts_and_oblig_owed_by_committee`                   DECIMAL(10,2),
  `debts_and_oblig_owed_to_committee`                   DECIMAL(10,2),
  `ending_bal_of_last_report_filed`                     DECIMAL(10,2),
  `ending_bal_of_this_report`                           DECIMAL(10,2),
  `data_source_url`                                     VARCHAR(255)     DEFAULT 'https://drive.google.com/drive/folders/10MEskbZAyK6cSAA9GLTb5mInEub39BeC',
  `created_by`                                          VARCHAR(255)      DEFAULT 'Hatri',
  `created_at`                                          DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                                          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `touched_run_id`                                      BIGINT,
  `deleted`                                             BOOLEAN           DEFAULT 0,
  `md5_hash`                                            VARCHAR(255),
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `md5_hash` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`)
) DEFAULT CHARSET = `utf8mb4`
  COLLATE = utf8mb4_unicode_520_ci
    COMMENT = "The Scrape made by Hatri";
