create table gasbuddy_v2_gas_stations
(
    id                      INT             NOT NULL AUTO_INCREMENT,
    zip_searched            CHAR(10)        NOT NULL,
    station_id              BIGINT          NOT NULL,
    station_name            VARCHAR(255),
    ratings_count           VARCHAR(255),
    star_rating             VARCHAR(255),
    phone                   VARCHAR(255),
    timezone                VARCHAR(255),
    brand_name              VARCHAR(255),
    status                  VARCHAR(255),
    emergency_status        VARCHAR(255),
    latitude                VARCHAR(255),
    longitude               VARCHAR(255),
    address_country         VARCHAR(255),
    address_line_1          VARCHAR(255),
    address_line_2          VARCHAR(255),
    address_locality        VARCHAR(255),
    address_postal_code     VARCHAR(255),
    address_region          VARCHAR(255),
    data_source_url         VARCHAR(255),
    run_id                  BIGINT          NULL,
    touched_run_id          BIGINT          NULL,
    deleted                 TINYINT(1)      DEFAULT 0 NULL,
    md5_hash                VARCHAR(255)    NULL,
    created_by              VARCHAR(255)    DEFAULT 'Alim L.',
    created_at              DATETIME        DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP     NOT NULL
);