create table il_cckc_case_party(
  `id`  int auto_increment   primary key,
  `run_id`  int,
  `touch_run_id`  int,
  `court_id`  int,
  `case_id` varchar(225),
  `is_lawyer`  boolean DEFAULT NULL,
  `party_name` varchar(225) DEFAULT NULL,
  `party_type`  varchar(225) DEFAULT NULL,
  `party_law_firm`  varchar(225) DEFAULT NULL,
  `party_address`  varchar(225) DEFAULT NULL,
  `party_city`  varchar(225) DEFAULT NULL,
  `party_state`  varchar(225) DEFAULT NULL,
  `party_zip`  varchar(225) DEFAULT NULL,
  `party_description`  text DEFAULT NULL,
  `party_dob`  date DEFAULT NULL,
  `party_action`  varchar(225) DEFAULT NULL,
  `barcode`  varchar(225) DEFAULT NULL,
  `phone`  varchar(225) DEFAULT NULL,
  `md5_hash`  varchar (255),
  `deleted` int DEFAULT 0,
  `data_source_url`     varchar (350),
  `created_by`           VARCHAR(255)       DEFAULT 'Tauseeq',
  `created_at`           DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_frequency`  VARCHAR(255)      DEFAULT 'Weekly',
  `expected_scrape_frequency`     VARCHAR(255)      DEFAULT 'Weekly',
  `dataset_name_prefix`           VARCHAR(255)      DEFAULT  'Circuit Court of Kankakee County (500)',
  `scrape_status`          VARCHAR(255)      DEFAULT 'Live',
  UNIQUE KEY `unique_data` (`md5_hash`)
)DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
