create table il_cckc_case_info(
  `id`  int auto_increment   primary key,
  `run_id`  int,
  `touch_run_id`  int,
  `court_id`  int,
  `case_id` varchar(225),
  `case_name`  text DEFAULT NULL,
  `case_filed_date` date DEFAULT NULL,
  `case_type`  varchar(225) DEFAULT NULL,
  `case_description`  varchar(225) DEFAULT NULL,
  `disposition_or_status`  varchar(225) DEFAULT NULL,
  `status_as_of_date`  varchar(225) DEFAULT NULL,
  `judge_name` varchar(225) DEFAULT NULL,
  `md5_hash`  varchar (255),
  `deleted` int DEFAULT 0,
  `data_source_url`     varchar (350),
  `created_by`           VARCHAR(255)       DEFAULT 'Tauseeq',
  `created_at`           DATETIME           DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrape_frequency`  VARCHAR(255)      DEFAULT 'Weekly',
  `expected_scrape_frequency`     VARCHAR(255)      DEFAULT 'Weekly',
  `dataset_name_prefix`           VARCHAR(255)      DEFAULT  'Circuit Court of Kankakee County (500)',
  `scrape_status`          VARCHAR(255)      DEFAULT 'Live',
  UNIQUE KEY `unique_data` (`md5_hash`)
)DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
