CREATE TABLE al_general_info(
  `id`	              bigint(20)    AUTO_INCREMENT PRIMARY KEY,
  `is_district`	      tinyint(1),
  `district_id`	      bigint(20),
  `number`	          varchar(50),
  `name`	            varchar(255),
  `school_code`	      varchar(50),
  `state_school_id`	  varchar(50),
  `county_number`	    varchar(255),
  `nces_id`	          varchar(50),
  `coop_code`	        varchar(50),
  `coop_name`         varchar(255),
  `school_type`	      varchar(255),
  `low_grade`	        varchar(255),
  `high_grade`	      varchar(255),
  `title_1_status`	  varchar(255),
  `program_type`	    varchar(255),
  `education_program`	varchar(255),
  `locale`	          varchar(255),
  `phone`	            varchar(255),
  `fax`               varchar(255),
  `website`	          varchar(255),
  `address`	          varchar(255),
  `city`	            varchar(255),
  `county`	          varchar(255),
  `state`	            varchar(255),
  `zip`	              varchar(255),
  `lan`	              varchar(255),
  `lon`	              varchar(255),
  `data_source_url`   varchar(255),
  `created_by`        VARCHAR(255)      DEFAULT 'Aglazkov',
  `created_at`        DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        TIMESTAMP         DEFAULT CURRENT_TIMESTAMP   not null on update CURRENT_TIMESTAMP,
  `run_id`            BIGINT(20),
  `touched_run_id`    BIGINT,
  `deleted`           tinyint(1)           DEFAULT 0,
  `md5_hash`          VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX run_id (run_id),
  INDEX touched_run_id (touched_run_id),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;
