CREATE TABLE al_schools_assessment(
  `id`	               bigint(20)    AUTO_INCREMENT PRIMARY KEY,
  `general_id`	       bigint(20),
  `school_year`	       varchar(50),
  `exam_name`	       varchar(255),
  `subject`	           varchar(255),
  `grade`	           varchar(255),
  `gender`	           varchar(255),
  `race`	           varchar(255),
  `ethnicity`	       varchar(255),
  `sub_population`     varchar(255),
  `enrolled`           varchar(255),
  `tested`             varchar(255),
  `proficient`         varchar(255),
  `participation_rate` varchar(255),
  `proficient_rate`    varchar(255),
  `data_source_url`    varchar(255),
  `created_by`         varchar(255)      DEFAULT 'Aglazkov',
  `created_at`         DATETIME          DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         TIMESTAMP         DEFAULT CURRENT_TIMESTAMP   not null on update CURRENT_TIMESTAMP,
  `run_id`             BIGINT(20),
  `touched_run_id`     BIGINT,
  `deleted`            tinyint(1)           DEFAULT 0,
  `md5_hash`           VARCHAR(255),
  UNIQUE KEY md5 (md5_hash),
  INDEX run_id (run_id),
  INDEX touched_run_id (touched_run_id),
  INDEX deleted (deleted)
) DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;