create table michigan
(
  id bigint(20) auto_increment primary key,
  bar_number bigint(20)    default null,
  name varchar(255)  default null,
  first_name varchar(255)  default null,
  last_name varchar(255)  default null,
  middle_name varchar(255)  default null,
  link varchar(511)  default null,
  law_firm_name varchar(1023) default null,
  law_firm_address varchar(2045) default null,
  law_firm_zip varchar(255)  default null,
  law_firm_city varchar(255)  default null,
  law_firm_state varchar(15)   default null,
  law_firm_county varchar(255) default null,
  phone varchar(255)  default null,
  email varchar(255)  default null,
  date_admitted datetime      default null,
  registration_status varchar(255)  default null,
  data_source_url varchar(255) default null,
  created_by varchar(30)  default 'Tauseeq' null,
  created_at datetime     default CURRENT_TIMESTAMP   null,
  updated_at timestamp    default CURRENT_TIMESTAMP   not null on update CURRENT_TIMESTAMP,
  run_id bigint default null,
  touched_run_id bigint default null,
  deleted tinyint(1) default 0,
  md5_hash varchar(255) default null,
  practice_area json default null,
  university varchar(255) default null,
  sections varchar(255) default null,
  lawyer_type varchar(255) default null,
  professional_affiliation varchar(255) default null,
  bio varchar(255) default null,
  api_url varchar(255) default null,
  website varchar(255) default null,
  linkedin varchar(255) default null,
  facebook varchar(255) default null,
  twitter varchar(255) default null,
  law_firm_website varchar(255) default null,
  other_jurisdictions varchar(255) default null,
  judicial_district varchar(255) default null,
  disciplinary_actions varchar(255) default null,
  insurance varchar(255) default null,
  courts_of_admittance varchar(255) default null,
  fax varchar(255) default null,
  scrape_frequency varchar(100) default 'weekly',
  UNIQUE KEY `md5` (`md5_hash`),
  INDEX `run_id` (`run_id`),
  INDEX `touched_run_id` (`touched_run_id`),
  INDEX `deleted` (`deleted`),
  INDEX `bar_number` (`bar_number`)
) DEFAULT CHARSET = `utf8mb4`
COLLATE = utf8mb4_unicode_520_ci;
