CREATE TABLE IF NOT EXISTS `usa_raw`.`us_assisted_housing` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `quarter` DATE NULL DEFAULT NULL,
  `gsl` VARCHAR(255) NULL DEFAULT NULL,
  `states` VARCHAR(255) NULL DEFAULT NULL,
  `entities` VARCHAR(255) NULL DEFAULT NULL,
  `sumlevel` INT NULL DEFAULT NULL,
  `program_label` VARCHAR(255) NULL DEFAULT NULL,
  `program` INT NULL DEFAULT NULL,
  `sub_program` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `total_units` INT NULL DEFAULT NULL,
  `pct_occupied` INT NULL DEFAULT NULL,
  `number_reported` INT NULL DEFAULT NULL,
  `pct_reported` INT NULL DEFAULT NULL,
  `months_since_report` INT NULL DEFAULT NULL,
  `pct_movein` INT NULL DEFAULT NULL,
  `people_per_unit` FLOAT NULL DEFAULT NULL,
  `people_total` INT NULL DEFAULT NULL,
  `rent_per_month` INT NULL DEFAULT NULL,
  `spending_per_month` INT NULL DEFAULT NULL,
  `hh_income` INT NULL DEFAULT NULL,
  `person_income` INT NULL DEFAULT NULL,
  `pct_lt5k` INT NULL DEFAULT NULL,
  `pct_5k_lt10k` INT NULL DEFAULT NULL,
  `pct_10k_lt15k` INT NULL DEFAULT NULL,
  `pct_15k_lt20k` INT NULL DEFAULT NULL,
  `pct_ge20k` INT NULL DEFAULT NULL,
  `pct_wage_major` INT NULL DEFAULT NULL,
  `pct_welfare_major` INT NULL DEFAULT NULL,
  `pct_other_major` INT NULL DEFAULT NULL,
  `pct_median` INT NULL DEFAULT NULL,
  `pct_lt50_median` INT NULL DEFAULT NULL,
  `pct_lt30_median` INT NULL DEFAULT NULL,
  `pct_2adults` INT NULL DEFAULT NULL,
  `pct_1adult` INT NULL DEFAULT NULL,
  `pct_female_head` INT NULL DEFAULT NULL,
  `pct_female_head_child` INT NULL DEFAULT NULL,
  `pct_disabled_lt62` INT NULL DEFAULT NULL,
  `pct_disabled_ge62` INT NULL DEFAULT NULL,
  `pct_disabled_all` INT NULL DEFAULT NULL,
  `pct_lt24_head` INT NULL DEFAULT NULL,
  `pct_age25_50` INT NULL DEFAULT NULL,
  `pct_age51_61` INT NULL DEFAULT NULL,
  `pct_age62plus` INT NULL DEFAULT NULL,
  `pct_age85plus` INT NULL DEFAULT NULL,
  `pct_minority` INT NULL DEFAULT NULL,
  `pct_black_nonhsp` INT NULL DEFAULT NULL,
  `pct_native_american_nonhsp` INT NULL DEFAULT NULL,
  `pct_asian_pacific_nonhsp` INT NULL DEFAULT NULL,
  `pct_white_nothsp` INT NULL DEFAULT NULL,
  `pct_black_hsp` INT NULL DEFAULT NULL,
  `pct_wht_hsp` INT NULL DEFAULT NULL,
  `pct_oth_hsp` INT NULL DEFAULT NULL,
  `pct_hispanic` INT NULL DEFAULT NULL,
  `pct_multi` INT NULL DEFAULT NULL,
  `months_waiting` INT NULL DEFAULT NULL,
  `months_from_movein` INT NULL DEFAULT NULL,
  `pct_utility_allow` INT NULL DEFAULT NULL,
  `ave_util_allow` INT NULL DEFAULT NULL,
  `pct_bed1` INT NULL DEFAULT NULL,
  `pct_bed2` INT NULL DEFAULT NULL,
  `pct_bed3` INT NULL DEFAULT NULL,
  `pct_overhoused` INT NULL DEFAULT NULL,
  `tpoverty` INT NULL DEFAULT NULL,
  `tminority` INT NULL DEFAULT NULL,
  `tpct_ownsfd` INT NULL DEFAULT NULL,
  `fedhse` INT NULL DEFAULT NULL,
  `cbsa` INT NULL DEFAULT NULL,
  `place` INT NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `pha_total_units` INT NULL DEFAULT NULL,
  `ha_size` INT NULL DEFAULT NULL,
  `data_source_url` TEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT 'Jaffar Hussain',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `touched_run_id` BIGINT(20) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5` (`md5_hash` ASC)  ,
  INDEX `run_id` (`run_id` ASC)  ,
  INDEX `touched_run_id` (`touched_run_id` ASC)  ,
  INDEX `deleted` (`deleted` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci
COMMENT = 'Created by Jaffar Hussain, Task #756';

CREATE TABLE IF NOT EXISTS `usa_raw`.`us_assisted_housing_files` (
  `id` int auto_increment primary key,
  `status` VARCHAR(255) DEFAULT 'processing',
  `data_source_url` TEXT NULL DEFAULT NULL,
  `data_source_file` VARCHAR(255) NULL DEFAULT NULL,
  `run_id` BIGINT(20) NULL DEFAULT NULL,
  `md5_hash` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) DEFAULT 'Jaffar Hussain',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `md5` (`md5_hash` ASC)  ,
  INDEX `run_id` (`run_id` ASC)  ,
  INDEX `status_idx` (`status`)
) 
ENGINE = InnoDB
DEFAULT CHARSET = `utf8mb4` 
COLLATE = utf8mb4_unicode_520_ci 
COMMENT = 'Created by Jaffar Hussain, Task #756';
